rackerlabs/encore-ui

src/rxSortableColumn/docs/rxSortableColumn.midway.js, src/rxSortableColumn/rxSortableColumn.page.js
We seem to be experimenting some techmological differences. View the travis logs to see more, as well as the long-form comments in https://github.com/rackerlabs/encore-ui/commit/c298e4fade292e821a5b3958498e3727a43324ab
Useful for when you need all column names, or their sorts by table.
Includes some refactoring for column sorting, which now gets reused.
=> test(rxSortableColumn): All-column functions

src/rxFloatingHeader/rxFloatingHeader.js, src/rxFloatingHeader/rxFloatingHeader.spec.js
Adds a `.find` method that allows the developer to use selectors supported via `element.querySelector`.
https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_Started/Selectors
=> feat(rxDOMHelpers): add a ".find" method

src/rxStatusColumn/README.md, src/rxStatusColumn/docs/rxStatusColumn.js, src/rxStatusColumn/docs/rxStatusColumn.midway.js
re: https://jira.rax.io/browse/EN-1568, added better documentation about which colors/treatments to use for different types of statuses.
=> docs(rxStatusColumn): Add color info

src/rxNotify/README.md, src/rxNotify/docs/rxNotify.html, src/rxNotify/docs/rxNotify.midway.js, src/rxNotify/rxNotify.js, src/rxNotify/rxNotify.spec.js
Adds an optional parameter to `rx-notification` directive that allows it to specify a target stack to put the contents of current notification into that stack.  
By specifying the current stack, the `rx-notification` element will be removed from the DOM and it's contents put into the defined stack via `rxNotify.add`
=> feat(rxNotification): add ability to add a notification from a stack

src/rxForm/docs/rxForm.midway.js, src/rxForm/rxForm.page.js
I have no idea why I exposed an `allOptions` call that returned every option as an object. This replaces that with a more suitable `options` call that returns all option's text, and does away with `allOptions` altogether.
This does make it a breaking change, but I'm almost certain no one was using it before. It can wait until other breaking changes are planned for a release to avoid excessive version increments.
=> test(rxForm): Prefer options' text over allOptions

src/rxAccountInfo/rxAccountInfo.page.js, src/rxActionMenu/rxActionMenu.page.js, src/rxApp/docs/rxApp.midway.js, src/rxApp/rxApp.page.js, src/rxBreadcrumbs/docs/rxBreadcrumbs.midway.js, src/rxBreadcrumbs/rxBreadcrumbs.page.js, src/rxEnvironment/rxEnvironment.page.js, src/rxFeedback/rxFeedback.page.js, src/rxFloatingHeader/rxFloatingHeader.page.js, src/rxForm/rxForm.page.js, src/rxPaginate/rxPaginate.page.js, src/rxPermission/rxPermission.page.js, src/rxSortableColumn/rxSortableColumn.page.js, src/rxSpinner/docs/rxSpinner.midway.js, src/rxSpinner/rxSpinner.page.js, src/rxStatusColumn/docs/rxStatusColumn.midway.js, src/tabs/tabs.page.js
This started as a chore to clean up comments, but it ended up becoming more. I realized that my editor makes it easy to make multiline comments by creating many single-line comments, and that this is a bit hard on the eyes. I'm switching over to multiline comments because they look better.
Also, since I submitted a pull request with breaking changes in it earlier this week, I thought I might as well get as many of them as I can for the minor version change that the first will cause.
=> E2e multiline comments everywhere, with minor breaking changes

src/rxStatusColumn/docs/rxStatusColumn.js, src/rxStatusColumn/docs/rxStatusColumn.midway.js, src/rxStatusColumn/rxStatusColumn.page.js
BREAKING CHANGE: Completely overhauls the page objects for
rxStatusColumn, anything that was there before is almost certainly
invalid now. The only exception to this is the `.api` property.
=> test(rxStatusColumn): Page objects

src/tabs/docs/tabs.midway.js, src/tabs/tabs.page.js
BREAKING CHANGE: Avoid functions that iterate over a collection of sub
components and return them as an object. It's slow and typically not
used. Prefer the use of the term `.names` (as is used everywhere else),
instead of `.allNames`.
=> test(tabs): Remove `.all`, use `.names` instead

src/rxNotify/rxNotify.page.js
Actually, none of you guys can spell... the code uses 'dismissable'
in about 1000 places.  This isn`t a word!  Should be 'dismissible'.
Changing it would break the interwebs though, so I recommend a firm
"Will Not Fix" on that.
=> chore(test): @droogans still can't spell

src/rxSortableColumn/rxSortableColumn.page.js, src/rxSortableColumn/templates/rxSortableColumn.html, src/rxStatusColumn/README.md, src/rxStatusColumn/docs/rxStatusColumn.html, src/rxStatusColumn/docs/rxStatusColumn.js, src/rxStatusColumn/docs/rxStatusColumn.midway.js, src/rxStatusColumn/rxStatusColumn.js, src/rxStatusColumn/rxStatusColumn.less
This commit puts the sort icon into the <button> that rxSortableColumn
creates, allowing us to click on the sort arrow itself.
This also updates rxStatusColumn to allow for sorting of the status
column. It adds documentation to the rxStatusColumn demo page to show
how to do this.
Finally, we also fixed a problem where tooltips would not show for
ACTIVE and PENDING status column cells. It was slightly related to
the sorting issue, so it has been bundled in to this commit.
Closes #732
Closes #733
=> fix(rxSortableColumn): Put sort arrow in <button> and show how to sort rxStatusColumn

src/rxAccountInfo/README.md, src/rxAccountInfo/docs/rxAccountInfo.html, src/rxAccountInfo/docs/rxAccountInfo.js, src/rxAccountInfo/docs/rxAccountInfo.midway.js, src/rxAccountInfo/rxAccountInfo.js, src/rxAccountInfo/rxAccountInfo.less, src/rxAccountInfo/rxAccountInfo.page.js, src/rxAccountInfo/rxAccountInfo.spec.js, src/rxAccountInfo/templates/rxAccountInfoBanner.html, src/rxApp/README.md, src/rxApp/docs/rxApp.html, src/rxApp/rxApp.js, src/rxApp/templates/rxPage.html
Previously `rxAccountInfo` was a big blue box that you could place anywhere on the page. That version is still supported to give people a chance to move this version, but now if you pass `account-info-banner="true"` to the directive, it will draw with the new style.
You should no longer explicitly place `<rx-account-info>` on your pages. It is now part of `rxPage`, and will automatically be inserted if you pass `account-number="..."` to `<rx-page>`
When used on a Cloud page, the account info will look like this:
When used on any other page, it will be drawn without the user select drop-down
=> Account info under breadcrumbs

src/rxSortableColumn/README.md, src/rxSortableColumn/docs/rxSortableColumn.html, src/rxSortableColumn/docs/rxSortableColumn.js, src/rxSortableColumn/docs/rxSortableColumn.midway.js, src/rxSortableColumn/rxSortableColumn.js, src/rxSortableColumn/rxSortableColumn.spec.js
Adds the rxSortEmptyTop filter in module rxSortableColumn to allow moving empty values to the top of the list in ascending order, and the bottom of the list in descending order.
=> feat(rxSortEmptyTop): DCXAPPS-1335 Add filter for placing empty values first

src/rxForm/rxForm.page.js, src/rxForm/templates/rxFormOptionTable.html
This is part of @glynnis's work to enforce an empty message in all tables in Encore UI.  Here, the text color is simply changing from red to the default color.
=> fix(rxFormOptionTable): Change color of empty message text.

src/rxFloatingHeader/rxFloatingHeader.js, src/rxFloatingHeader/rxFloatingHeader.spec.js
Fixes #756 
The issue is that a `select` element has a `length` property, which returns the number of options it has.  That was causing the `wrapAll` method to thing that the element was actually an array of elements.  Further, it is possible to access a specific option by its index, e.g. `selectElement[0] === optionElement`.
=> fix(rxDOMHelper): Properly wrap a select node instead of its options.

src/rxForm/rxForm.less
There is a visual bug with our select inputs.  These screenshots are taken from [this doc page](http://rackerlabs.github.io/encore-ui/#/styleguide/forms) (except locally).
using Chrome 40.0.2214.93 and Firefox 35.0.1
=> fix(select): Adjust height of before content.

src/rxNotify/docs/rxNotify.html, src/rxNotify/docs/rxNotify.midway.js, src/rxNotify/rxNotify.less
Removed StyleDocco lines since we already have those examples represented in the current demo.
Added styles for link colors within rxNotify, and put links into the demo to illustrate:
Closes #743.
=> style(rxNotify): add styles for link color

src/rxStatusColumn/README.md, src/rxStatusColumn/docs/rxStatusColumn.js, src/rxStatusColumn/docs/rxStatusColumn.midway.js, src/rxStatusColumn/rxStatusColumn.page.js
Updated statuses here to provide more real-world examples of how we use them, so new teams are more likely to understand and utilize status mappings correctly.
=> docs(statusColumn): update demo to reflect real status usage

src/rxApp/rxApp.less, src/rxForm/rxForm.less, src/rxPaginate/rxPaginate.less, src/styles/flexbox.less, src/tabs/tabs.less
* pulled in better flexbox mixins from https://github.com/CITguy/moar-elements/blob/master/flexbox.less
* majority of mixins match non-prefixed properties
* replaced prefixed properties with mixins
* Modified existing mixins to use new mixin definitions
* .flexbox-direction() -> .flex-direction()
* .flexbox-order() -> .order()
* .flexbox-display() -> .flexbox()
* .flexbox-wrap() -> .flex-wrap()
* .flexbox-pack() -> .justify-content()
* .flexbox-align() -> .align-items()
* .flexbox-grow() -> .flex-grow()
* .flexbox() -> .flex()
=> fix(flexbox): normalize flexbox mixins and usage

grunt-tasks/modules.js, grunt-tasks/options/copy.js, package.json
Specifically to fix:
```
npm WARN deprecated node-markdown@0.1.1: highlight is deprecated in favor of "highliht.js"
```
[`node-markdown`](https://github.com/andris9/node-markdown) has been abandoned. Maintainer suggests replacing in favor of [`marked`](https://www.npmjs.com/package/marked).
* replace `node-markdown` with `marked`
=> chore(npm): replace node-markdown with marked

src/rxApp/rxApp.js
$routeParams is not ready until the current route has successfully
resolved. This was causing a race condition if the nav directive
tried to use it before the route finished. $route.current.params
will always be ready
=> fix(rxAccountUsers): Switch to $route from $routeParams

grunt-tasks/rxPageObjects.js
Didn't catch this in the big rebase operation on Thursday. This is why there are no docs in the npm module home page.
=> docs(tests): Publish after creating docs

src/rxModalAction/README.md, src/rxModalAction/docs/rxModalAction.html, src/rxModalAction/docs/rxModalAction.js, src/rxModalAction/rxModalAction.js, src/rxModalAction/rxModalAction.spec.js, src/rxModalAction/templates/rxModalActionForm.html, src/rxModalAction/templates/rxModalFooters.html
This PR addresses issue #799, and I suppose #814 to some degree.  It is intended for modals that kick of tracked processes to hide the submit and cancel buttons after the process is kicked off.  It could possibly be used/adapted for implementing a wizard in the modal.
This solution is backwards compatible with existing modals, meaning existing (and some future) uses of  `rxModalForm` do not have to worry about manipulating the modal's state.
=> feat(rxModalAction): Make footer content stateful.

src/typeahead/typeahead.less
=> fix(typeahead): Show typeahead in front of textarea.

grunt-tasks/options/concat.js, src/rxCharacterCount/rxCharacterCount.exercise.js
The [regex rule for concatenation](https://github.com/rackerlabs/encore-ui/blob/master/grunt-tasks/options/concat.js#L46) does not support having the `.js` file extension.  This breaks v1.9.0 of the npm module.
```
$ node
> require('rx-page-objects')
Error: Cannot find module './rxCharacterCount.page.js'
```
=> fix(rxPageObjects): Exercise written with incompatible require path.

src/rxCharacterCount/README.md, src/rxCharacterCount/rxCharacterCount.exercise.js, src/rxCharacterCount/rxCharacterCount.js, src/rxCharacterCount/rxCharacterCount.less, src/rxCharacterCount/rxCharacterCount.page.js, src/rxCharacterCount/rxCharacterCount.spec.js, src/rxForm/rxForm.less, src/styles/mixins.less
Fixes #820 
There are some concerns about the accessibility of using a `contenteditable` element instead of an input, so instead a background is provided for the input.  A drawback of this approach is that the width of the background must be the same as the input.  Since we already direct developers to apply an overriding style to change the width (see comments), this seemed like an acceptable constraint.
=> feat(rxCharacterCount): Highlight characters over the limit.

demo/assets/demo.less, demo/assets/generated_demo.css, demo/styleguide/forms.html, demo/styleguide/forms/rx-form-item.html, src/rxCharacterCount/README.md, src/rxCharacterCount/docs/rxCharacterCount.html, src/rxCharacterCount/rxCharacterCount.js, src/rxCharacterCount/rxCharacterCount.less, src/rxCharacterCount/rxCharacterCount.spec.js
Closes #847
Properly clean up the character count and other generated elements,
created when rx-character-count is used on an element.
This also moves the character count into the `.counted-input-wrapper`
div. Previously it sat outside of it.
BREAKING CHANGE
We've removed the `.character-count-wrapper` class. Previously we
set widths on this class. It ended up being redundant, widths
should now be set w.r.t. `.counted-input-wrapper`
=> fix(rxCharacterCount): Clean up the generated elements

demo/styleguide/forms.html, demo/styleguide/forms/disabled.html, src/rxForm/docs/rxForm.html, src/rxForm/rxForm.less
We didn't have styles for this previously. This addresses part of #758, but there is still the question of changing the color of select box arrows, which I looked into but didn't do as part of this PR because it's going to be complex.
=> style(rxForm): add styles for disabled input box

package.json
Trying to do a release, and we're running into https://github.com/olov/ng-annotate/issues/139 Updating our grunt-ng-annotate (which brings in a new ngAnnotate) fixes it.
=> chore(ngAnnotate): Upgrade to 0.10.0

src/metadata/docs/metadata.html, src/metadata/metadata.less
* remove `float` from `<dd>`
* move padding from `<dd>` to `<dt>` margin
* update styling based on [EOD-643](https://jira.rax.io/browse/EOD-643)
**POTENTIAL BREAKING CHANGE:**
* removed `.list-definition` class and consolidated to using just `.metadata`
Closes #870
=> fix(metadata): correct/update styling

guides/architecture.md
We've removed Style Docco from Encore, so I'm taking it out of docs here too.
=> Remove reference Style Docco

src/rxCharacterCount/README.md, src/rxCharacterCount/docs/rxCharacterCount.html, src/rxCharacterCount/docs/rxCharacterCount.js, src/rxCharacterCount/docs/rxCharacterCount.midway.js, src/rxCharacterCount/rxCharacterCount.exercise.js, src/rxCharacterCount/rxCharacterCount.js, src/rxCharacterCount/rxCharacterCount.spec.js
This is a quick fix to add the `highlight` attribute to `rx-character-count`.  It is not intended to address any of the known issues with the highlighting, but rather to get the general component to a better state.
=> feat(rxCharacterCount): turn highlighing off by default

src/rxBreadcrumbs/docs/rxBreadcrumbs.midway.js, src/rxBreadcrumbs/rxBreadcrumbs.page.js
Note that there were no midways or specs that test visit.  The click function does not bubble, so we need to actually click the link itself.
=> fix(rxBreadcrumbs): Fix rxBreadcrumbs.visit();

src/tabs/tabs.less
* Add blue border around tab content area to provide visual context for tab
content areas (helpful especially for long screen that involve scrolling).
* Add small margin between tabs themselves so they are more visually distinct
from one another.
Before:
After:
=> feat(tabs): Update styles for tab component

src/rxPaginate/rxPaginate.exercise.js
@parlarjb (or anyone for that matter) if you can think of a good way to catch more of these exercise edge cases without making the demo site unreadable with dozens of components all over the place, I'd appreciate it.
This one only shows up when you have a pagination element with one page of data on it being exercised.
=> test(rxPaginate): Handle one-page exercises

grunt-tasks/options/concat.js
Since exercises need their underlying components to run, the
`exports.exercise = require('./exercise');` line needs to be below all
index.js components in order to prevent an infinite require loop from
occurring.
=> fix(exercises): Resolve require-loop

src/rxPaginate/rxPaginate.js
After deploying the new pagination code, we noticed some infinite
digest problems in Cloud. It turns out we were trying to go
to the last page over and over. Now we check if we're already
on the last page, and only go if we're not.
=> fix(rxPaginate): Fix infinite loop on one page tables

package.json
Our ability to run grunt tasks was breaking because of
some breaking dependency changes. This fixes that.
=> chore(dependencies): Go to grunt-connect-proxy 0.2.0

grunt-tasks/options/copy.js, grunt-tasks/util/config.js
Closes #635
This will include our flexbox.less, mixins.less and vars.less
with bower, so projects can build against our variables.
=> feat(LESS): Bundle our main LESS files with bower

src/rxForm/rxForm.less, src/styles/vars.less
Please see [EOD-646](https://jira.rax.io/browse/EOD-646) for more details. This now means the variable `@inputBorderColorValid` is unused -- I can remove it as well if we see no future need for it. 
@glynnis @ElementE
=> fix(rxForm): Remove blue ng-valid border on dirty form fields

demo/styleguide/tables.html, demo/styleguide/tables/single-action.html, src/rxButton/rxButton.less
Fixes #908 
The markup is a little more verbose than I would like, but pointer events aren't allowed on disabled elements, hence the need to wrap the button (and to use a button instead of a link).
=> docs(tables): add demo for table rows with a single action

demo/styleguide/buttons.html, demo/styleguide/buttons/custom-buttons.html, src/rxButton/rxButton.less, src/styles/vars.less
Fixes #910 
*In the screenshot, the rightmost button is showing the hover styles (the mouse was not captured).
@ElementE I guessed at some of the dimensions you posted in the issue, so let me know where I have erred.  Also, I purposefully gave corners (not rounded) to the inner buttons so that the control looks good with more than two buttons, though that was not part of your demo either.
@glynnis any suggestions for the docs?
=> feat(rxButton): add button group styles

src/rxRadio/docs/rxRadio.html, src/rxRadio/rxRadio.less, src/styles/vars.less
(Noticed this while playing around with `rxFormOptionTable`.)
*Before - Notice the white corners on the gray and green backgrounds*
*After - no more white corners*
=> fix(rxRadio): fix broken styles

grunt-tasks/component-template/root/docs/component.js
Update component template to use the `.controller('myController', function ($scope) {...})` syntax. This is for angular 1.3+ support of new components.
=> fix(componentTemplate): update to .controller() syntax

src/rxCheckbox/rxCheckbox.page.js, src/rxRadio/rxRadio.page.js, src/rxSelect/README.md, src/rxSelect/docs/rxSelect.html, src/rxSelect/docs/rxSelect.js, src/rxSelect/docs/rxSelect.midway.js, src/rxSelect/rxSelect.exercise.js, src/rxSelect/rxSelect.js, src/rxSelect/rxSelect.less, src/rxSelect/rxSelect.page.js, src/styles/vars.less, wraith/configs/config.yaml
Per necessity of rxForm rework, but this directive can stand alone for use elsewhere in the framework.
* `$destroy` support
* apply `rx-disabled` class to wrapper if disabled by either `disabled` or `ng-disabled`
* exercises added to test common functionality
* page objects exports `rxSelect`, `htmlSelectOption`, and `htmlSelect`
* `htmlSelectOption` and `htmlSelect` provides page object support for
non-styled elements
* rxCheckbox.page.js updated to export both `rxCheckbox` and `htmlCheckbox`
* this is to provide page object support for non-styled checkboxes
* rxRadio.page.js updated to export both `rxRadio` and `htmlRadio`
* this is to provide page object support for non-styled radios
* Lays groundwork for #884
Closes #896
=> feat(rxSelect): add rxSelect component

src/rxForm/rxForm.less, src/rxForm/rxForm.page.js, src/rxForm/templates/rxFormOptionTable.html
* fix: label fills cell
* fix: label[for] points to input, not column header
* added td[data-column] for cell lookup by column
* update: use rxRadio and rxCheckbox
* includes styling fix found in another PR
Closes #249
*Before*
*After*
=> fix(rxFormOptionTable): fix label height

package.json, src/rxMisc/README.md, src/rxMisc/rxMisc.js, src/rxMisc/rxMisc.spec.js
So I was using `rxAutoSave` and figured out that I needed to change how the keys are stored in localstorage, so I had to completely overwrite the storage method.
Thought that was a bit overkill and thought this would be a more "elegant" solution
=> Add in keyMapping function to rxAutoSave

guides/css-styleguide.md
Removed `["Good CSS has a one-to-many relationship with HTML"](https://speakerdeck.com/csswizardry/big-css-1?slide=22)` which gives `presentation not found`
=> removed dead link

demo/styleguide/tables/nested-metadata.html, src/rxApp/common.less
Closes #804. Brings metadata styles up to date for the expanded table row view, and adds padding. 
This also addresses part of https://jira.rax.io/browse/UXENCORE-356.
Before:
After:
=> style(styleguide): Fix metadata styles for expanded table

src/rxStatusColumn/README.md, src/rxStatusColumn/rxStatusColumn.less
Add label to status column and center status icons
https://jira.rax.io/browse/EN-1997
=> feat(lbaas): EN-1997 Add Label to Status Column

src/rxSelect/rxSelect.js, src/rxSelect/rxSelect.less, src/rxSelectFilter/README.md, src/rxSelectFilter/docs/rxSelectFilter.html, src/rxSelectFilter/rxSelectFilter.exercise.js, src/rxSelectFilter/rxSelectFilter.js, src/rxSelectFilter/rxSelectFilter.less, src/rxSelectFilter/rxSelectFilter.page.js, src/rxSelectFilter/rxSelectFilter.spec.js, src/rxSelectFilter/templates/rxMultiSelect.html, src/rxSelectFilter/templates/rxSelectOption.html, src/styles/vars.less
Fixes #990 
Now, this input looks the same as `rx-select` and can be disabled.  Also, preview text (e.g. "2 Selected") that exceeds the width of the control will now be clipped instead of wrapping to a new line.
=> feat(rxSelectFilter): Leverage new rxCheckbox and rxSelect components

src/rxApp/rxApp.js, src/rxApp/rxApp.spec.js, src/rxApp/templates/rxAppNavItem.html, src/rxPermission/README.md, src/rxPermission/rxPermission.js, src/rxPermission/rxPermission.spec.js
Closes #958
This adds the ability to filter individual items in the nav
by requiring certain LDAP roles. If a logged-in user doesn't
have the necessary roles, then the item won't appear in the nav
for them.
Note: Before we can really start to use this, all Encore products will have to be running whatever version of the framework incorporates this change. Otherwise all nav items will be displayed when the user is in a non-updated product.
Note that I haven't explicitly documented how to add these roles to the nav. I don't know yet where the right place is for that. Likely better to increase documentation in the encore-ui-nav repo.
=> feat(rxApp): Add LDAP filtering in the nav

src/rxCheckbox/docs/rxCheckbox.html, src/rxCheckbox/docs/rxCheckbox.js, src/rxCheckbox/docs/rxCheckbox.midway.js, src/rxCheckbox/rxCheckbox.less, src/rxRadio/docs/rxRadio.html, src/rxRadio/docs/rxRadio.js, src/rxRadio/docs/rxRadio.midway.js, src/rxRadio/rxRadio.less, src/rxSelect/docs/rxSelect.html, src/rxSelect/docs/rxSelect.js, src/rxSelect/docs/rxSelect.midway.js, src/rxSelect/rxSelect.less
Disabled styles should trump valid and invalid styling for `rxCheckbox`, `rxRadio`, and `rxSelect`.
* Styles updated accordingly
* Demo pages and midways updated to reflect new tests
=> fix(styles): disabled styles trump valid and invalid styles

grunt-tasks/build.js, grunt-tasks/options/copy.js, grunt-tasks/util/config.js, src/rxApp/common.less
1. **bower**: Because `font-awesome` is already a bower dependency, it will be installed automatically as a sibling bower dependency within the target app (i.e. no need to bundle).
2. **demo**: `demo/index.html` is already including the font-awesome CSS (configured via `grunt wiredep`).
3. Likely related to #774
=> fix(fontawesome): stop bundling FontAwesome

src/rxCheckbox/rxCheckbox.js, src/rxRadio/rxRadio.js, src/rxSelect/rxSelect.js
This is to provide support for angular 1.3+
Though we're not entirely sure what caused the issue, it seems that the `wrapper` variable used to wrap the native form elements seems to be disconnected from the DOM in angular 1.3.0 and above.  The workaround is to use `element.parent()` instead of `wrapper`.
=> fix(ng1dot3): modify for angular 1.3 support

src/rxSelectFilter/rxSelectFilter.js, src/rxSelectFilter/rxSelectFilter.spec.js
Fixex #984 
The preview text requires that the DOM has been updated, as it uses an option's label in some cases.  Also, the component internally tracks the list of available options, and this list is used in the preview text logic.  However, items weren't being removed if the option element was removed.
=> fix(rxSelectFilter): correctly render preselected options

src/rxBulkSelect/README.md, src/rxBulkSelect/docs/rxBulkSelect.html, src/rxBulkSelect/docs/rxBulkSelect.js, src/rxBulkSelect/docs/rxBulkSelect.midway.js, src/rxBulkSelect/rxBulkSelect.exercise.js, src/rxBulkSelect/rxBulkSelect.js, src/rxBulkSelect/rxBulkSelect.less, src/rxBulkSelect/rxBulkSelect.page.js, src/rxBulkSelect/rxBulkSelect.spec.js, src/rxBulkSelect/templates/rxBatchActions.html, src/rxBulkSelect/templates/rxBulkSelectMessage.html
Fixes #703 
The only significant change to the original implementation was removing `rxTableFilter` in favor of `rxBatchActions`, which is more generic (doesn't control the entire header row).
This does not include any code outside the demo that relates to the modal.  I included some guidelines in the readme based off what I saw [here](https://projects.invisionapp.com/d/#/projects/2559734).
=> Add rxBulkSelect component

src/rxApp/rxApp.js, src/rxApp/rxApp.spec.js
When a user searches for an account they will, by default, have the admin user for that account selected.  They can then select a different user if they choose.
JIRA: https://jira.rax.io/browse/EN-1912
=> feat(rxApp): EN-1912 default to an accounts admin user

src/rxBulkSelect/rxBulkSelect.js, src/rxBulkSelect/rxBulkSelect.spec.js, src/rxFloatingHeader/docs/rxFloatingHeader.html, src/rxFloatingHeader/rxFloatingHeader.js, src/rxSearchBox/rxSearchBox.js
Closes #1038
Closes #1047
`rxBulkSelect` and `rxSearchBox` have their templates inserted _after_ the `rxFloatingHeader` `link` function runs. `rxFloatingHeader` needs to know about their content, so we now have them explicitly tell `rxFloatingHeader` to rerun once they're ready.
=> fix(rxFloatingHeader): rxSearchBox and rxBulkSelect fixes

src/rxCheckbox/rxCheckbox.js, src/rxRadio/rxRadio.js, src/rxSelect/rxSelect.js
Found an issue where essentially we have `rxFormOptionTable` in tabs, and as you switch tabs, the table gets destroyed thanks to an `ng-if` things in the browser/unit-tests seem ok.   
But with the inclusion of the new `rx-radio` `rx-checkbox` elements  
```bash
TypeError: 'undefined' is not a function (evaluating 'parent[0].remove()')
at /Users/fred7307/Workspace/encore-tq-ui/app/bower_components/encore-ui/encore-ui-tpls.js:2067
```
Essentially my finding was that `parent` DOMElement in PhantomJS seems to have no `remove` function (in fact none of the DOMElements do), however the `jqlite` wrapper does.  Not sure if this was just an uncaught or overseen issue.
The reason for the `$evalSync` was due to if we call `parent.remove()` within the `element.$destroy` event, then an infinite loop …
=> fix(rxFormElements): Work around for removing parent elements

demo/assets/demo.less
Closes #940.
We'll be tweaking documentation styles, so code blocks will appear on the grey Encore background in most contexts -- more details and mock-ups coming, just posting a screen shot here as a rough example.
@ElementE Can you review and let me know if these colors look good to you? I figure we'll likely revisit when we do more detailed color work/standardization in the future.
=> style(demo): Add visual styles for code blocks

src/rxSelect/rxSelect.page.js
Fix rxSelect.main to return an rxSelect object.
Fix htmlSelect.main to return an htmlselect object.
=> fix(rxSelect) main methods do not return

src/rxBulkSelect/rxBulkSelect.js, src/rxBulkSelect/rxBulkSelect.spec.js
The `rx-bulk-select-message` directive was being added to every `<thead>` in the table, which is fine until you need nested tables (like in the [docs](http://rackerlabs.github.io/encore-ui/#/styleguide/tables)).
=> fix(rxBulkSelect): only add bulk message to root table

src/layout/docs/responsiveLayout.html, src/layout/layout.less, src/layout/responsive.less
Using layout-margin produces margins around all edges of the child elements by default. For keeping a consistent visual look in our framework and considering that the layout module is intended to replace the Pure Grid system, the outer margins on outer child elements should be removed. This will mean that layout-margin will no longer be compatible with flex-order, as css selectors currently work based on DOM order, (ie, depending on the flex-order, the first and last child selector may not represent the outer elements).
=> feat(FlexLayout): remove outer margins on layout-margin

.travis.yml, utils/visual-regression/clone.sh
Don't install visual regression tools, which take nearly 3 to 5 minutes,
if the tools aren't even going to be used.
By placing these steps inside of the `after_success` block, it prevents
these installs should the tests fail.
By placing these steps after a check for secure variables existing, it
prevents these installs for PRs that will never run the visual
regression tests in the first place, like from a fork.
=> fix(travis): Valid visual regression installs only

demo/styleguide/basics.html, demo/styleguide/buttons.html, demo/styleguide/forms.html, demo/styleguide/layouts.html, demo/styleguide/modals.html, demo/styleguide/tables.html, src/rxApp/README.md, src/rxBreadcrumbs/README.md, src/rxButton/README.md, src/rxCharacterCount/README.md, src/rxCheckbox/README.md, src/rxForm/README.md, src/rxMisc/README.md, src/rxOptionTable/README.md, src/rxRadio/README.md, src/rxSelect/README.md, src/rxStatus/README.md, src/rxToggleSwitch/README.md
* Use correct relative link URLs:
* removing leading forward slash
* Normalized relative links:
* modified `rackerlabs.github.io` links to use relative paths, where necessary
This needs to be added ASAP or the new rxForm documentation links (as well as a few others) will be 9 kinds of broken.
=> DOCS: normalize relative links

demo/styleguide/tables.html, demo/styleguide/tables/delete.html, src/rxApp/common.less
Fixes #930 
To clarify the screenshot, my mouse is hovering the x, but it isn't visible.  The x is not red unless hovered.
=> docs(tables): Add proper styling for delete X pattern.

demo/assets/demo.less, demo/assets/generated_demo.css
While I realize that these styles will probably be out of date once design is finished with their work, but in the mean time, this is a fix to make documentation more legible.
=> docs(styles): fast follow update to <code> styles

src/rxFeedback/rxFeedback.js, src/rxFeedback/rxFeedback.spec.js, src/rxFeedback/templates/rxFeedback.html
`rxFeedback` is displaying whatever the url was at the application's bootstrap, which is not necessarily the url at the time the feedback is submitted.  This has no effect on the api call that is made.
To reproduce this bug, go to the home page for the docs, and then click to any other page.  Open up the feedback modal, and you'll see
=> fix(rxFeedback): Show url of current page.

.travis.yml
There are intermittent failures in Travis end to end test runs. This is attempting to fix that.
This at least narrows it down a little bit, since we're all using Firefox 35.0 locally.
I've found that Selenium server is at 2.46 in both places, so it shouldn't be that. Protractor is latest in both places. This appears to be the only obvious place to start for now.
I'm going to keep running this PR over and over for the next few days (?).
| Run Number | Result |
|------|-------|
| 1 | Pass |
| 2 | Pass |
| 3 | Pass |
| 4 | Pass |
| 5 | Pass |
| 6 | Pass |
| 7 | [Fail](https://github.com/rackerlabs/encore-ui/pull/1092#issuecomment-119558643) |
| 8 | Pass |
| 9 | Pass |
| 10 | Pass |
| 11 | Pass |
| 12 | Pass |
| 13 | Pass |
| 14 | Pass |
| 15 | Pass |
| 16 | Pass |
| 17 | Pass |
| 18 | Pass | …
=> chore(travis): Use Firefox 35.0

src/rxButton/README.md, src/rxButton/docs/rxButton.html, src/rxButton/rxButton.js
This is a pretty old component that has almost no documentation.
=> docs(rxButton): Improve usage documentation.

src/rxCheckbox/docs/rxCheckbox.html, src/rxCheckbox/docs/rxCheckbox.midway.js, src/rxCheckbox/rxCheckbox.exercise.js, src/rxCheckbox/rxCheckbox.page.js, src/rxForm/rxForm.page.js, src/rxRadio/docs/rxRadio.html, src/rxRadio/docs/rxRadio.js, src/rxRadio/docs/rxRadio.midway.js, src/rxRadio/rxRadio.exercise.js, src/rxRadio/rxRadio.page.js, src/rxSelect/docs/rxSelect.html, src/rxSelect/docs/rxSelect.js, src/rxSelect/docs/rxSelect.midway.js, src/rxSelect/rxSelect.exercise.js, src/rxSelect/rxSelect.page.js
This addresses a couple of issues with the rxForm refactor, from the perspective of the page objects.
1. There are some missing tests for plain old HTML elements. These have been added in the demo "for comparison", and also to test against.
2. Some of the exercises now assert against more specific things (such as text in select elements).
3. ~~The exercises no longer ask for what type of element the component is (these functions have been removed from the page objects entirely as well). If you're using a checkbox/radio/select element, you can interact with it in specific ways to determine it's type. There's no need to ask explicitly.~~ This was added back in. No change here.
4. The `html*` and `rx*` page objects have been unified under a single object that responds to both plain html-type …
=> Rx form page object refactor

CONTRIBUTING.md
This isn't a GitHub Issues, but I think it's a good idea.
=> docs(Contributing): update squash guide to mention explicit branch

src/rxApp/rxApp.js, src/rxApp/rxApp.spec.js
We can achieve the same overall goal by sorting the options in the
dropdown by admin instead of using `switchUser`.
JIRA: relates to https://jira.rax.io/browse/EN-1912
=> fix(accountUsers): fixing looping switch to admin issue

src/rxCollapse/README.md
For more context, see: https://github.com/rackerlabs/encore-ui/pull/1107#issuecomment-125983838
We should also add this kind of documentation to the Style Guide in the metadata section. Issue for that here: https://jira.rax.io/browse/FRMW-97
=> docs(rxCollapse): Add more prescriptive rules around use of see more

src/rxForm/rxForm.less, src/styles/vars.less
*Resubmitted #1127 for visual regression hooks*
Per chat with @glynnis, the font sizes for items within `rxForm` needed corrected.
=> chore(styles): correct font sizes

guides/versioning.md
`npm adduser` (by default) will add the given user credentials to the currently set registry. Given that a user may have the internal npm registry set as their default, it would add the credentials to the incorrect registry.  This will make sure that the public npmjs registry is the target for the additional credentials.
=> docs(VERSIONING): clarification on npm adduser

demo/demo.js, demo/guides/guideController.js, demo/overview.html, src/rxBreadcrumbs/docs/rxBreadcrumbs.midway.js, src/rxEnvironment/rxEnvironment.js
This should make nesting pages under an existing breadcrumb much simpler. Perhaps more of the style guide can become hierarchical in the future.
This also makes testing against the `ghPages` environment simpler. By changing the regular expression to match `/localhost/`, you can simulate what the url will look like when published to Github pages.
=> Fix gh pages links

demo/assets/demo.less, demo/assets/generated_demo.css, demo/styleguide/basics.html, demo/styleguide/basics/headings.html, src/rxApp/common.less, src/rxApp/rxApp.less
* added base H1-H6 styles above legacy .title styles
* allows for backward compatibility as developers update their code
* added namespace for upcoming work on new styleguide pages
JIRA: https://jira.rax.io/browse/FRMW-37
=> chore(headings): Deprecate .title classes/subclasses

src/rxPaginate/docs/rxPaginate.html, src/rxPaginate/rxPaginate.js, src/rxPaginate/rxPaginate.less, src/rxPaginate/rxPaginate.spec.js, src/rxPaginate/templates/rxPaginate.html
Correct me if I am wrong, but it seems this was left in on accident when `rxLoadingOverlay` was added.
Fixes #1139
=> fix(rxPaginate): Remove old loading overlay.

src/rxApp/common.less, src/rxForm/README.md, src/rxForm/docs/rxForm.html, src/rxForm/rxForm.less, src/rxSearchBox/rxSearchBox.less, src/styles/vars.less
* rxSearchBox restyled
* italic placeholder
* font-size inherited
* rxForm LESS updated for rxSearchBox support
* deprecate `.filter-box` CSS class
JIRA: https://jira.rax.io/browse/FRMW-107
=> fix(styles): rxSearchBox + rxForm

grunt-tasks/component-template/root/README.md, grunt-tasks/component-template/root/component.js
* add quick blurb to define basic component ngdocs overview page
* add link to component ngdocs overview page in README
=> chore(componentTemplate): update for standard component ngdocs

demo/demo.js, demo/styleguide/basics.html, demo/styleguide/forms.html
Fixes #1183 
* remove old documentation section for collapsible element
* correct old "wells" links to use new href
=> docs(links): correct/remove dead links and documentation

demo/assets/demo.less, src/layout/responsiveLayout.less, src/progressbar/progressbar.less, src/rxCharacterCount/rxCharacterCount.less, src/rxCollapse/rxCollapse.less, src/rxStatusColumn/rxStatusColumn.less
Resubmitted PR https://github.com/rackerlabs/encore-ui/pull/1190 with proper upstream/origin workflow.  Thanks to @CITguy @TheNando @halkon for the assist.
Changed hard-coded hex colors to named variables https://jira.rax.io/browse/FRMW-131.  I also checked for uppercase hex colors.
=> refactor(less): FRMW-131 use named color variables

demo/styleguide/forms/manual-saving.html, src/rxButton/rxButton.less
* update manual save example to use better markup based on current CSS (per conversation with @glynnis)
* old markup using deprecated `title` class on inline `<span>` 
* browser doesn't apply margins to `inline` elements
* now using `<h3>`
* replace rxButton font-sizes with static, `px` values (per [JIRA 208](https://jira.rax.io/browse/FRMW-208))
=> fix(bugs): manual save + rxButton

grunt-tasks/build.js, grunt-tasks/default.js, grunt-tasks/minify.js, grunt-tasks/modules.js, grunt-tasks/options/concat.js, grunt-tasks/options/karma.js, karma.conf.js
Provides the ability to split up the monolithic component javascript source files. In addition to current file structure, this will support the following hierarchy:
```
src/
<component>/
docs/
templates/ 
README.md
<component>.less
<component>.module.js # defines angular module for component
scripts/
<item>.js
<item>.exercise.js
<item>.page.js
<item>.spec.js
```
=> chore(grunt): support for splitting up monolithic js source files

src/rxAuth/README.md, src/rxAuth/rxAuth.js
JIRA: https://jira.rax.io/browse/FRMW-163
Migrate `rxAuth` to API Documentation
=> docs(rxAuth): FRMW-163-Migrate rxAuth to API Docs

src/rxBulkSelect/rxBulkSelect.exercise.js
This shouldn't be hard-coded at 10.
Addresses issue: #1225
Additionally, prefer positive to negative matching on options.
LGTMs
=> chore(exercises): Add count to rxBulkSelect exercise options

src/rxMetadata/README.md, src/rxMetadata/rxMetadata.js
Sprint 2: JIRA FRMW-154: https://jira.rax.io/browse/FRMW-154
I am migrating `rxMetadata` API Documentation in README to API docs.  `metadata` is deprecated.
=> feat(docs): FRMW-154-Migrate rxMetadata to API docs

bower.json
Pin to angular 1.2.28 for time being.  Something with 1.2.29 is causing all kinds of havoc with Travis and testing.
=> chore(bower): anchor to ng1.2.28

README.md
This was discussed in sprint planning today -- all the information from the README that was deleted is out of date or has already been specified somewhere else in the Framework Overview.
=> docs(README): Remove out of date info

src/rxMisc/docs/rxMisc.midway.js, src/rxMisc/rxMisc.page.js
Attempt to fix #1279.
The rxMisc.page.js currencyToPennies function will sometimes `parseInt(15013.9999999999998)` when the expected result is 15014.
I removed the `it('should lose precision when converting a fraction of a penny to an int')` test case per @Droogans suggestion.
=> test(rxMisc): #1279 Round before parseInt in currencyToPennies

src/rxMisc/docs/rxMisc.midway.js, src/rxMisc/rxMisc.page.js
I forgot to update the ngdoc for currencyToPennies in my last commit. Oops!
Also removed an irrelevant test since we're now saying currencyToPennies should not be passed fractions of a penny.
=> test(rxMisc): Remove a test and update currencyToPennies ngdoc

src/rxTags/rxTags.page.js, src/rxTags/templates/rxTags.html
* revert template back to `ng-keydown` (b/c Chrome doesn't work with `ng-keypress`)
* use protractor chord (SHIFT + BACK_SPACE) to workaround weirdness
* without this correction, rxTags will NOT work on Chrome
=> fix(rxTags): midway revert and workaround

protractor.conf.js, src/rxFloatingHeader/docs/rxFloatingHeader.midway.js, src/rxFloatingHeader/rxFloatingHeader.page.js, src/rxMisc/rxMisc.page.js
Expanded upon #1229, to apply Y value tolerance to all checks.
> This isn't an issue on Travis, but when running tests locally, there is an issue where the floating header will be off by one pixel on higher resolution displays. This fix adds a tolerance around the location of the floating header during protractor tests to be +/- 2 pixels.
=> chore(rxFloatingHeader): add Y tolerance to midways

src/rxFloatingHeader/rxFloatingHeader.less
JIRA: https://jira.rax.io/browse/FRMW-66 - BUG: z-index for rxSelectFilter is behind rxFloatingHeader
Added a `z-index` criteria for `rxFloatingHeader`
=> fix(z_index): FRMW-66-Bug-fix-rxFloatingHeader

src/rxPaginate/rxPaginate.less
JIRA: https://jira.rax.io/browse/FRMW-100 - BUG: (z-Index) rxPaginate + rxFloatingHeader
Modify active page number behavior, so that it scrolls below a `rx-floating-header` component.
=> fix(z_index): FRMW-100-Bug-fix-rxPaginate

src/rxMisc/docs/rxMisc.midway.js, src/rxMisc/rxMisc.page.js
For #1234 
The rxMisc.page.currencyToPennies function can now accept an array of currencies. It still works with a single currency so it's backwards compatible.
=> test(rxMisc): #1234 Modify currencyToPennies to accept an array too

src/rxSelectFilter/rxSelectFilter.less
JIRA: https://jira.rax.io/browse/FRMW-292 - BUG: Unbreakable Long Values in rxMultiSelect
Force break extra long values in drop down boxes to wrap.
=> fix(bug): FRMW-292-Unbreakable long value rxMultiSelect

src/rxLocalStorage/docs/rxLocalStorage.midway.js, src/rxLocalStorage/rxLocalStorage.page.js
Jira: https://jira.rax.io/browse/FRMW-240
Fixed failing rxLocalStorage test ("should set and return an array of objects") that we had to .skip() about 2 weeks ago.
Note: I don't know WHY this fixes the problem.
=> test(rxLocalStorage): Fix failing array of objects test

src/rxApp/rxApp.less
JIRA: https://jira.rax.io/browse/FRMW-312 - BUG: z-index rxNotification
---
Removed `z-index` property from `.fake-select` class, which was setting the class above the `rxNotification` component.
=> fix(z_index): FRMW-312-z-index-error

src/rxForm/rxForm.js, src/rxSelectFilter/rxSelectFilter.js, src/rxSelectFilter/rxSelectFilter.spec.js
JIRA: https://jira.rax.io/browse/FRMW-293
Added `rxForm` hierarchy validation that enforces `rxSelectFilter` is a child of `rxFormSection`.
=> feat(rxSelectFilter): FRMW-293-Add rxForm hierarchy validation

src/rxBulkSelect/docs/rxBulkSelect.midway.js, src/rxBulkSelect/rxBulkSelect.exercise.js, src/rxBulkSelect/rxBulkSelect.page.js, src/rxBulkSelect/templates/rxBatchActions.html
See issue #1244
I chose to implement the batch actions menu by wrapping rxActionMenu, as they seemed to have a lot of similar functionality, but it was necessary to override several properties of rxActionMenu.
I used a pattern similar to that used in rxModalAction, however in that case you could not override core functionality of rxModalAction, which I had need to do here.  It might be worth splitting this page object up, but I felt that was less dry and would necessitate more testing.
=> chore(rxBatchActions): #1244 Add midways, exercises and page-objects

src/rxActionMenu/docs/rxActionMenu.html, src/rxActionMenu/docs/rxActionMenu.midway.js
JIRA: https://jira.rax.io/browse/FRMW-421
---
Remove deprecated CSS `.title` class from `rxActionMenu`.
=> fix(css): FRMW-421-Remove deprecated .title from rxActionMenu

package.json
Yet another random NPM module updated upstream and caused Travis builds to break.
Correct broken package and shrinkwrap dependencies to prevent this from happening again.
=> chore(npm): fix broken package

grunt-tasks/options/watch.js, src/rxBreadcrumbs/docs/rxBreadcrumbs.js, src/rxBreadcrumbs/docs/rxBreadcrumbs.midway.js, src/rxBulkSelect/scripts/rxBatchActions.js, src/rxOptionTable/docs/rxOptionTable.midway.js, src/rxOptionTable/templates/rxOptionTable.html, src/rxSearchBox/rxSearchBox.js
Backporting refactor work added in `ng1.3` branch. Should still be ng1.2 compatible.
* readability updated for `watch` config
* corrected rxBreadcrumbs demo/midway
* refactor rxOptionTable template to have `ng-switch-when` on wrapper elements
* refactor rxOptionTable to be compatible with ng1.3
* refactor rxBulkSelect to be compatible with ng1.3
* refactor rxSearchBox to be compatbile with ng1.3
=> refactor(various): refactor for future compatibility

src/rxCollapse/rxCollapse.less, src/styles/vars.less
https://jira.rax.io/browse/FRMW-333
=> style(rxCollapse): update rxCollapse to use 2.0 color palette

src/rxMisc/scripts/rxMisc.page.js
JIRA: https://jira.rax.io/browse/FRMW-451
---
Explicitly check for opening and closing parenthesis for negative numbers in `currencyToPennies`.
=> fix(bug): FRMW-451 currencyToPennies handle negative values

src/rxTags/rxTags.less
JIRA: https://jira.rax.io/browse/FRMW-328
Images have been updated to reflect the most recent commit.
Showing the Previous Colors
(Includes tota11y) Color Contrast Ratios
I used the recommended colors from Zhen, but had to change some of the matches to get a good color ratio contrast as shown.
=> style(rxTags): FRMW-328 Update rxTags To Color 2.0

demo/assets/_palette.less, demo/assets/generated_demo.css, demo/styles/color.html, src/rxApp/rxApp.less, src/rxBreadcrumbs/rxBreadcrumbs.less, src/styles/vars.less
https://jira.rax.io/browse/FRMW-335
On hover:
=> style(rxBreadcrumb): Update breadcrumbs for 2.0 color palette

demo/styles/color.html
`.palette.blue .secondary-700` DNE, replaced with `.primary`
=> fix(colors): correct styling for primary link usage

demo/assets/generated_demo.css, src/rxApp/common.less, src/rxApp/rxApp.less, src/rxButton/rxButton.less, src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-322
Re-submitting this to run the visual regression. This is the same PR as previously submitted https://github.com/rackerlabs/encore-ui/pull/1359 One Dev and Design were already LGTM. Just need one more Dev LGTM.
Before:
After:
Before:
After: 
@glynnis I think the red from before was a richer Red.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
@glynnis This is the screenshot of the disabled link at `@gray-600`
This was a change I made since it was in common.less, however I realized that this was crossing into the Tables story.  I kept it in since it was a minor change. This is the before and after for it.
Before:
After:
=> style(colors): FRMW-322 Buttons/Actions

src/styles/vars.less
* readded `@tabBorder` for backward compatibility and to prevent
introduction of a breaking change
* use `@blue-700` instead
=> chore(vars): readd deprecated var

demo/styles/color.html, src/components/rxActionMenu/docs/rxActionMenu.html, src/components/rxActionMenu/rxActionMenu.less
https://jira.rax.io/browse/FRMW-331
Note that link colors within the action menus were not changed as part of this PR. Just including a screenshot of them to indicate that they have indeed inherited the work from another PR that dealt with action link colors.
=> style(rxActionMenu): update to use 2.0 colors

src/components/rxForm/rxForm.less
JIRA: https://jira.rax.io/browse/FRMW-436
---
Added `margin-bottom: 0px;` to `rxInput` -> `.button` to remove the `10px` bottom margin inherited from `rxButton`.
=> chore(rxButton): FRMW-436-removed bottom margin

src/components/rxApp/rxApp.less, src/components/rxModalAction/rxModalAction.less, src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-332
I only found modals used in the following LESS files.
* vars.less
* common.less
* rxModalAction.less
* rxApp.less
and in the following components shown below.
http://localhost:9001/#/styleguide/modals
NOTE: Keep in mind that the current rxNotify PR will take care of the notification colors.
http://localhost:9001/#/components/rxModalAction
NOTE: Form colors will be corrected in rxForm
http://localhost:9001/#/styles/wells
http://localhost:9001/#/components/rxActionMenu
http://localhost:9001/#/components/rxFeedback
http://localhost:9001/#/components/rxBulkSelect
NOTE: Table colors will be corrected when they are addressed in the Tables color story.
=> style(modals): FRMW-332 Updating Modals to Color 2.0

src/components/rxCharacterCount/docs/rxCharacterCount.midway.js, src/components/rxCheckbox/docs/rxCheckbox.midway.js, src/components/rxForm/docs/rxForm.midway.js, src/components/rxSearchBox/docs/rxSearchBox.midway.js, src/components/rxToggleSwitch/scripts/rxToggleSwitch.exercise.js
JIRA: https://jira.rax.io/browse/FRMW-513
---
Update component midways that used deprecated `cssSelector` option to use `instance` option instead.
=> chore(cssSelector): FRMW-513-tech debt remove from midways

src/components/rxCheckbox/rxCheckbox.less, src/components/rxForm/rxForm.less, src/components/rxRadio/rxRadio.less, src/components/rxSelect/rxSelect.less, src/styles/vars.less
https://jira.rax.io/browse/FRMW-324
Other form elements are coming separately. Didn't want to make this PR any bigger.
https://jira.rax.io/browse/FRMW-538 - rxMultiSelect, rxToggleSwitch, rxSelectFilter
https://jira.rax.io/browse/FRMW-539 - rxCharacterCount, rxSearchBox
=> style(rxForm): Update rxForm + elements to use 2.0 color palette

src/components/rxCharacterCount/rxCharacterCount.less, src/styles/vars.less
https://jira.rax.io/browse/FRMW-539
=> style(rxForm): update colors for rxSearchBox and rxCharacterCount

src/components/rxMultiSelect/rxMultiSelect.less, src/components/rxToggleSwitch/rxToggleSwitch.less, src/styles/vars.less
https://jira.rax.io/browse/FRMW-538
[Outdated screenshot.](https://cloud.githubusercontent.com/assets/1529366/11796430/e72a5be6-a281-11e5-8bb7-78026b894878.png)
=> style(rxForm): Update color for rxMultiSelect + rxToggleSwitch

src/components/rxSortableColumn/rxSortableColumn.less, src/components/rxSortableColumn/scripts/rxSortableColumn.page.js, src/components/rxSortableColumn/scripts/rxSortableColumn.spec.js, src/components/rxSortableColumn/templates/rxSortableColumn.html
JIRA: https://jira.rax.io/browse/FRMW-457
---
`rxSortableColumn` narrow table headers caused the sort icon to overlap the content.  Now the sort icon will wrap inside the header instead of overlapping the header content.
=> fix(rxSortableColumn): FRMW-457-fix sort icon overlapping title

src/components/rxApp/common.less, src/components/rxBulkSelect/rxBulkSelect.less, src/components/rxFloatingHeader/rxFloatingHeader.less, src/components/rxOptionTable/rxOptionTable.less, src/components/rxPaginate/rxPaginate.less, src/components/rxSortableColumn/rxSortableColumn.less, src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-321
I received Feedback from Eric in the comments below, I made my changes in my second commit, and then updated this initial comment with the latest screenshots.
This was updated after James' PR, then updated the colors here.
=> style(tables): FRMW-321 Update Tables to Color 2.0

src/components/rxMetadata/scripts/rxMetadata.page.js
The already existing term() function gives me a way to get the definitionElement.getText(), but I don't want the text.
I want the element in cases where definitionElement is a link or something and I need to make assertions on it.
=> test(rxMetadata): Add function to get a definition element.

grunt-tasks/rxPageObjects.js
`clean:rxPageObjects` was removed in a previous PR, but the `rxPageObjects` task still referenced it
=> fix(grunt): remove reference to clean:rxPageObjects

package.json
Yet another upstream dependency is breaking Travis. Pin `vinyl-fs` to 2.2.1 in attempt to correct issue.
=> fix(depedencies): pin vinyl-fs version

package.json
* undo pinning to `vinyl-fs 2.2.1` (project has released 2.3.1 to correct regression)
=> fix(npm): revert bandaid for dependency regression

src/components/rxSelect/rxSelect.less
JIRA: https://jira.rax.io/browse/FRMW-637
By setting a `z-index` of the wrapper, the `z-index` values of the children do not escape the parent context, so they don't interfere with other elements on the page.
=> fix(rxSelect): set up local stacking context

demo/index.html, demo/scripts/rxDebug.js, src/atoms/rxCheckbox/docs/rxCheckbox.html, utils/demo.page.js
* Add `rxDebug` directive to hide page content unless the `?debug` URL query parameter is present.
* This does not affect distributed code.
* Useful to hide content when midway tests are _not_ running to reduce clutter in the documentation.
```html
<p>I'll always show up!</p>
<rx-debug>
<p>I'll only show up if "?debug" is present in url!</p>
</rx-debug>
```
=> refactor(rxDebug): add rxDebug for ui testing purposes

src/components/tooltips/tooltips.less, src/styles/vars.less
Something changed with regards to css and tooltips for ng1.3-compatible ngBootstrap updates.  These changes broke styling with tooltip arrows. (Screenshots to follow in first comment).
=> refactor(tooltips): backport ng1.3 css updates

grunt-tasks/options/shell.js, grunt-tasks/rxPageObjects.js, utils/rx-page-objects/package.json
rxPageObjects deploy tasks were deploying packed versions of the deployed files, resulting in a tarball (*.tgz) file within the distributed directory. This process also packed previous tarballs already in the directory, so each subsequent tarball contained all of the previous tarballs, causing exponential file size increases to the point of failure to publish because the payload was too large.
* no tasks made use of these tarballs (grunt tasks removed)
* in my effort to troubleshoot, I accidentally removed the `package.json` (readded)
@Droogans, I'd like your seal of approval before I merge this PR.
=> fix(grunt): fix deploy tasks

grunt-tasks/options/browserSync.js, guides/ui-setup.md, package.json
I always forget to look at new components in both Chrome and Firefox. I added this tool to make it easier for me to compare the CSS (especially) side by side when writing automation code/manual testing.
This does not affect live reload in any way. This tool is designed to sync content that you watch yourself on port 3000. The actual watching happens on port 9001 still.
=> feat(browserSync): Include simple FF/Chrome syncing

demo/templates/styles/color.html, src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-700
This story and PR were created in order to update the @blue-700 hex value. Reason is so that the PhoneUI can update to this framework and make most of the blue links have a better contrast of 4.5 ratio within the panels. Most panels use the @gray-25 background color which allow this new blue color to work well with links.
=> style(color): FRMW-700 Update @blue-700 Hex Value

src/components/rxApp/docs/rxApp.js, src/components/rxApp/docs/rxApp.midway.js, src/components/rxApp/scripts/rxApp.page.js, src/components/rxApp/templates/rxApp.html
JIRA: https://jira.rax.io/browse/FRMW-679
This is the least amount of work possible to keep everything working as is
while still blocking users from attempting to logout in the most obvious place
within encore apps, the left hand nav.
Anyone who is still supporting "logout" functionality will still be able to
"logout" users, even though it's not supported.
BREAKING CHANGE: Anyone who is checking the rxApp page objects for the userId
property will have their tests fail. This isn't a huge deal because part of the
update to the new version of the framework will make those tests irrelevant. Just
delete all tests exercising logout functionality and checking the currently logged
in user from your end to end test suite to successfully migrate to the newest
version of rx-page-objects.
=> fix(rxApp): Drop all user id display and logout display

src/atoms/rxCheckbox/scripts/rxCheckbox.exercise.js, src/components/rxBulkSelect/scripts/rxBulkSelect.exercise.js, src/components/rxCharacterCount/scripts/rxCharacterCount.exercise.js, src/components/rxCollapse/scripts/rxCollapse.exercise.js, src/components/rxForm/scripts/rxFieldName.exercise.js, src/components/rxMetadata/scripts/rxMetadata.exercise.js, src/components/rxMultiSelect/scripts/rxMultiSelect.exercise.js, src/components/rxOptionTable/scripts/rxOptionTable.exercise.js, src/components/rxPaginate/scripts/rxPaginate.exercise.js, src/components/rxRadio/scripts/rxRadio.exercise.js, src/components/rxSearchBox/scripts/rxSearchBox.exercise.js, src/components/rxSelect/scripts/rxSelect.exercise.js, src/components/rxToggleSwitch/scripts/rxToggleSwitch.exercise.js
JIRA: https://jira.rax.io/browse/FRMW-211
FRMW-211 #in-review
BREAKING CHANGE: You will need to refer to the component under test
using the `instance` option, which should be a page object that you
instantiate yourself, and hand into the exercise.
=> test(exerciese): Remove deprecated cssSelector option

src/components/rxToggleSwitch/docs/rxToggleSwitch.midway.js, src/components/rxToggleSwitch/scripts/rxToggleSwitch.exercise.js, src/components/rxToggleSwitch/scripts/rxToggleSwitch.page.js
JIRA: https://jira.rax.io/browse/FRMW-706
This takes the confusing `isEnabled`/`isDisabled` functions and renames them to the more
reasonable `isOn` and `isOff`, respectively. This replaces `isEnabled`/`isDisabled` with
checks on the toggle switch button to ensure that it is not currently "greyed out" (disabled).
FRMW-706 #in-review
=> test(rxToggleSwitch): Realign page object API to reduce confusion

src/components/rxApp/scripts/rxPage.page.js, src/components/rxSortableColumn/scripts/rxSortableColumn.page.js, src/utilities/rxNotify/scripts/rxNotify.page.js
JIRA: (NONE)
This PR fixes an unclear example in the `rxNotify` page object documentation.
=> docs(rxPageObjects): clarify rxNotify; fix memberof typo

src/components/rxCharacterCount/scripts/rxCharacterCount.js, src/components/rxCharacterCount/scripts/rxCharacterCount.spec.js
JIRA: https://jira.rax.io/browse/FRMW-452
In some situations, our cleanup code in rxCharacterCount was causing
a "maximum call stack size exceeded" error. I've moved some of the cleanup
code into a $timeout to solve this.
=> FRM-452 fix(rxCharacterCount): Solve max call stack

demo/templates/rx-example.html
JIRA: n/a
`.example` styles brought in from #1640 affected rxExample
=> fix(styles): rx-example using incorrect css class

bower.json, grunt-tasks/modules.js, src/components/rxCharacterCount/scripts/rxCharacterCount.js, src/components/rxModalAction/scripts/rxModalAction.js, src/components/rxModalAction/scripts/rxModalAction.spec.js, src/components/tooltips/tooltips.module.js, src/ngBootstrapOverrides.js
JIRA: n/a
This PR updates to ngBootstrap 0.14.3 (last version to support ng1.3). With it, many console warnings appeared, suggesting to modify usage to use the new `uib` prefixed directives and services.
Two actions were taken:
1. Dependencies were updated only where it would be seamless to our consumers (`$modal` -> `$uibModal`), leaving most implementations as is.
2. Suppressed deprecation warnings from ngBootstrap to prevent getting in the way of consumers' development workflow.
This will get us to the latest supported ngBootstrap functionality, while making it seamless to our consumers. This should buy us time to remove our dependency on ngBootstrap before we upgrade to ng1.4+ in Spring 2017 (estimated).
=> Upgrade to the latest ng1.3-compatible version of ngBootstrap

.travis.yml, utils/quitIfFork.js
JIRA: https://jira.rax.io/browse/FRMW-853
Half of this stuff is now located at https://codeship.com/projects/102410
This does not include getting rid of `grunt phantomjs-check:allModules`, which will happen after this PR lands.
=> test(ci): Move all selenium based work to codeship

src/components/rxApp/docs/rxApp.js
JIRA: n/a
The "Embedded rxApp" example at http://rackerlabs.github.io/encore-ui/#/components/rxApp does not work with Firefox (any version... at least between 22 and 48alpha), but it works in Chrome. Hard coding the `src` value on the iframe didn't help for an Angular-loaded template. The basic demo at http://output.jsbin.com/sihocux verified that static iframes work perfectly in all browsers. When I attempted to modify the `src` attribute to go to an Angular-redirect url, I noticed it worked again and discovered that adding a single forward slash to the original url fixed everything.
[insert facepalm here]
=> fix(rxApp): fix embedded demo for Firefox

src/elements/Metadata/docs/examples/metadata.simple.html
This example is at http://rackerlabs.github.io/encore-ui/#/elements/Metadata
It conflicts with http://rackerlabs.github.io/encore-ui/#/styles/formatting
which states
> _Dates in any context should be formatted this way: Mar 2, 2015 @ 15:40 (UTC-0600) — a three-letter capitalized month abbreviation (no period), followed by the day of the month (no leading zeroes), a comma, the four-digit year, an @ symbol, military time, and UTC in parentheses._
CC: @ErnieAtLYD 
JIRA: NONE
=> fix(metadataSimpleExample): consistentify date format with styleguide

utils/rx-page-objects/src/rxToggleSwitch.page.js
This PR is a quick improvement to the example documentation for `rxToggleSwitch`.
http://rackerlabs.github.io/encore-ui/rx-page-objects/rxToggleSwitch.html
Because `switch` is a reserved word in JavaScript,
`var switch = ...`
would be better as
`var mySwitch = ...` 
This caused an issue for @arc6789 this morning.
=> docs(rxToggleSwitch): rename 'var switch = ' in @example

utils/rx-page-objects/src/rxCharacterCount.exercise.js, utils/rx-page-objects/src/rxDatePicker.page.js, utils/rx-page-objects/src/rxFloatingHeader.page.js, utils/rx-page-objects/src/rxModalAction.page.js, utils/rx-page-objects/src/rxNotify.page.js, utils/rx-page-objects/src/rxSearchBox.exercise.js, utils/rx-page-objects/src/rxTags.page.js, utils/rx-page-objects/test/rxModalAction.midway.js
> _This PR fixes a couple of minor typos in the documentation for `rx-page-objects`_
=> docs(rx-page-objects): fix typos

utils/rx-page-objects/src/rxActionMenu.page.js, utils/rx-page-objects/test/rxActionMenu.midway.js
> This PR adds the `isPresent` method to check for the presence of the action cog/menu.
This resolves issue #1764 .
=> test(rxActionMenu): add isPresent method

src/utilities/rxAge/scripts/rxAge.js
JIRA: https://jira.rax.io/browse/FRMW-1000
With really small durations moment returns a small float
parseInt handles this weirdly returning 1 and sometimes 2
Changes implementation to use Math.floor
Issue: https://github.com/rackerlabs/encore-ui/issues/1767
=> fix(rxAge): Fixes parseInt bug

utils/rx-page-objects/package.json
JIRA: n/a
TypeScript 2.0.3 (patch-level release) introduced breaking changes. Locking to 2.0.2 until we have time to properly upgrade.
=> fix(rxPageObjects): lock to typescript 2.0.2

src/utilities/Environment/scripts/Environment.js, src/utilities/Environment/scripts/Environment.spec.js
When we launched the domain name `origin.encore.rackspace.com` we realized that the `Environment` service was not recognizing it as a production environment.
This update allows for it to match.
=> chore(Environment): Match origin as prod

src/components/rxApp/scripts/rxAccountUsers.js, src/components/rxApp/scripts/rxAccountUsers.spec.js
JIRA:
This fixes our usage of rxAccountUsers when oriLocationService
is available
=> fix(rxAccountUsers): Fix directive in Origin's nav

src/components/rxApp/scripts/rxAccountUsers.js, src/components/rxApp/scripts/rxAccountUsers.spec.js
JIRA:
This fixes our usage of rxAccountUsers when oriLocationService
is available
=> (3.x) fix(rxAccountUsers): Fix directive in Origin's nav

package.json, src/utilities/urlUtils/scripts/urlUtils.spec.js
JIRA: n/a
* update for macOS Sierra compatibility and unit test correctness
PhantomJS 1.x **will not run** on macOS Sierra.
=> [3.x] fix(phantomjs): upgrade to PhantomJS 2.x

components/switchDocs/switch-docs.html, components/switchDocs/switchDocs.js
JIRA: https://jira.rax.io/browse/FRMW-1220
* This PR adds the shared `<switch-docs>` directive to be used by the different versions of the docs.
* This PR does not add the automatic forwarding to the latest release documentation.
* This PR is expected to be merged into the `gh-pages` branch.
=> feat(switchDocs): add version switching directive

demo/index.html, demo/scripts/demoApp.js, grunt-tasks/options/copy.js, grunt-tasks/options/gh-pages.js, grunt-tasks/publish-docs.js, grunt-tasks/shipit.js, grunt-tasks/util/config.js, utils/rx-page-objects/protractor.chrome.conf.js
JIRA: https://jira.rax.io/browse/FRMW-1219
**This is not disrupting existing documentation at http://rackerlabs.github.io/encore-ui/.**
Generated 3.x docs served at http://rackerlabs.github.io/encore-ui/3.x/#/overview.
_NOTE:_ The version selection is not available yet in the navigation. This will come in the next PR.
With the local development server, the navigation will behave like this.
PR #1875 added the necessary logic for it to behave like this on production.
=> chore(ghPages): 3.x support for versioned docs

src/utilities/ErrorFormatter/docs/ErrorFormatter.meta.json, src/utilities/ErrorFormatter/docs/examples/ErrorFormatter.simple.js, src/utilities/rxErrorFormatter/docs/examples/rxErrorFormatter.simple.html, src/utilities/rxErrorFormatter/docs/examples/rxErrorFormatter.simple.js, src/utilities/rxErrorFormatter/docs/rxErrorFormatter.docs.html, src/utilities/rxErrorFormatter/docs/rxErrorFormatter.meta.json, src/utilities/rxErrorFormatter/scripts/rxErrorFormatter.js, src/utilities/rxErrorFormatter/scripts/rxErrorFormatter.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1149
* rename `Utilities > ErrorFormatter` to `Utilities > rxErrorFormatter`
* leave `ErrorFormatter` alias for backward compatibility (documented as deprecated)
| before | after |
| --- | --- |
| ![errorformatter-before](https://cloud.githubusercontent.com/assets/10750223/21061807/8af4436a-be13-11e6-8126-efe4046d6150.png)| ![rxerrorformatter-after](https://cloud.githubusercontent.com/assets/10750223/21061813/956659aa-be13-11e6-9b88-478d1b8e9b85.png)
| before | after |
| --- | --- |
| ![demo-error-before](https://cloud.githubusercontent.com/assets/10750223/21062025/8816bc08-be14-11e6-9f85-29aa3e988020.png) | ![demo-error-after](https://cloud.githubusercontent.com/assets/10750223/21062033/9373c956-be14-11e6-9066-fa45ca0c3dd3.png)
| page | before | …
=> refactor(rxErrorFormatter): rx-prefixes update to ErrorFormatter

.eslintrc.test.json, utils/rx-page-objects/protractor.chrome.conf.js, utils/rx-page-objects/protractor.conf.js, utils/rx-page-objects/src/rxCopy.exercise.js, utils/rx-page-objects/test/rxIfEnvironment.midway.js
JIRA: n/a
* Quality of life update to rxCopy midway so that it doesn't fail on Chrome on Mac.
* fix flaky midway failure with `rxIfEnvironment`
=> fix(midways): QoL and Flaky Test Fix

demo/index.html, demo/scripts/demoApp.js, demo/templates/modules/showModule.html, grunt-tasks/options/copy.js, grunt-tasks/options/gh-pages.js, grunt-tasks/publish-docs.js, grunt-tasks/shipit.js, grunt-tasks/util/config.js, src/components/rxForm/rxForm.module.js, src/components/rxModalAction/scripts/rxModalFooter.js, src/components/rxPaginate/rxPaginate.module.js, src/components/rxPermission/scripts/rxPermission.js, src/components/rxSearchBox/scripts/rxSearchBox.js, src/components/rxStatusColumn/scripts/rxStatusColumn.js, src/components/rxStatusColumn/scripts/rxStatusHeader.js, src/components/rxToggleSwitch/scripts/rxToggleSwitch.js, src/components/tooltips/tooltips.module.js, src/components/typeahead/typeahead.module.js, src/elements/Breadcrumbs/docs/examples/Breadcrumbs.simple.js, src/elements/Buttons/scripts/rxButton.js, src/utilities/rxNotify/scripts/rxNotify.js, utils/rx-page-objects/protractor.chrome.conf.js
JIRA: https://jira.rax.io/browse/FRMW-1222
Similar changes as #1874 
This is not disrupting existing documentation at http://rackerlabs.github.io/encore-ui/.
Generated 1.x docs served at http://rackerlabs.github.io/encore-ui/1.x/#/overview.
=> chore(ghPages): 1.x support for versioned docs

demo/index.html, demo/scripts/demoApp.js, demo/templates/modules/showModule.html, grunt-tasks/options/copy.js, grunt-tasks/options/gh-pages.js, grunt-tasks/publish-docs.js, grunt-tasks/shipit.js, grunt-tasks/util/config.js, src/elements/Breadcrumbs/docs/examples/Breadcrumbs.simple.js, src/elements/Buttons/scripts/rxButton.js, src/elements/Forms/scripts/rxSearchBox.js, src/elements/Forms/scripts/rxToggleSwitch.js, src/elements/Modals/scripts/rxModalFooter.js, src/elements/Tables/scripts/rxStatusColumn.js, src/elements/Tables/scripts/rxStatusHeader.js, src/elements/typeahead/scripts/typeahead.js, src/utilities/rxNotify/scripts/rxNotify.js, utils/rx-page-objects/protractor.chrome.conf.js
JIRA: https://jira.rax.io/browse/FRMW-1221
This is not disrupting existing documentation at http://rackerlabs.github.io/encore-ui/.
Generated 2.x docs served at http://rackerlabs.github.io/encore-ui/2.x/#/overview.
=> chore(ghPages): 2.x support for versioned docs

src/elements/AccountInfo/templates/rxAccountInfo.html, src/elements/AccountInfo/templates/rxAccountInfoBanner.html
JIRA: https://jira.rax.io/browse/FRMW-1269
Upgrading to ngBootstrap 0.14.3 for the 2.0.0 release broke account badge tooltips (ngBootstrap introduced a breaking change in their update). This PR fixes the AccountInfo template usage of ngBootstrap tooltips.
=> fix(AccountInfo): correct bug with badge tooltips [3.x]

src/elements/AccountInfo/templates/rxAccountInfo.html, src/elements/AccountInfo/templates/rxAccountInfoBanner.html, utils/rx-page-objects/test/rxIfEnvironment.midway.js
JIRA: https://jira.rax.io/browse/FRMW-1269
Upgrading to ngBootstrap 0.14.3 for the 2.0.0 release broke account badge tooltips (ngBootstrap introduced a breaking change in their update). This PR fixes the AccountInfo template usage of ngBootstrap tooltips.
=> fix(AccountInfo): correct bug with badge tooltips [2.x]

src/components/rxBulkSelect/scripts/rxBulkSelect.js, src/components/rxFloatingHeader/docs/rxFloatingHeader.html, src/components/rxFloatingHeader/scripts/rxFloatingHeader.js, src/components/rxFloatingHeader/scripts/rxFloatingHeader.spec.js, src/components/rxPaginate/scripts/rxPaginate.js, src/components/rxPaginate/templates/rxPaginate.html, src/utilities/rxBulkSelectController/scripts/rxBulkSelectController.js, src/utilities/rxBulkSelectController/scripts/rxBulkSelectController.spec.js
* Float original header rows
* Generate filler rows to reserve geometry (smoother float transition)
* Using rxPaginate, correct recalculation of column widths
when navigating to a different page of data.
* Correct phantom pixel when floating
* Clean up demo markup
* Also fixed a performance bug, too!
JIRA: https://jira.rax.io/browse/FRMW-1255
* dynamic elements added to header were not reserving the proper space (too little) which resulted in the data "jumping up" when it begins to float
* due to browser quirks, a phantom pixel shows up around the floating header (right side Chrome, left side Firefox)
* while floating, when the browser is resized, the floating header doesn't update
* the user has to scroll back up and refloat the headers to correct
* broken compatibility in the demo due …
=> fix(rxFloatingHeader): correct numerous rendering bugs [1.x]

demo/scripts/layout/page/layoutDataTableController.js, demo/templates/styles/layouts/data-table-page.html, utils/visual-regression/components/rxForm.midway.js, utils/visual-regression/styleguide/layouts.midway.js
Fix console error in `Styleguide > Layouts > Layout 2: Data Table` due to removing deprecated items. Additionally, fixing visual regression selectors (first corrected in #1971) to properly update visual regression images.
=> fix(demo): correct angular error in Layout 2 demo [4.x]

grunt-tasks/util/config.js
`master` will be branched to `3.x` for a long-running support branch of 3.6.x versions
=> chore(3x): prepare `master` for long-running 3.x branch [3.x]

components/switchDocs/switch-docs.html, components/switchDocs/switchDocs.js, index.html
Preparation for `gh-pages` branch for AFTER all of the releases.
=> chore(ghPages): prep for post-4.0 updates

src/elements/Forms/docs/examples/forms.intermediatecontrols.html, src/elements/Forms/docs/forms.docs.html, src/elements/Forms/scripts/rxInlineError.js, src/elements/Forms/styles/rxForm.less
JIRA: https://jira.rax.io/browse/FRMW-1334
(didn't exist)
=> frmw1334-inlinenotification

src/elements/Copy/docs/Copy.docs.html, src/elements/Copy/docs/examples/copy.tables.html, src/elements/Copy/styles/rxCopy.less
JIRA: https://jira.rax.io/browse/FRMW-1378
=> refactor(rxCopy): updated css styles for tables with rxCopy element

demo/templates/overview.html
Update link to point to 5.0 migration guide in Overview page.
=> docs(overview): link to 5.0 migration guide
