rackerlabs/encore-ui

- src/rxApp/rxApp.js
- src/rxApp/rxApp.spec.js
Allows hiding the nav if the account is of UK origin. Resolves https://jira.rax.io/browse/EOD-360 and will be used in encore-ui-nav
> feat(rxHideIfUkAccount): hides nav if UK account

- src/rxFloatingHeader/rxFloatingHeader.js
- src/rxFloatingHeader/rxFloatingHeader.spec.js
- src/rxForm/README.md
- src/rxForm/docs/rxForm.html
- src/rxForm/docs/rxForm.js
- src/rxForm/rxForm.js
- src/rxForm/rxForm.less
- src/rxForm/rxForm.spec.js
- src/rxForm/templates/rxFormItem.html
> feat(errorHandling): Show errors

- src/rxSortableColumn/docs/rxSortableColumn.midway.js
- src/rxSortableColumn/rxSortableColumn.spec.js
- src/rxSortableColumn/templates/rxSortableColumn.html
- src/rxStatusColumn/docs/rxStatusColumn.midway.js
Fixes reversed ascending and descending sort in rxColumnSort.
> fix(rxColumnSort): Fix reversed ascending and descending sort

- src/rxForm/rxForm.less
* remove errant CSS rule
Fixes #664
> fix(select): 664 - Fix new select styles for FF

- src/styles/vars.less
* increase field labels by 10px for slightly larger values
> fix(css): bump size of field labels

- src/rxActionMenu/rxActionMenu.less
* width should roughly match cog icon width
> fix(style): rxActionMenu width

- src/rxForm/docs/rxForm.midway.js
- src/rxForm/rxForm.page.js
> test(rxForm): currencyToPennies returns ints only

- demo/styleguide/buttons/links.html
- src/rxApp/rxApp.less
Closes #715
Note that once Cloud upgrades its framework version after this has been released, there is clean-up to be done. See https://github.com/rackerlabs/encore-ui/issues/715 for details.
> style(rxApp): add style for disabled links

- src/rxForm/rxForm.less
> fix(style): compressed checkbox Chrome malfunction

- src/rxApp/rxApp.js
- src/rxApp/rxApp.less
- src/rxApp/templates/rxBillingSearch.html
> feat(billing): Add support for Cloud Control API search in Billing nav

- src/rxApp/rxApp.less
* In regards to #782
* Fix `position: absolute;` attachment
> fix(css): rx-app-search icon

- src/rxPaginate/README.md
- src/rxPaginate/rxPaginate.js
- src/rxPaginate/rxPaginate.spec.js
> feat(rxPaginate): Persist items per page accross applications.

- demo/styleguide/buttons.html
- demo/styleguide/buttons/links.html
Closes https://github.com/rackerlabs/encore-ui/issues/787
> docs(buttons): improve docs for icons and action links

- src/rxActionMenu/docs/rxActionMenu.midway.js
- src/rxForm/rxForm.page.js
- src/rxModalAction/docs/rxModalAction.midway.js
> test(rxForm): Handle clicks in buggy situations

- demo/demo.js
- demo/styleguide/buttons.html
- demo/styleguide/buttons/custom-buttons.html
Kinda mis-titled this branch, so please ignore the branch name.
This PR adds documentation for different spinner usage in Encore with buttons and action links, and improves the demo for spinners and buttons.
Addresses some of https://github.com/rackerlabs/encore-ui/issues/790, but I'm going to create an additional issue for "documenting other spinners across Encore" as I know there are others that are non-standard that we need to look into.
Please focus on wording and whether what I wrote for documentation makes sense outside of my designer brain! :+1: :ice_cream:
> Add docs for spinners

- src/progressbar/README.md
- src/progressbar/docs/progressbar.html
- src/progressbar/docs/progressbar.js
- src/progressbar/progressbar.less
- src/rxFloatingHeader/docs/rxFloatingHeader.html
- src/rxFloatingHeader/docs/rxFloatingHeader.js
- src/rxFloatingHeader/rxFloatingHeader.js
- src/rxFloatingHeader/rxFloatingHeader.less
- src/rxFloatingHeader/rxFloatingHeader.spec.js
- src/rxForm/rxForm.less
- src/rxModalAction/rxModalAction.js
- src/rxModalAction/rxModalAction.less
- src/rxStatusColumn/rxStatusColumn.js
- src/rxStatusColumn/rxStatusColumn.spec.js
- wraith/configs/config.yaml
This implements the necessary changes to support https://github.com/rackerlabs/encore-cloud-ui/pull/465
Namely:
1. Modifies `rxFloatingHeader` to support the appearing/disappearing "message header row" 
2. Brings in `progressbar` from Angular Bootstrap.
3. Adds the ability do disable "press Escape to close" for `rxModalAction` 
4. Has `rxStatusColumn` explicitly watch for changes in status, and update accordingly
5. Modifies some padding values for `rxModalAction` and `rxForm`
> Bulk select support for Cloud

- src/rxFeedback/README.md
> docs(rxFeedback): document custom feedback function

- demo/demo.js
- src/rxEnvironment/README.md
- src/rxEnvironment/docs/rxEnvironment.html
> docs(rxEnvironment): Better documentation for rxEnvironment

- demo/demo.js
- demo/styleguide/forms.html
- demo/styleguide/forms/rx-form-item.html
- src/rxCharacterCount/README.md
- src/rxCharacterCount/docs/rxCharacterCount.html
- src/rxCharacterCount/docs/rxCharacterCount.js
- src/rxCharacterCount/docs/rxCharacterCount.midway.js
- src/rxCharacterCount/rxCharacterCount.exercise.js
- src/rxCharacterCount/rxCharacterCount.js
- src/rxCharacterCount/rxCharacterCount.less
- src/rxCharacterCount/rxCharacterCount.page.js
- src/rxCharacterCount/rxCharacterCount.spec.js
- src/rxForm/rxForm.less
- wraith/configs/config.yaml
> feat(rxCharacterCount): Add a character counter directive and styles

- src/rxButton/rxButton.less
> fix(rxButton): Disabled style takes precedence while hovered.

- grunt-tasks/component-template/rename.json
- grunt-tasks/component-template/root/component.exercise.js
- grunt-tasks/component-template/root/component.page.js
- src/rxCharacterCount/docs/rxCharacterCount.html
- src/rxCharacterCount/docs/rxCharacterCount.midway.js
- src/rxCharacterCount/rxCharacterCount.exercise.js
- src/rxCharacterCount/rxCharacterCount.page.js
- src/rxForm/rxForm.page.js
- src/rxPaginate/rxPaginate.exercise.js
@glynnis I was really happy to see that you wrote out end to end tests for your new component. Most devs don't do that :cry:.
However, there were some missing parts. I've gone ahead and addressed them one at a time, leaving a detailed commit messages overviewing each change so that you know what an ideal page object looks like.
I'll squash all these together once you get the gist of what's going on here, and you're good with merging it.
> E2e rx character count

- src/rxForm/docs/rxForm.midway.js
- src/rxForm/rxForm.page.js
> feat(rxPageObjects): Add accessor for a dropdown's values.

- src/rxSortableColumn/docs/rxSortableColumn.js
- src/rxSortableColumn/rxSortableColumn.js
- src/rxSortableColumn/rxSortableColumn.spec.js
> feat(rxSortUtil): No longer use 'name' as a default predicate.

- src/rxForm/README.md
- src/rxForm/docs/rxForm.html
- src/rxForm/docs/rxForm.js
- src/rxForm/docs/rxForm.midway.js
- src/rxForm/rxForm.js
- src/rxForm/rxForm.less
- src/rxForm/rxForm.page.js
- src/rxForm/rxForm.spec.js
- src/rxForm/templates/rxFormOptionTable.html
- src/styles/vars.less
Add ability to disable options in rx-form-table-options
> feat(rxForm): Disable options

- demo/styleguide/basics/wells.html
> docs(wells): Use modal in modal-well demo.

- src/rxAge/docs/rxAge.midway.js
- src/rxAge/rxAge.page.js
- src/rxCharacterCount/docs/rxCharacterCount.html
- src/rxCharacterCount/docs/rxCharacterCount.js
- src/rxCharacterCount/docs/rxCharacterCount.midway.js
- src/rxCharacterCount/rxCharacterCount.exercise.js
- src/rxCharacterCount/rxCharacterCount.js
- src/rxCharacterCount/rxCharacterCount.spec.js
The character count will reflect the characters remaining based on the model's initial value.
> feat(rxCharacterCount): account for initial model value

- src/rxApp/docs/rxApp.midway.js
- src/rxApp/rxApp.js
- src/rxApp/rxApp.page.js
- src/rxApp/rxApp.spec.js
- src/rxApp/templates/rxApp.html
> feat(rxApp): show user name next to logout link.

- demo/styleguide/buttons.html
- demo/styleguide/buttons/links.html
See https://jira.rax.io/browse/UXENCORE-214
Before:
After:
> docs(buttons): Add new Billing icons to buttons/links docs

- src/rxFloatingHeader/docs/rxFloatingHeader.html
This demo code for showing a message wasn't correct. A proper way
to do this will come into the framework when we move the bulk select
stuff in.
> fix(rxFloatingHeader): Remove bad example code

- src/rxNotify/rxNotify.less
> style(rxNotify): up contrast on dismiss buttons

- demo/demo.js
- demo/styleguide/basics.html
- demo/styleguide/basics/progressbars.html
- src/progressbar/docs/progressbar.html
- src/progressbar/progressbar.less
@ElementE and I did some style work to make progress bars a little more Encore-y in appearance. In updating CSS we realized that we also needed to add progress bars to the style guide. This PR does both.
> style(progressbar): update styles and docs/demo for progress bar

- src/rxButton/rxButton.less
Removed comments associated with Style Docco (no longer in use), re-ordered cascade so disabled styles can also apply to Cancel buttons.
Closes #862
> style(rxButton): reorder so disabled style works for cancel

- demo/styleguide/layout-1.html
> style(layout1): remove vertical rule

- README.md
Closes #235.
Collaborated/answered many of these with @parlarjb's help. :heart:
> Documenting process

- src/rxApp/rxApp.js
- src/rxApp/rxApp.spec.js
Fixes #515 
With this change, the nav is initially populated with a cached copy (if available).  If the request to the CDN succeeds, it will overwrite the cached version (both on the page and in the cache).  If the request fails, it will do so silently, and the cached version will be used.
> feat(rxApp): cache nav in local storage

- src/rxActionMenu/rxActionMenu.less
- src/rxApp/rxApp.less
- src/rxButton/rxButton.less
- src/rxForm/rxForm.less
- src/rxSpinner/rxSpinner.less
- src/styles/mixins.less
- src/tooltips/tooltips.less
* correct implmentation of .border-radius() mixin
* replaced `border-radius` with mixin version
> fix(styles): normalize .border-radius()

- demo/styleguide/forms/rx-form-item.html
- src/rxToggleSwitch/README.md
- src/rxToggleSwitch/docs/rxToggleSwitch.html
- src/rxToggleSwitch/docs/rxToggleSwitch.js
- src/rxToggleSwitch/docs/rxToggleSwitch.midway.js
- src/rxToggleSwitch/rxToggleSwitch.exercise.js
- src/rxToggleSwitch/rxToggleSwitch.js
- src/rxToggleSwitch/rxToggleSwitch.less
- src/rxToggleSwitch/rxToggleSwitch.page.js
- src/rxToggleSwitch/rxToggleSwitch.spec.js
- src/rxToggleSwitch/templates/rxToggleSwitch.html
- src/styles/mixins.less
- wraith/configs/config.yaml
> Add rx-toggle-switch to framework.

- demo/demo.js
- demo/styleguide/layout-2.html
- demo/styleguide/tables.html
- demo/styleguide/tables/with-filtering.html
- src/rxApp/common.less
- src/rxButton/rxButton.less
- src/rxFloatingHeader/README.md
- src/rxFloatingHeader/docs/rxFloatingHeader.html
- src/rxForm/rxForm.less
- src/rxSearchBox/README.md
- src/rxSearchBox/docs/rxSearchBox.html
- src/rxSearchBox/docs/rxSearchBox.js
- src/rxSearchBox/docs/rxSearchBox.midway.js
- src/rxSearchBox/rxSearchBox.exercise.js
- src/rxSearchBox/rxSearchBox.js
- src/rxSearchBox/rxSearchBox.less
- src/rxSearchBox/rxSearchBox.page.js
- src/rxSearchBox/rxSearchBox.spec.js
- src/rxSearchBox/templates/rxSearchBox.html
- src/styles/mixins.less
- src/styles/vars.less
- wraith/configs/config.yaml
Closes #844
**Defaults / Empty Search Boxes**
**Search Boxes with Values**
> Add rxSearchBox

- demo/styleguide/buttons.html
- demo/styleguide/buttons/custom-buttons.html
- src/rxButton/rxButton.less
- src/rxModalAction/docs/rxModalAction.html
- src/rxModalAction/templates/rxModalFooters.html
Relates to https://jira.rax.io/browse/UXENCORE-231 and https://jira.rax.io/browse/EOD-273 -- new button style for "finish & close" with multi-screen modals.
> style(rxButton): Add styles for finish & close button

- src/rxMisc/README.md
- src/rxMisc/docs/rxMisc.html
- src/rxMisc/docs/rxMisc.js
- src/rxMisc/docs/rxMisc.midway.js
- src/rxMisc/rxMisc.js
- src/rxMisc/rxMisc.spec.js
- src/rxPaginate/docs/rxPaginate.midway.js
Closes #679
This provides a way to have form data automatically saved to and
loaded from LocalStorage. This is to improve the user experience
if they're typing in a form and accidentally navigate away.
> feat(rxMisc): Added rxAutoSave service

- demo/demo.js
- src/rxStatusColumn/README.md
- src/rxStatusColumn/docs/rxStatusColumn.js
- src/rxStatusColumn/docs/rxStatusColumn.midway.js
- src/rxStatusColumn/rxStatusColumn.js
- src/rxStatusColumn/rxStatusColumn.less
- src/rxStatusColumn/rxStatusColumn.page.js
- src/rxStatusColumn/rxStatusColumn.spec.js
> feat(rxStatusColumn): add disabled status

- README.md
> docs(readme): Fix misspelling

- src/rxForm/docs/rxForm.midway.js
- src/rxForm/rxForm.page.js
- utils/rx-page-objects/README.md
Closes #904
BREAKING CHANGE: `rxForm.form.fill` is now `rxForm.fill`
> test(rxForm): Simple generation of form elements

- demo/demo.js
- demo/styleguide/basics.html
- demo/styleguide/basics/collapsible.html
- demo/styleguide/tables.html
- demo/styleguide/tables/collapsible-filtering.html
- src/rxCollapse/README.md
- src/rxCollapse/docs/rxCollapse.html
- src/rxCollapse/docs/rxCollapse.midway.js
- src/rxCollapse/rxCollapse.exercise.js
- src/rxCollapse/rxCollapse.js
- src/rxCollapse/rxCollapse.less
- src/rxCollapse/rxCollapse.page.js
- src/rxCollapse/rxCollapse.spec.js
- src/rxCollapse/templates/rxCollapse.html
- src/styles/vars.less
- wraith/configs/config.yaml
> feat(rxCollapse): Add collapsible component

- demo/styleguide/forms.html
- demo/styleguide/forms/manual-saving.html
- src/rxNotify/rxNotify.less
> Document design pattern for manual saving

- CONTRIBUTING.md
Update rebase instructions to account for merge conflicts
> fix(contributing): update rebase instructions

- demo/demo.js
- demo/index.html
- demo/styleguide/basics.html
- grunt-tasks/build.js
- grunt-tasks/options/concat.js
- grunt-tasks/options/cssmin.js
- grunt-tasks/options/less.js
- grunt-tasks/util/config.js
- src/grid/README.md
- src/layout/README.md
- src/layout/docs/responsiveLayout.html
- src/layout/docs/responsiveLayout.js
- src/layout/layout.less
- src/layout/responsive.less
- src/layout/responsiveLayout.less
- src/styles/flexbox.less
- src/styles/vars.less
- wraith/configs/config.yaml
Incorporate the layouts module from the Angular Material framework (https://material.angularjs.org/#/layout/container).
https://jira.rax.io/browse/EOD-671
> feat(ResponsiveLayout): add responsive layout module and docs

- src/rxMisc/README.md
- src/rxMisc/rxMisc.js
- src/rxMisc/rxMisc.spec.js
- src/rxPaginate/README.md
- src/rxPaginate/docs/rxPaginate.html
- src/rxPaginate/docs/rxPaginate.js
- src/rxPaginate/docs/rxPaginate.midway.js
- src/rxPaginate/rxPaginate.js
- src/rxPaginate/rxPaginate.spec.js
- src/rxSelectFilter/README.md
- src/rxSelectFilter/docs/rxSelectFilter.html
- src/rxSelectFilter/docs/rxSelectFilter.js
- src/rxSelectFilter/docs/rxSelectFilter.midway.js
- src/rxSelectFilter/rxSelectFilter.exercise.js
- src/rxSelectFilter/rxSelectFilter.js
- src/rxSelectFilter/rxSelectFilter.less
- src/rxSelectFilter/rxSelectFilter.page.js
- src/rxSelectFilter/rxSelectFilter.spec.js
- src/rxSelectFilter/templates/rxMultiSelect.html
- src/rxSelectFilter/templates/rxSelectFilter.html
- src/rxSelectFilter/templates/rxSelectOption.html
- wraith/configs/config.yaml
> feat(rxSelectFilter): Add table filtering component

- src/layout/docs/responsiveLayout.html
- src/layout/responsiveLayout.less
Remove code styles until they can get proper design attention.
https://github.com/rackerlabs/encore-ui/issues/940
> fix(styles): remove code block style

- demo/assets/demo.less
- demo/assets/generated_demo.css
- demo/demo.js
- src/rxRadio/README.md
- src/rxRadio/docs/rxRadio.html
- src/rxRadio/docs/rxRadio.js
- src/rxRadio/docs/rxRadio.midway.js
- src/rxRadio/rxRadio.exercise.js
- src/rxRadio/rxRadio.js
- src/rxRadio/rxRadio.less
- src/rxRadio/rxRadio.page.js
- src/styles/vars.less
- wraith/configs/config.yaml
Per necessity of #884, this directive can stand alone for use elsewhere
in the framework.
> feat(rxRadio): add rxRadio component

- src/rxCheckbox/README.md
- src/rxCheckbox/docs/rxCheckbox.html
- src/rxCheckbox/docs/rxCheckbox.js
- src/rxCheckbox/docs/rxCheckbox.midway.js
- src/rxCheckbox/rxCheckbox.exercise.js
- src/rxCheckbox/rxCheckbox.js
- src/rxCheckbox/rxCheckbox.less
- src/rxCheckbox/rxCheckbox.page.js
- src/styles/vars.less
- wraith/configs/config.yaml
Per necessity of #884, this directive can stand alone for use elsewhere in the framework.
> feat(rxCheckbox): add rxCheckbox component

- src/configs/configs.js
- src/rxFeedback/README.md
- src/rxFeedback/rxFeedback.js
- src/rxFeedback/rxFeedback.spec.js
Updates API endpoint to `/api/encore/feedback`.  User feedback now includes sso, current page and browser agent.
> feat(rxFeedback): Update API endpoint and add fields to feeback

- demo/styleguide/buttons/links.html
> docs(styleguide): Add clone icon

- grunt-tasks/options/coveralls.js
> chore(coveralls): fix deprecation warning

- bower.json
> chore(bower): upgrade to font-awesome 4.3

- src/typeahead/README.md
- src/typeahead/docs/typeahead.html
- src/typeahead/docs/typeahead.midway.js
- src/typeahead/typeahead.js
- src/typeahead/typeahead.less
- src/typeahead/typeahead.page.js
- src/typeahead/typeahead.spec.js
> feat(typeahead): show options when focused

- src/rxForm/rxForm.js
- src/rxForm/rxForm.spec.js
Chrome recently started failing on some of our tests (see attached
issue for more details). This fixes those errors.
Closes #991
> fix(rxForm): Various fixes for Chrome

- package.json
- src/rxFloatingHeader/rxFloatingHeader.page.js
This is part of #951, but it should be mergeable on its own.
> chore(protractor): Upgrade to protractor 2.0

- demo/styleguide/layouts.html
> docs(styleguide): add deprecation warning and index to pure grids

- demo/demo.js
- demo/styleguide/basics.html
> docs(styleguide): Add documentation for date formatting

- src/rxFieldName/README.md
- src/rxFieldName/docs/rxFieldName.html
- src/rxFieldName/docs/rxFieldName.js
- src/rxFieldName/docs/rxFieldName.midway.js
- src/rxFieldName/rxFieldName.exercise.js
- src/rxFieldName/rxFieldName.js
- src/rxFieldName/rxFieldName.less
- src/rxFieldName/rxFieldName.page.js
- src/rxFieldName/templates/rxFieldName.html
- src/styles/vars.less
> feat(rxFieldName): add rxFieldName component

- src/rxForm/rxForm.js
> fix(rxFormOptionTable): use link instead of controller

- src/layout/responsive.less
https://github.com/rackerlabs/encore-ui/issues/1016
> fix(Layout): remove redundant import

- demo/demo.js
- demo/styleguide/basics.html
> docs(styleguide): Document format for empty or null values

- CONTRIBUTING.md
@glynnis @chriscantu feel free to simply push over these commits on my fork with anything that you need to see here.
> docs(contributing): Visual review standards

- .travis.yml
- guides/testing.md
- protractor.conf.js
- protractor.visual.regression.conf.js
- utils/visual-regression/components/metadata.midway.js
- utils/visual-regression/test.sh
@parlarjb just checking if my recent changes to the .travis.yml file broke legit visual regression tests.
> test(metadata): Visual regression

- src/rxTokenInterceptor/rxTokenInterceptor.js
- src/rxTokenInterceptor/rxTokenInterceptor.spec.js
On behalf of @parlarjb:
Closes #1009
> fix(rxTokenInterceptor): Only look at hostname for token exclusion

- CONTRIBUTING.md
Based on discussions with a few people, we're trying to make more explicit our contribution process. Most of this will be obvious to people already contributing, as it's just writing down our current structure, but we've also added a few points to try to make lives easier on our designers.
> docs(CONTRIBUTING): Be more explicit about contributions

- README.md
- demo/styleguide/basics.html
- grunt-tasks/options/bump.js
- grunt-tasks/options/replace.js
- guides/using-encoreui.md
Miscellaneous changes for JIRA task [FRMW-22](https://jira.rax.io/browse/FRMW-22)
> docs(GettingStarted): Updates for FRMW-22

- README.md
- guides/js-styleguide.md
Changes for https://jira.rax.io/browse/FRMW-19
> docs(JSStylguide): Misc changes (FRMW-19)

- README.md
- guides/ui-setup.md
Addresses https://jira.rax.io/browse/FRMW-15
> docs(uisetup): FRWM-15-update-ui-setup

- README.md
- guides/testing.md
Updated docs for https://jira.rax.io/browse/FRMW-18
> docs(testing): Misc changes for FRMW-18

- demo/demo.js
- guides/testing.md
* Link to Yeoman Generator
* Fix broken link in testing guide
> docs(demo): update link to app generator in demo nav

- src/rxStatus/README.md
- src/rxStatus/docs/rxStatus.html
https://jira.rax.io/browse/FRMW-44
Fixes #1061
> docs(rxStatus): Fix button styles

- src/rxApp/rxApp.js
- src/rxApp/rxApp.spec.js
https://jira.rax.io/browse/FRMW-28
> fix(rxAccountUsers): check account number before making API call

- CONTRIBUTING.md
- guides/css-styleguide.md
- guides/js-styleguide.md
- guides/testing.md
- guides/ui-setup.md
- guides/versioning.md
This is a practice exercise in making a PR.
> docs(Onboarding): fix typos

- README.md
https://jira.rax.io/browse/FRMW-57
> docs(README): Remove 'Getting your tool in Encore'

- README.md
- guides/common-questions.md
https://jira.rax.io/browse/FRMW-14
> docs(CommonQuestions): Move "Common Questions" to its own document

- grunt-tasks/options/karma.js
- src/rxCollapse/README.md
- src/rxCollapse/docs/rxCollapse.html
- src/rxCollapse/docs/rxCollapse.midway.js
- src/rxCollapse/rxCollapse.exercise.js
- src/rxCollapse/rxCollapse.js
- src/rxCollapse/rxCollapse.less
- src/rxCollapse/rxCollapse.page.js
- src/rxCollapse/rxCollapse.spec.js
- src/rxCollapse/templates/rxCollapse.html
This is an add on to rxCollapse for story linked here: https://jira.rax.io/browse/EOD-614
> rxCollapse second version "See More / Less"

- demo/demo.js
Provide redirect for legacy component routes
Closes #1101
> fix(demo): add redirect for legacy component routes

- src/rxPaginate/README.md
- src/rxPaginate/rxPaginate.js
- src/rxPaginate/rxPaginate.spec.js
- src/rxPaginate/templates/rxPaginate.html
> feat(rxPaginate): Add ability to disable itemsPerPage persistence

- src/rxActionMenu/rxActionMenu.page.js
- src/rxModalAction/rxModalAction.page.js
This also include rxModalAction, since action menus use them so much. They're all linked up together all nice and everything.
> E2e docs rx action menu

- src/rxMisc/docs/rxMisc.html
- src/rxMisc/docs/rxMisc.midway.js
- src/rxMisc/rxMisc.page.js
I'm tired of copying this function from various `util` directories between projects.
I also did a touch of refactoring in the rxMisc midway tests.
> E2e rx misc unless

- demo/styleguide/layout-3.html
- utils/visual-regression/clone.sh
- utils/visual-regression/components/metadata.midway.js
- utils/visual-regression/components/rxBreadcrumbs.midway.js
- utils/visual-regression/components/rxSpinner.midway.js
- utils/visual-regression/styleguide/layouts.midway.js
Please make sure screenshots show up and that they all look Ok.
This gets around some issues with node-canvas that happened today. Hopefully nobody notices anything because it all just works.
> chore(visualRegression): Bump to latest

- bower.json
> chore(bower): upgrade font awesome to 4.4.0

- demo/assets/demo.less
- demo/assets/generated_demo.css
- src/metadata/README.md
- src/rxMetadata/README.md
- src/rxMetadata/docs/rxMetadata.html
- src/rxMetadata/docs/rxMetadata.js
- src/rxMetadata/docs/rxMetadata.midway.js
- src/rxMetadata/rxMetadata.exercise.js
- src/rxMetadata/rxMetadata.js
- src/rxMetadata/rxMetadata.less
- src/rxMetadata/rxMetadata.page.js
- src/rxMetadata/templates/rxMeta.html
- src/rxMisc/docs/rxMisc.midway.js
- src/rxMisc/rxMisc.page.js
- src/styles/vars.less
* rxMetadata parent element directive
* rxMeta child element directive
* best if used as `rxMetadata > section > rxMeta`
Closes #885 
Closes #939 
JIRA: https://jira.rackspace.com/browse/FRMW-31
> feat(rxMetadata): add rxMetadata component

- guides/css-styleguide.md
JIRA: https://jira.rackspace.com/browse/FRMW-20
Closes #1079
> docs(CSS): Update CSS Styleguide

- src/rxMisc/rxMisc.page.js
Per post-merge [comment](https://github.com/rackerlabs/encore-ui/pull/1107/files#r36010268)
[ci skip] [skip ci]
> docs(rxMisc): mark param as optional [skip ci]

- CONTRIBUTING.md
JIRA: https://jira.rax.io/browse/FRMW-16
> docs(CONTRIBUTING): Update Contribution Guide

- src/rxMetadata/docs/rxMetadata.html
> style(rxMetadata): Add data and link example to demo

- demo/demo.js
- demo/styleguide/forms.html
- demo/styleguide/forms/manual-saving.html
- protractor.visual.regression.conf.js
- src/rxButton/rxButton.less
- src/rxNotify/rxNotify.page.js
- utils/visual-regression/styleguide/forms.midway.js
- utils/visual-regression/styleguide/layouts.midway.js
[Invision](https://projects.invisionapp.com/d/main#/console/3750442/81735376/preview)
The manual save pattern was redone awhile back, but I didn't get around to updating the docs until now (sorry :smile: ).  Fixes #907
> docs(forms): Fix design pattern for manual saving.

- .gitignore
- CONTRIBUTING.md
- demo/assets/demo.less
- demo/assets/generated_demo.css
- demo/demo.js
- demo/guides/guideController.js
- demo/guides/guideViewer.html
- demo/index.html
- demo/overview.html
- demo/styleguide/basics.html
- demo/styleguide/buttons.html
- demo/styleguide/forms.html
- demo/styleguide/layouts.html
- grunt-tasks/build.js
- grunt-tasks/options/copy.js
- guides/testing.md
- src/rxApp/README.md
- src/rxBreadcrumbs/README.md
- src/rxForm/README.md
- src/rxStatus/README.md
https://jira.rax.io/browse/FRMW-27
https://jira.rax.io/browse/FRMW-24
https://jira.rax.io/browse/FRMW-47
> docs(overview): implement newly organzied overview page

- demo/styleguide/basics.html
- demo/styleguide/basics/metadata.html
- demo/styleguide/layout-1.html
- demo/styleguide/layouts.html
- demo/styleguide/tables.html
- demo/styleguide/tables/nested-metadata.html
Submitting per [this request](https://github.com/rackerlabs/encore-ui/pull/1124#issuecomment-130056175) for visual regression updates.
> docs(styleguide): update rxMetadata usage

- src/rxForm/docs/rxForm.midway.js
- src/rxSelect/docs/rxSelect.midway.js
- src/rxSelect/rxSelect.page.js
> test(rxSelect): Allow for optional `slowClick`

- guides/versioning.md
Per @parlar's recommendation (and #1131).
> docs(VERSIONING): update with secret recipe

- guides/versioning.md
> docs(VERSIONING): update for patch release [skip ci]

- grunt-tasks/squirrel.js
This will need some manual testing since I think lodash needs to be more up to date to get this to use https://lodash.com/docs#repeat
> refact(grunt): Responsive shipit squirrel

- src/rxMetadata/README.md
- src/rxMetadata/docs/rxMetadata.html
- src/rxMetadata/docs/rxMetadata.midway.js
- src/rxMetadata/rxMetadata.less
JIRA: https://jira.rax.io/browse/FRMW-104
> fix(rxMetadata): provide correction to unbreakable data values

- demo/styleguide/basics/metadata.html
- src/rxMetadata/docs/rxMetadata.html
- src/rxMisc/docs/rxMisc.midway.js
- src/rxMisc/rxMisc.page.js
Replaces https://github.com/rackerlabs/encore-ui/pull/1144 so that visual regression is run.
> test(rxMisc): Quickly convert text to dates

- utils/visual-regression/components/rxApp.midway.js
Adding visual regression for standard and custom app definitions of `rxApp`.
> chore(rxApp): add visual regression

- src/rxModalAction/README.md
- src/rxModalAction/docs/rxModalAction.html
- src/rxModalAction/docs/rxModalAction.js
- src/rxModalAction/docs/rxModalAction.midway.js
- src/rxModalAction/rxModalAction.js
- src/rxModalAction/rxModalAction.spec.js
JIRA: https://jira.rax.io/browse/FRMW-59
> feat(rxModalAction): add dismiss-hook support

- demo/demo.js
- demo/overview.html
- src/rxApp/rxApp.less
JIRA: https://jira.rax.io/browse/FRMW-109
> docs(Overview): move 'Other Links' to Overview

- src/rxApp/rxApp.js
- src/rxApp/rxApp.spec.js
> fix(rxAccountUsers): Fix ever increasing user calls

- .jshintrc
- grunt-tasks/component-template/root/component.exercise.js
- src/rxBulkSelect/rxBulkSelect.exercise.js
- src/rxCharacterCount/docs/rxCharacterCount.midway.js
- src/rxCharacterCount/rxCharacterCount.exercise.js
- src/rxCheckbox/docs/rxCheckbox.midway.js
- src/rxCheckbox/rxCheckbox.exercise.js
- src/rxCollapse/docs/rxCollapse.midway.js
- src/rxCollapse/rxCollapse.exercise.js
- src/rxForm/docs/rxForm.midway.js
- src/rxForm/rxFieldName.exercise.js
- src/rxOptionTable/docs/rxOptionTable.midway.js
- src/rxOptionTable/rxOptionTable.exercise.js
- src/rxPaginate/docs/rxPaginate.js
- src/rxPaginate/docs/rxPaginate.midway.js
- src/rxPaginate/rxPaginate.exercise.js
- src/rxRadio/docs/rxRadio.midway.js
- src/rxRadio/rxRadio.exercise.js
- src/rxSearchBox/docs/rxSearchBox.midway.js
- src/rxSearchBox/rxSearchBox.exercise.js
- src/rxSelect/docs/rxSelect.midway.js
- src/rxSelect/rxSelect.exercise.js
- src/rxSelectFilter/docs/rxSelectFilter.midway.js
- src/rxSelectFilter/rxSelectFilter.exercise.js
- src/rxToggleSwitch/docs/rxToggleSwitch.midway.js
- src/rxToggleSwitch/rxToggleSwitch.exercise.js
- utils/rx-page-objects/README.md
> Instances in exercises

- src/rxCollapse/rxCollapse.exercise.js
- src/rxCollapse/rxCollapse.page.js
I really want to put this on top of #1122.
> test(rxCollapse): Support for expand/collapse

- demo/styles/color.html
> fix(typo): colours

- src/rxBulkSelect/README.md
- src/rxBulkSelect/docs/rxBulkSelect.html
- src/rxBulkSelect/docs/rxBulkSelect.js
- src/rxBulkSelect/docs/rxBulkSelect.midway.js
- src/rxBulkSelect/rxBulkSelect.js
- src/rxBulkSelect/rxBulkSelect.spec.js
Adds a directive for validating rxBulkSelect in a form.
[JIRA Issue](https://jira.rax.io/browse/FRMW-88)
> feat(rxBulkSelectValidate): Validate rxBulkSelect in a form

- demo/index.html
- src/rxAccountInfo/docs/rxAccountInfo.js
- src/rxAccountInfo/docs/rxAccountInfo.midway.js
- src/rxAccountInfo/rxAccountInfo.js
- src/rxAccountInfo/rxAccountInfo.page.js
- src/rxAccountInfo/rxAccountInfo.spec.js
- src/rxAccountInfo/templates/rxAccountInfoBanner.html
JIRA: https://jira.rax.io/browse/FRMW-135
Depends on: https://github.com/rackerlabs/encore-ui-api-js/pull/60
Screenshot:
> feat(accessPolicy): Add Account Access Policy to rxAccountInfo

- src/rxMetadata/rxMetadata.less
JIRA: https://jira.rax.io/browse/FRMW-132
Corrected top/bottom margin as well as simplified gutters.
> style(rxMetadata): correct margins

- src/rxForm/rxForm.less
> fix(rxForm): add top/bottom margins

- demo/demo.js
- demo/layout/collapsible.html
- demo/layout/collapsible/box.html
- demo/layout/collapsible/see-more-see-less.html
- demo/styleguide/layouts/collapsible.html
JIRA: https://jira.rax.io/browse/FRMW-50
Screenshot:
> feat(docs): FRMWK-50 - Add Collapsible Layout page

- src/rxNotify/README.md
- src/rxNotify/docs/rxNotify.html
- src/rxNotify/docs/rxNotify.js
- src/rxNotify/rxNotify.js
- src/rxNotify/rxNotify.spec.js
- src/rxNotify/templates/rxNotifications.html
JIRA:
* [FRMW-32](https://jira.rax.io/browse/FRMW-32): Make all notifications dismiss-able
* [FRMW-113](https://jira.rax.io/browse/FRMW-113): Tech Debt: rxNotify - Move API documentation to API docs
> refactor(rxNotify): remove ability to prevent stack notification dismissal

- src/rxLocalStorage/docs/rxLocalStorage.midway.js
- src/rxLocalStorage/rxLocalStorage.page.js
Added a rxLocalStorage page object with basic functionality to be used by tests in other projects. This saves us from having to write driver.executeScript() all over the place.
> test(rxLocalStorage): Add a page object for rxLocalStorage

- src/rxTags/README.md
- src/rxTags/docs/rxTags.html
- src/rxTags/docs/rxTags.js
- src/rxTags/docs/rxTags.midway.js
- src/rxTags/rxTags.exercise.js
- src/rxTags/rxTags.js
- src/rxTags/rxTags.less
- src/rxTags/rxTags.page.js
- src/rxTags/rxTags.spec.js
- src/rxTags/templates/rxTags.html
- src/styles/vars.less
Fixes #918 
@glynnis This does not include the feature to show the list on click.  I started down that path, and it's a bit complex.  I am also going to be out next week, so someone else can have a go or I will look at it again down the road.
> feat(rxTags): Add rxTags component.

- demo/styles/color.html
> fix(typo): @light-green hex

- src/layout/layout.less
- src/rxApp/rxApp.less
- src/rxForm/rxForm.less
- src/rxOptionTable/rxOptionTable.less
- src/rxPaginate/rxPaginate.less
- src/rxRadio/rxRadio.less
- src/rxSearchBox/rxSearchBox.less
- src/rxSelect/rxSelect.less
- src/styles/flexbox.less
- src/styles/mixins.less
- src/tabs/tabs.less
JIRA: https://jira.rax.io/browse/FRMW-83
* ~~Removed~~ Added deprecation warning to top of `flexbox.less`
* Updated mixins to not depend on `flexbox.less`
* Re-ident modified files (commit: https://github.com/rackerlabs/encore-ui/commit/95f49b0a0364c14f983242920cba6699f2ed2a94)
Forms:
Tabs
rxSelect
Layout
> FRMW-83: Update Flexbox Mixins

- src/rxSearchBox/README.md
- src/rxSearchBox/rxSearchBox.js
JIRA: https://jira.rax.io/browse/FRMW-111
* Create JS Docs for component and directive
* Removed Options table
> docs(rxSearchBox): FRMW-111 - Create rxSearchBox API Docs

- src/layout/layout.less
- src/layout/responsive.less
- src/layout/responsiveLayout.less
- src/metadata/metadata.less
- src/rxApp/common.less
- src/rxApp/rxApp.less
- src/rxButton/rxButton.less
- src/rxCharacterCount/rxCharacterCount.less
- src/rxCheckbox/rxCheckbox.less
- src/rxCollapse/rxCollapse.less
- src/rxFloatingHeader/rxFloatingHeader.less
- src/rxForm/rxForm.less
- src/rxMetadata/rxMetadata.less
- src/rxNotify/rxNotify.less
- src/rxOptionTable/rxOptionTable.less
- src/rxPaginate/rxPaginate.less
- src/rxRadio/rxRadio.less
- src/rxSearchBox/rxSearchBox.less
- src/rxSelect/rxSelect.less
- src/rxTags/rxTags.less
- src/styles/flexbox.less
- src/styles/mixins.less
Standardize LESS Indentation to 4 spaces per tab: https://jira.rax.io/browse/FRMW-98
> style(less): FRMW-98-Standardize LESS Indentation

- src/configs/README.md
- src/configs/configs.js
JIRA: https://jira.rax.io/browse/FRMW-150
> feat(docs): FRMW-150 - Migrate configs API Docs in README to ngdocs

- src/hotkeys/README.md
- src/hotkeys/hotkeys.js
JIRA: https://jira.rax.io/browse/FRMW-152
> feat(docs): FRMW-151 - Migrate hotkey s API Docs in README to ngdocs

- src/rxAccountInfo/README.md
- src/rxAccountInfo/rxAccountInfo.js
JIRA: https://jira.rax.io/browse/FRMW-156
> feat(docs): FRMW-156 - Migrate rxAccountInfo docs in README to ngdocs

- src/layout/README.md
- src/layout/layout.js
JIRA: https://jira.rax.io/browse/FRMW-153
> feat(docs): FRMW-153 - Migrate layout API Docs in README to ngdocs

- src/rxActionMenu/README.md
- src/rxActionMenu/rxActionMenu.js
JIRA: https://jira.rax.io/browse/FRMW-157
> feat(docs): FRMW-153 - Migrate rxActionMenu docs in README to ngdocs

- demo/demo.js
- demo/styleguide/forms.html
- src/rxApp/common.less
- src/rxCheckbox/rxCheckbox.less
- src/rxForm/rxForm.less
- src/rxRadio/rxRadio.less
- src/rxSelect/rxSelect.less
JIRA
* https://jira.rax.io/browse/FRMW-147
* https://jira.rax.io/browse/FRMW-145
LGTMS
~~*may or may not pass midway tests. we'll see*~~
> chore(CSS): red border on invalid and dirty

- src/rxBreadcrumbs/docs/rxBreadcrumbs.midway.js
- src/rxBreadcrumbs/rxBreadcrumbs.page.js
https://github.com/rackerlabs/encore-ui/issues/1209
> chore(rxBreadcrumbs): Make rxBreadcrumbs.byName return a page object

- demo/demo.js
- demo/styleguide/basics.html
- demo/styles/typography.html
- demo/styles/typography/headings.html
- demo/styles/typography/lists.html
- demo/styles/typography/metadata.html
JIRA: https://jira.rax.io/browse/FRMW-39
* Removed elements from basics page
* New Style page: Typography
Screenshot:
> feat(docs): Create Typography style page

- src/rxActiveUrl/rxActiveUrl.js
JIRA: https://jira.rax.io/browse/FRMW-158
> feat(docs): FRMW-158 - Migrate rxActiveUrl docs in README to ngdocs

- src/rxAge/README.md
- src/rxAge/rxAge.js
Encore Framework Sprint 2: https://jira.rax.io/browse/FRMW-159
Migrate rxAge to API documentation.
> feat(docs): FRMW-159-Migrate rxAge to API Docs

- src/rxAppRoutes/README.md
- src/rxAppRoutes/rxAppRoutes.js
JIRA: https://jira.rax.io/browse/FRMW-161
> feat(docs): FRMW-161 - Update rxAppRoutes API docs and README

- demo/styleguide/basics.html
PR for :ant: :ant: :ant: 
https://jira.rax.io/browse/FRMW-224
> fix(basics): Correct typo

- src/rxBreadcrumbs/README.md
- src/rxBreadcrumbs/rxBreadcrumbs.js
JIRA: https://jira.rax.io/browse/FRMW-164
Migrate `rxBreadcrumbs` to API Documentation.
> docs(rxBreadcrumbs): FRMW-164-Migrate rxBreadcrumbs to API Docs

- src/rxCapitalize/rxCapitalize.js
JIRA: https://jira.rax.io/browse/FRMW-167
> docs(rxCapitalize): FRMW-167 Migrate rxCapitalize

- src/rxAttributes/README.md
- src/rxAttributes/rxAttributes.js
JIRA: https://jira.rax.io/browse/FRMW-162
> feat(docs): FRMW-162 - Migrate rxAttributes docs to ngdocs

- src/rxBulkSelect/README.md
- src/rxBulkSelect/rxBulkSelect.js
JIRA: https://jira.rax.io/browse/FRMW-168
> feat(docs): FRMW-165 - Migrate rxBulkSelect docs to ngdocs

- src/rxCheckbox/README.md
- src/rxCheckbox/rxCheckbox.js
JIRA: https://jira.rax.io/browse/FRMW-169
> feat(docs): FRMW-169 - Migrate rxCheckbox docs to ngdocs

- src/rxButton/README.md
- src/rxButton/rxButton.js
JIRA: https://jira.rax.io/browse/FRMW-166
Migrate `rxButton` to API documentation
> docs(rxButton): FRMW-166-Migrate rxButton to API docs.

- src/rxDiskSize/README.md
- src/rxDiskSize/rxDiskSize.js
JIRA: https://jira.rax.io/browse/FRMW-172
Migrate rxDiskSize to API documentation.
> docs(rxDiskSize): FRMW-172-Migrate rxDiskSize to API docs

- demo/styleguide/basics/progressbars.html
- src/progressbar/README.md
- src/progressbar/docs/progressbar.html
- src/progressbar/progressbar.js
Sprint 2: JIRA FRMW-155: https://jira.rax.io/browse/FRMW-155
Migrate `progressbar` docs in README to ngdocs.
> feat(docs): FRMW-155-Migrate progressbar docs in README to ngdocs

- src/rxFavicon/README.md
- src/rxFavicon/rxFavicon.js
JIRA: https://jira.rax.io/browse/FRMW-174
> docs(rxFavicon): FRMW-174 Migrate rxFavicon

- src/rxCompile/README.md
- src/rxCompile/rxCompile.js
JIRA: https://jira.rax.io/browse/FRMW-171
> feat(docs): FRMW-171 - Migrate rxCompile docs

- src/rxIdentity/README.md
- src/rxIdentity/rxIdentity.js
JIRA: https://jira.rax.io/browse/FRMW-178
> docs(rxIdentity): FRMW-178 Migrate rxIdentity

- src/rxFloatingHeader/README.md
- src/rxFloatingHeader/rxFloatingHeader.js
JIRA: https://jira.rax.io/browse/FRMW-176
Migrate `rxFloatingHeader` to API Documentation.
> docs(rxFloatingHeader): FRMW-176-Migrate rxFloatingHeader to API Docs

- src/rxInfoPanel/README.md
- src/rxInfoPanel/rxInfoPanel.js
JIRA: https://jira.rax.io/browse/FRMW-179
> docs(rxInfoPanel): FRMW-179 Migrate rxInfoPanel

- src/rxLocalStorage/README.md
- src/rxLocalStorage/rxLocalStorage.js
JIRA: https://jira.rax.io/browse/FRMW-180
Migrate `rxLocalStorage` to API Documentation.
> docs(rxLocalStorage): FRMW-180-Migrate rxLocalStorage to API Docs

- src/rxLogout/README.md
- src/rxLogout/rxLogout.js
JIRA: https://jira.rax.io/browse/FRMW-181
Migrate `rxLogout` to API Documentation.
> docs(rxLogout): FRMW-181-Migrate rxLogout to API Docs

- src/rxCollapse/README.md
- src/rxCollapse/rxCollapse.js
JIRA: https://jira.rax.io/browse/FRMW-170
Migrate rxCollapse to API documentation.
> docs(rxCollapse): FRMW-170-Migrate rxCollapse to API docs

- demo/styleguide/basics.html
- demo/styleguide/forms.html
- demo/styleguide/layouts.html
- demo/styleguide/tables.html
JIRA:
https://jira.rax.io/browse/FRMW-226
https://jira.rax.io/browse/FRMW-227
https://jira.rax.io/browse/FRMW-228
https://jira.rax.io/browse/FRMW-229
https://jira.rax.io/browse/FRMW-230
https://jira.rax.io/browse/FRMW-231
https://jira.rax.io/browse/FRMW-232
https://jira.rax.io/browse/FRMW-233
https://jira.rax.io/browse/FRMW-234
> docs(styleguide): FRMW-226-234 Typo Content Updates

- src/rxModalAction/README.md
- src/rxModalAction/rxModalAction.js
JIRA: https://jira.rax.io/browse/FRMW-184
Migrate `rxModalAction` to API Documentation.
> docs(rxModalAction): FRMW-184-Migrate rxModalAction to API Docs

- src/rxSpinner/README.md
- src/rxSpinner/rxSpinner.js
JIRA: https://jira.rax.io/browse/FRMW-197
> feat(docs): FRMW-197 - Update rxSpinner docs

- src/rxRadio/README.md
- src/rxRadio/rxRadio.js
JIRA: https://jira.rax.io/browse/FRMW-190
> docs(rxRadio): FRMW-190 Migrate rxRadio

- src/rxFeedback/README.md
- src/rxFeedback/rxFeedback.js
Add documentation lost in #1240.
> docs(rxFeedback): add accidentally lost documentation

- src/rxSortableColumn/README.md
- src/rxSortableColumn/rxSortableColumn.js
JIRA: https://jira.rax.io/browse/FRMW-196
> feat(docs): FRMW-196 - Migrate rxSortableColumn docs

- src/rxOptionTable/README.md
- src/rxOptionTable/rxOptionTable.js
JIRA: https://jira.rax.io/browse/FRMW-186
Migrate `rxOptionTable` to API Documentation
> docs(rxOptionTable): FRMW-186-Migrate rxOptionTable to API Docs

- src/rxSelect/README.md
- src/rxSelect/rxSelect.js
JIRA: https://jira.rax.io/browse/FRMW-192
> feat(docs): FRMW-192 - Migrate rxSelect docs

- src/rxSearchBox/README.md
- src/rxSearchBox/rxSearchBox.js
JIRA: https://jira.rax.io/browse/FRMW-191
> docs(rxSearchBox): FRMW-191 Migrate rxSearchBox

- src/rxPageTitle/README.md
- src/rxPageTitle/rxPageTitle.js
JIRA: https://jira.rax.io/browse/FRMW-187
Migrate `rxPageTitle` to API Documentation.
> docs(rxPageTitle): FRMW-187-Migrate rxPageTitle to API Docs

- src/rxSession/README.md
- src/rxSession/rxSession.js
JIRA: https://jira.rax.io/browse/FRMW-194
> feat(docs): FRMW-194 - Migrate rxSession docs

- src/rxTags/docs/rxTags.html
- src/rxTags/docs/rxTags.midway.js
- src/rxTags/rxTags.exercise.js
- src/rxTags/templates/rxTags.html
Angular has some strange behavior when handling the `keydown` event. This caused some inconsistent behavior when sending a `backspace` key command on the local environment, which _locally_ would cause the browser to navigate backward and cause failures with remaining midway tests.
> chore(rxTags): fix/refactor local midways

- src/rxSessionStorage/README.md
- src/rxSessionStorage/rxSessionStorage.js
JIRA: https://jira.rax.io/browse/FRMW-195
> feat(docs): FRMW-195 - Migrate rxSessionStorage docs

- src/rxPermission/README.md
- src/rxPermission/rxPermission.js
JIRA: https://jira.rax.io/browse/FRMW-189
Migrate `rxPermission` to API Documentation.
> docs(rxPermission): FRMW-189-Migrate rxPermission to API Docs

- src/styles/vars.less
https://jira.rax.io/browse/FRMW-249
> style(vars): Add 2.0 color palette

- src/rxToggleSwitch/README.md
- src/rxToggleSwitch/rxToggleSwitch.js
JIRA: https://jira.rax.io/browse/FRMW-201
> feat(docs): FRMW-202 - Migrate rxToggleSwitch docs

- src/rxTokenInterceptor/README.md
- src/rxTokenInterceptor/rxTokenInterceptor.js
JIRA: https://jira.rax.io/browse/FRMW-202
Migrate `rxTokenInterceptor` to API Documentation.
> docs(rxTokenInterceptor): FRMW-202-Migrate to API Docs

- .travis.yml
related to #1295 for testing
* Node 0.12
* Protractor 2.5.0
> chore(travis): bump to node 0.12

- src/rxToggle/README.md
- src/rxToggle/rxToggle.js
JIRA: https://jira.rax.io/browse/FRMW-200
> feat(docs): FRMW-200 - Migrate rxToggle docs

- src/tabs/README.md
- src/tabs/tabs.js
JIRA: https://jira.rax.io/browse/FRMW-204
> feat(docs): Migrate tabs docs

- src/tooltips/README.md
- src/tooltips/tooltips.js
JIRA: https://jira.rax.io/browse/FRMW-205
Migrate `tooltips` to API Documentation.
> docs(tooltips): Migrate tooltips to API Docs

- src/rxUnauthorizedInterceptor/README.md
- src/rxUnauthorizedInterceptor/rxUnauthorizedInterceptor.js
JIRA: https://jira.rax.io/browse/FRMW-203
Migrate `rxUnauthorizedInterceptor` to API Documentation.
> docs(rxUnauthorizedInterceptor): Migrate to API Docs

- src/typeahead/README.md
- src/typeahead/typeahead.js
JIRA: https://jira.rax.io/browse/FRMW-206
*  [x] Dev LGTM
*  [x] Dev LGTM
> feat(docs): Migrate typehead docs

- demo/index.html
- demo/styles/typography.html
- src/rxApp/common.less
JIRA: https://jira.rax.io/browse/FRMW-267 - SPIKE: Basics - Typography
**Copy Edits** to `Typography` styleguide
> docs(copy_edits): FRMW-267-Typography-copy-edits

- demo/styleguide/tables.html
JIRA: https://jira.rax.io/browse/FRMW-263 - Table Footer Pagination via rxPaginate
**Copy Edits** for Tables Styleguide
> docs(copy_edits): FRMW-263-Copy-Edits-Pagination

- src/rxForm/docs/rxForm.html
- src/rxForm/rxForm.less
Correction for invalid styles with regards to rxCharacterCount
* https://jira.rax.io/browse/FRMW-92
> fix(rxForm): correct invalid styles for rxCharacterCount

- demo/styleguide/tables/collapsible-filtering.html
- src/rxPaginate/docs/rxPaginate.html
JIRA: https://jira.rax.io/browse/FRMW-106
Screenshot:
**Collapsable**
> refactor(table): FRMW-106 - Update design pattern for table filtering

- demo/styleguide/tables.html
JIRA: https://jira.rax.io/browse/FRMW-264
> chore(docs): FRMW-264 - Remove Non Data based tables section

- demo/styleguide/tables.html
JIRA: https://jira.rax.io/browse/FRMW-265
**Copy Edits** - Tables styleguide
> docs(copyedits): FRMW-265-Copy-Edits-styleguide

- src/styles/vars.less
https://jira.rax.io/browse/FRMW-286
> fix(vars): Switch gray scale so darker colors have higher var numbers

- protractor.visual.regression.conf.js
* Per Droogans' suggestion
https://jira.rax.io/browse/FRMW-288
> chore(vr_conf): remove phone resolutions

- demo/layout/collapsible.html
- demo/overview.html
- demo/styleguide/basics.html
- demo/styleguide/forms.html
- demo/styleguide/layouts.html
- demo/styleguide/modals.html
- demo/styleguide/tables.html
- demo/styles/buttons.html
- demo/styles/color.html
- demo/styles/typography.html
- demo/styles/wells.html
JIRA: https://jira.rax.io/browse/FRMW-236
> docs(styleguide): FRMW-236 FrameworkUI Copy Edits

- src/rxFloatingHeader/rxFloatingHeader.less
- src/rxForm/docs/rxForm.html
- src/rxForm/rxForm.less
- src/rxPaginate/docs/rxPaginate.html
- src/rxSelectFilter/docs/rxSelectFilter.html
- src/rxSelectFilter/rxSelectFilter.less
- src/rxSelectFilter/templates/rxSelectFilter.html
JIRA: https://jira.rax.io/browse/FRMW-241
* added `rx-form-section[controlled-width]` to `rxForm.less`
* removed `.title` class from `rxForm` docs
* added `.controlled-width` and examples to `rxForm` docs
* added `rxForm` compatibility to `rxSelectFilter` component.
* updated `rxPaginate` demo to use `rxForm`
---
> FRMW-241- Add rxForm compatibility to rxSelectFilter and more

- guides/common-questions.md
- guides/testing.md
- guides/versioning.md
- utils/rx-page-objects/README.md
> docs(docs): fix typos

- src/rxApp/rxApp.less
JIRA: https://jira.rax.io/browse/FRMW-128
LGTM'ed based on #1312
> fix(bux): FRMW-128-Unbreakable long page titles

- src/rxTags/README.md
- src/rxTags/rxTags.js
JIRA: https://jira.rax.io/browse/FRMW-294
> docs(rxTags): FRMW-294 Migrate rxTags

- src/rxMultiSelect/README.md
- src/rxMultiSelect/rxMultiSelect.js
JIRA: https://jira.rax.io/browse/FRMW-295
> docs(rxMultiSelect): FRMW-295 Migrate rxMultiSelect

- src/rxAge/docs/rxAge.html
- src/rxAge/docs/rxAge.midway.js
JIRA: https://jira.rax.io/browse/FRMW-296
> docs(rxAge): FRMW-296 Update rxAge

- src/grid/README.md
JIRA: https://jira.rax.io/browse/FRMW-297
> docs(grid): FRMW-297 Update Stability Tag: Grid Component

- src/progressbar/progressbar.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-270
> refactor(progressbar): FRMW-270 progressbar LESS Vars

- guides/css-styleguide.md
JIRA: https://jira.rax.io/browse/FRMW-290 
---
Update CSS Styleguide to establish 120 character line limit, which is inline with Javascript Styleguide.
> * Line length should be under 120 characters
> docs(css): FRMW-290-Document 120 char line limit

- src/rxFeedback/templates/feedbackForm.html
Updated text and removed modal
> chore(rxfeedback): Updated text, and removed well

- src/rxToggleSwitch/docs/rxToggleSwitch.html
- src/rxToggleSwitch/docs/rxToggleSwitch.js
JIRA: https://jira.rax.io/browse/FRMW-60 -  Demo: rxToggleSwitch Needs Example of Failed Async Operation
---
Added failed asynchronous operation example to `rxToggleSwitch` demo:
* User attempts to activate a service
* `rxToggleSwitch` shows disabled activation state as service attempts asynchronous operation
* Asynchronous operation fails
* `rxToggleSwitch` returns to deactivated state
> feat(demo): FRMW-60-rxToggleSwitch failed async demo

- demo/assets/demo.less
- demo/assets/generated_demo.css
Demo styles inconsistent with released styles. Removing unnecessary styling from demo.less
> fix(style): remove unnecessary style

- grunt-tasks/options/connect.js
- src/rxButton/rxButton.js
- src/rxForm/rxForm.js
- src/rxModalAction/rxModalAction.js
- src/rxNotify/rxNotify.js
- src/rxPaginate/rxPaginate.js
- src/rxPermission/rxPermission.js
- src/rxSearchBox/rxSearchBox.js
- src/rxStatusColumn/rxStatusColumn.js
- src/rxToggleSwitch/rxToggleSwitch.js
- src/tooltips/tooltips.js
- src/typeahead/typeahead.js
For Issue https://github.com/rackerlabs/encore-ui/issues/1338
Fix all demo links (`/#/components/...` -> `/encore-ui/#/components/...`)
> fix(links): Fix demo links

- src/rxMisc/docs/rxMisc.html
- src/rxMisc/rxMisc.spec.js
JIRA: https://jira.rax.io/browse/FRMW-422
---
Updated to reflect CSS `.title` class deprecation.
> fix(css): FRMW-422-Remove .title class from rxMisc

- demo/components.html
- demo/guides/guideViewer.html
- demo/layout/collapsible.html
- demo/styleguide/basics.html
- demo/styleguide/layout-2.html
- demo/styles/buttons.html
- demo/styles/color.html
- demo/styles/typography.html
- demo/styles/wells.html
Applying `.clear` class to appropriate locations in documentation markup.
-----
> fix(clearfix): apply clearfix to documentation pages

- demo/overview.html
- guides/html-styleguide.md
JIRA:
https://jira.rax.io/browse/FRMW-289
and
https://jira.rax.io/browse/FRMW-291
> docs(styleguide): FRMW-289 HTML Indentation Standard

- src/rxOptionTable/rxOptionTable.js
- src/rxOptionTable/rxOptionTable.spec.js
- src/rxOptionTable/templates/rxOptionTable.html
JIRA: https://jira.rax.io/browse/FRMW-112
> feat(selectAll): FRMW-112 - Add Select All to rxOptionTable

- demo/assets/_palette.less
- demo/assets/demo.less
- demo/assets/generated_demo.css
- demo/demo.js
- demo/styles/buttons.html
- demo/styles/color-1-0.html
- demo/styles/color.html
- src/rxApp/common.less
- src/styles/vars.less
https://jira.rax.io/browse/FRMW-259
New color palette, ready for review!
> docs(color): Add new color palette, link to old palette

- src/rxToggleSwitch/docs/rxToggleSwitch.midway.js
- src/rxToggleSwitch/rxToggleSwitch.exercise.js
- src/rxToggleSwitch/rxToggleSwitch.spec.js
JIRA: https://jira.rax.io/browse/FRMW-425
---
Added midway tests for `rxToggleSwitch` failed asynchronous operation
> feat(test): FRMW-425 add rxToggleSwitch failed async midway

- src/rxModalAction/docs/rxModalAction.html
- src/rxModalAction/docs/rxModalAction.midway.js
- src/rxModalAction/rxModalAction.js
- src/rxModalAction/rxModalAction.less
- src/rxModalAction/templates/rxModalAction.html
JIRA: https://jira.rax.io/browse/FRMW-269
> feat(disableLink): FRMW-269 - Add ability to disable modal link

- src/layout/docs/responsiveLayout.html
- src/layout/responsiveLayout.less
JIRA: https://jira.rax.io/browse/FRMW-118
---
- Document and provide an example of static flex items in `EncoreUI` layout.  
- Reformat to conform to HTML styleguide
> feat(flex): FRMW-118-Document static flex items

- demo/styles/typography.html
https://jira.rax.io/browse/FRMW-261
PR for :ant: :ant: :ant:
> docs(metadata): Update copy

- src/rxPageTitle/rxPageTitle.module.js
- src/rxPageTitle/scripts/rxPageTitle.js
- src/rxPageTitle/scripts/rxPageTitle.spec.js
- src/rxPageTitle/scripts/rxUnsafeRemoveHTML.js
- src/rxPageTitle/scripts/rxUnsafeRemoveHTML.spec.js
JIRA: https://jira.rax.io/browse/FRMW-359
> chore(rxPageTitle): decompose monolithic source

- src/rxAuth/rxAuth.module.js
- src/rxAuth/scripts/Auth.js
- src/rxAuth/scripts/Auth.spec.js
JIRA: https://jira.rax.io/browse/FRMW-481
> chore(rxAuth): decompose monolithic source

- src/rxSession/rxSession.module.js
- src/rxSession/scripts/Session.js
- src/rxSession/scripts/Session.spec.js
JIRA: https://jira.rax.io/browse/FRMW-474
> chore(rxSession): decompose monolithic source

- src/styles/vars.less
Adding comment headings to help clarify things for Design.
> chore(Less): vars.less labeling and comments

- src/rxCollapse/rxCollapse.less
- src/rxCollapse/templates/rxCollapse.html
JIRA: https://jira.rax.io/browse/FRMW-508
> fix(rxCollapse): expand button clickable area

- src/rxInfoPanel/rxInfoPanel.less
https://jira.rax.io/browse/FRMW-326
> style(rxInfoPanel): Update rxInfoPanel to use 2.0 color palette

- demo/styleguide/tables.html
JIRA: https://jira.rax.io/browse/FRMW-266
"ENCORE-SPECIFIC: You can add consistency and color code your status columns using the CSS classes included in rxStatusColumn. Ticket Queues have their own styling that predates this and can be seen in their tickets.less file. However, if rxStatusColumn classes are not suitable, please send feedback through the "Submit feedback" link."
"ENCORE-SPECIFIC: You can add consistency and color code your status columns using the .rxStatusColumn class. Ticket Queues have their own styling that predates this and can be seen in their tickets.less file. Your new project should use rxStatusColumn, however, if
this is not suitable, send feedback."
I have made minor copy changes. Refer to the code in this PR.
> docs(tables): FRMW-266 Tables - Status Columns

- src/rxCompile/rxCompile.module.js
- src/rxCompile/scripts/rxCompile.js
- src/rxCompile/scripts/rxCompile.spec.js
JIRA: https://jira.rax.io/browse/FRMW-487
---
`rxCompile` monolithic source decomposition.
> chore(rxCompile): FRMW-487 decompose monolithic source

- src/tooltips/tooltips.less
JIRA: https://jira.rax.io/browse/FRMW-339
> style(tooltips): FRMW-339 Update Tooltips to Color 2.0

- src/rxIdentity/rxIdentity.module.js
- src/rxIdentity/scripts/Identity.js
- src/rxIdentity/scripts/Identity.spec.js
JIRA: https://jira.rax.io/browse/FRMW-491
> chore(rxIdentity): decompose monolithic source

- src/rxSessionStorage/rxSessionStorage.module.js
- src/rxSessionStorage/scripts/SessionStorage.js
- src/rxSessionStorage/scripts/SessionStorage.spec.js
JIRA: https://jira.rax.io/browse/FRMW-498
---
`rxSessionStorage` monolithic decomposition.
> chore(rxSessionStorage): FRMW-498-monolithic decomposition

- src/rxToggleSwitch/rxToggleSwitch.module.js
- src/rxToggleSwitch/scripts/rxToggleSwitch.exercise.js
- src/rxToggleSwitch/scripts/rxToggleSwitch.js
- src/rxToggleSwitch/scripts/rxToggleSwitch.page.js
- src/rxToggleSwitch/scripts/rxToggleSwitch.spec.js
JIRA: https://jira.rax.io/browse/FRMW-501
> chore(rxToggleSwitch): decompose monolithic source

- src/rxUnauthorizedInterceptor/rxUnauthorizedInterceptor.module.js
- src/rxUnauthorizedInterceptor/scripts/UnauthorizedInterceptor.js
- src/rxUnauthorizedInterceptor/scripts/UnauthorizedInterceptor.spec.js
JIRA: https://jira.rax.io/browse/FRMW-503
---
`rxUnauthorizedInterceptor` monolithic decomposition.
> chore(rxUnauthorizedInterceptor): FRMW-503-monolithic decomposition

- src/rxTokenInterceptor/rxTokenInterceptor.module.js
- src/rxTokenInterceptor/scripts/TokenInterceptor.js
- src/rxTokenInterceptor/scripts/TokenInterceptor.spec.js
JIRA: https://jira.rax.io/browse/FRMW-502
> chore(rxTokenInterceptor): decompose monolithic source

- grunt-tasks/options/imagemin.js
> fix(imagemin): Fix grunt-tasks imagemin path

- src/components/rxSpinner/docs/rxSpinner.html
- src/components/rxSpinner/rxSpinner.less
https://jira.rax.io/browse/FRMW-336
> style(rxSpinner): Update rxSpinner to use new color palette, remove unused styles

- src/components/tabs/tabs.less
- src/styles/vars.less
https://jira.rax.io/browse/FRMW-338
> style(tabs): Update tabs to use 2.0 colors

- CONTRIBUTING.md
https://jira.rax.io/browse/FRMW-468
@ssalinas24 I feel like there's more we can document or explain around design LGTMs that you can provide some perspective on, having had to learn how to provide design LGTMs more recently than me.
Suggestions welcome from all, though. Devs, you may also have insight into how design LGTMs are different that I can't see because I'm too close to it :grin:
> docs(contributing): Add tota11y and design LGTM info

- src/components/rxAccountInfo/rxAccountInfo.less
- src/components/rxApp/templates/rxAccountUsers.html
- src/components/rxForm/rxForm.less
https://jira.rax.io/browse/FRMW-330
User dropdown in Encore Cloud
> style(rxAccountInfo): Update rxAccountInfo to use 2.0 colors

- src/components/rxCollapse/docs/rxCollapse.html
JIRA: https://jira.rax.io/browse/FRMW-510
---
Update `rxCollapse` demo to use `rxMetadata`.
> chore(rxCollapse): FRMW-510 update demo with rxMetadata

- src/components/rxPaginate/scripts/rxPaginate.js
> Fix incorrect text in rxPaginate directive docs

- bower.json
- demo/index.html
- grunt-tasks/options/karma.js
- src/components/rxAge/scripts/rxAge.js
JIRA: https://jira.rax.io/browse/FRMW-449
---
Update `bower.json` with `moment.js` package and remove deprecated `momentjs`.
> chore(bower): FRMW-449-update bower package to moment

- src/components/rxAccountInfo/rxAccountInfo.less
- src/components/rxApp/rxApp.less
- src/components/rxApp/templates/rxAccountUsers.html
- src/components/rxForm/rxForm.less
JIRA: https://jira.rax.io/browse/FRMW-548
> fix(styles): correct styling for user select in nav

- src/quarks/quarks.module.js
Organize quarks by component type. *Should make for simpler rebasing/merging.*
> docs(quarks): organize Quarks overview

- src/components/rxApp/rxApp.less
JIRA: https://jira.rax.io/browse/FRMW-334
> style(rxapp): FRMW-334 Update Left Nav to Color 2.0

- src/components/rxForm/rxForm.less
- src/molecules/molecules.module.js
- src/molecules/rxDatePicker/docs/examples/rxDatePicker.empty.html
- src/molecules/rxDatePicker/docs/examples/rxDatePicker.empty.js
- src/molecules/rxDatePicker/docs/examples/rxDatePicker.simple.html
- src/molecules/rxDatePicker/docs/examples/rxDatePicker.simple.js
- src/molecules/rxDatePicker/docs/rxDatePicker.html
- src/molecules/rxDatePicker/docs/rxDatePicker.js
- src/molecules/rxDatePicker/docs/rxDatePicker.midway.js
- src/molecules/rxDatePicker/rxDatePicker.less
- src/molecules/rxDatePicker/rxDatePicker.meta.json
- src/molecules/rxDatePicker/scripts/rxDatePicker.js
- src/molecules/rxDatePicker/scripts/rxDatePicker.page.js
- src/molecules/rxDatePicker/scripts/rxDatePicker.spec.js
- src/molecules/rxDatePicker/templates/rxDatePicker.html
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-95
*screenshots to follow*
> feat(rxDatePicker): Add rxDatePicker Molecule

- src/components/rxMisc/rxMisc.module.js
- src/quarks/quarks.module.js
- src/quarks/titleize/docs/examples/titleize.simple.html
- src/quarks/titleize/docs/examples/titleize.simple.js
- src/quarks/titleize/docs/titleize.docs.html
- src/quarks/titleize/scripts/titleize.js
- src/quarks/titleize/scripts/titleize.spec.js
- src/quarks/titleize/titleize.meta.json
JIRA: https://jira.rax.io/browse/FRMW-397
---
Refactor `rxMisc.titleize` to Quark filter.
> refactor(titleize): FRMW-397 convert titleize to a Quark filter

- src/components/rxButton/rxButton.less
- src/components/rxModalAction/rxModalAction.less
- src/molecules/progressbar/progressbar.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-545
> style(vars): FRMW-545 Rename Variables with Proper Component Prefix

- src/components/rxEnvironment/rxEnvironment.module.js
- src/quarks/quarks.module.js
- src/quarks/rxCapitalize/rxCapitalize.meta.json
- src/quarks/rxEnvironmentMatch/docs/examples/rxEnvironmentMatch.simple.html
- src/quarks/rxEnvironmentMatch/docs/examples/rxEnvironmentMatch.simple.js
- src/quarks/rxEnvironmentMatch/docs/rxEnvironmentMatch.docs.html
- src/quarks/rxEnvironmentMatch/rxEnvironmentMatch.meta.json
- src/quarks/rxEnvironmentMatch/scripts/rxEnvironmentMatch.js
- src/quarks/rxEnvironmentMatch/scripts/rxEnvironmentMatch.spec.js
- src/quarks/rxEnvironmentUrl/docs/examples/rxEnvironmentUrl.simple.html
- src/quarks/rxEnvironmentUrl/docs/examples/rxEnvironmentUrl.simple.js
- src/quarks/rxEnvironmentUrl/docs/rxEnvironmentUrl.docs.html
- src/quarks/rxEnvironmentUrl/rxEnvironmentUrl.meta.json
- src/quarks/rxEnvironmentUrl/scripts/rxEnvironmentUrl.js
- src/quarks/rxEnvironmentUrl/scripts/rxEnvironmentUrl.spec.js
JIRA: https://jira.rax.io/browse/FRMW-391, https://jira.rax.io/browse/FRMW-392
---
Refactor `rxEnvironmentMatch` filter and `rxEnvironmentUrl` filter into `Quarks`.
> refactor(quarks): FRMW-391-392-rxEnvironmentMatch and rxEnvironmentUrl

- utils/rx-page-objects/README.md
This has been bugging me for a while.
> docs(rxPageObjects): Correct javascript syntax errors

- src/components/rxSelectFilter/rxSelectFilter.module.js
- src/quarks/SelectFilter/SelectFilter.meta.json
- src/quarks/SelectFilter/docs/SelectFilter.docs.html
- src/quarks/SelectFilter/scripts/SelectFilter.js
- src/quarks/SelectFilter/scripts/SelectFilter.spec.js
- src/quarks/quarks.module.js
JIRA: https://jira.rax.io/browse/FRMW-411
---
Refactor `rxSelectFilter.SelectFilter` to Quark service.
> refactor(SelectFilter): FRMW-411-covert to quark.

- src/components/rxMisc/rxMisc.module.js
- src/quarks/quarks.module.js
- src/quarks/rxNestedElement/docs/rxNestedElement.docs.html
- src/quarks/rxNestedElement/rxNestedElement.meta.json
- src/quarks/rxNestedElement/scripts/rxNestedElement.js
- src/quarks/rxNestedElement/scripts/rxNestedElement.spec.js
JIRA: https://jira.rax.io/browse/FRMW-400
---
Refactor `rxMisc.rxNestedElement` to Quark service.
> refactor(rxNestedElement): FRMW-400-convert to Quark service.

- src/components/rxEnvironment/rxEnvironment.module.js
- src/components/rxEnvironment/scripts/rxIfEnvironment.js
- src/quarks/Environment/Environment.meta.json
- src/quarks/Environment/docs/Environment.docs.html
- src/quarks/Environment/docs/examples/Environment.simple.html
- src/quarks/Environment/docs/examples/Environment.simple.js
- src/quarks/Environment/scripts/Environment.js
- src/quarks/quarks.module.js
JIRA: https://jira.rax.io/browse/FRMW-393
---
Refactor `rxEnvironment.Environment` to Quark Service.
> FRMW-393: Refactor rxEnvironment.Environment to Quark Service

- src/components/rxPageTitle/rxPageTitle.module.js
- src/quarks/quarks.module.js
- src/quarks/rxUnsafeRemoveHTML/docs/examples/rxUnsafeRemoveHTML.simple.html
- src/quarks/rxUnsafeRemoveHTML/docs/examples/rxUnsafeRemoveHTML.simple.js
- src/quarks/rxUnsafeRemoveHTML/docs/rxUnsafeRemoveHTML.docs.html
- src/quarks/rxUnsafeRemoveHTML/rxUnsafeRemoveHTML.meta.json
- src/quarks/rxUnsafeRemoveHTML/scripts/rxUnsafeRemoveHTML.js
- src/quarks/rxUnsafeRemoveHTML/scripts/rxUnsafeRemoveHTML.spec.js
JIRA: https://jira.rax.io/browse/FRMW-403
---
Refactor `rxPageTitle.rxUnsafeRemoteHTML` to Quark filter.
> refactor(rxUnsafeRemoteHTML): FRMW-403-convert to quark filter

- src/components/rxNotify/rxNotify.module.js
- src/quarks/quarks.module.js
- src/quarks/rxPromiseNotifications/docs/examples/rxPromiseNotifications.simple.html
- src/quarks/rxPromiseNotifications/docs/examples/rxPromiseNotifications.simple.js
- src/quarks/rxPromiseNotifications/docs/rxPromiseNotifications.docs.html
- src/quarks/rxPromiseNotifications/rxPromiseNotifications.meta.json
- src/quarks/rxPromiseNotifications/scripts/rxPromiseNotifications.js
- src/quarks/rxPromiseNotifications/scripts/rxPromiseNotifications.spec.js
JIRA: https://jira.rax.io/browse/FRMW-402
---
Refactor `rxPromiseNotifications` to Quark service.
> refactor(rxPromiseNotifications): FRMW-402-convert to quark service.

- src/components/rxSortableColumn/rxSortableColumn.module.js
- src/quarks/quarks.module.js
- src/quarks/rxSortUtil/docs/rxSortUtil.docs.html
- src/quarks/rxSortUtil/rxSortUtil.meta.json
- src/quarks/rxSortUtil/scripts/rxSortUtil.js
- src/quarks/rxSortUtil/scripts/rxSortUtil.spec.js
JIRA: https://jira.rax.io/browse/FRMW-413
---
Refactor `rxSortableColumn.rxSortUtil` to Quark Service.
> refactor(rxSortUtil): FRMW-413-convert to quark.

- src/components/rxStatusColumn/rxStatusColumn.module.js
- src/quarks/rxStatusMappings/docs/examples/rxStatusMappings.demo.less
- src/quarks/rxStatusMappings/docs/examples/rxStatusMappings.simple.html
- src/quarks/rxStatusMappings/docs/examples/rxStatusMappings.simple.js
- src/quarks/rxStatusMappings/docs/rxStatusMappings.docs.html
- src/quarks/rxStatusMappings/rxStatusMappings.meta.json
- src/quarks/rxStatusMappings/scripts/rxStatusMappings.js
- src/quarks/rxStatusMappings/scripts/rxStatusMappings.spec.js
JIRA: https://jira.rax.io/browse/FRMW-418
---
Refactor `rxStatusColumn.rxStatusMappings` to Quark Service.
> refactor(rxStatusMappings): FRMW-418-convert to Quark Service.

- src/components/rxSortableColumn/rxSortableColumn.module.js
- src/quarks/quarks.module.js
- src/quarks/rxSortEmptyTop/docs/examples/rxSortEmptyTop.simple.html
- src/quarks/rxSortEmptyTop/docs/examples/rxSortEmptyTop.simple.js
- src/quarks/rxSortEmptyTop/docs/rxSortEmptyTop.docs.html
- src/quarks/rxSortEmptyTop/rxSortEmptyTop.meta.json
- src/quarks/rxSortEmptyTop/scripts/rxSortEmptyTop.js
- src/quarks/rxSortEmptyTop/scripts/rxSortEmptyTop.spec.js
JIRA: https://jira.rax.io/browse/FRMW-412
---
Refactor `rxSortableColumn.rxSortEmptyTop` to Quark filter.
> refactor(rxSortEmptyTop): FRMW-412-refactor to Quark filter

- src/components/rxSelectFilter/rxSelectFilter.module.js
- src/quarks/Apply/Apply.meta.json
- src/quarks/Apply/docs/Apply.docs.html
- src/quarks/Apply/docs/examples/Apply.simple.html
- src/quarks/Apply/docs/examples/Apply.simple.js
- src/quarks/Apply/scripts/Apply.js
- src/quarks/SelectFilter/scripts/SelectFilter.js
JIRA: https://jira.rax.io/browse/FRMW-410
---
Refactor `rxSelectFilter.Apply` to Quark filter.
> refactor(Apply): FRMW-410 convert rxSelectFilter.Apply to quark

- src/components/rxAccountInfo/scripts/rxAccountInfo.js
JIRA: https://jira.rax.io/browse/FRMW-574
> fix(rxAccountInfo): auto load primary team badges

- src/components/rxMisc/rxMisc.module.js
- src/quarks/rxDOMHelper/docs/rxDOMHelper.docs.html
- src/quarks/rxDOMHelper/rxDOMHelper.meta.json
- src/quarks/rxDOMHelper/scripts/rxDOMHelper.js
- src/quarks/rxDOMHelper/scripts/rxDOMHelper.spec.js
JIRA: https://jira.rax.io/browse/FRMW-399
---
Refactor `rxMisc.rxDOMHelper` to Quark Service.
> refactor(rxDOMHelper): FRMW-399-convert to Quark Service.

- src/components/rxForm/rxForm.module.js
- src/quarks/rxFormUtils/docs/rxFormUtils.docs.html
- src/quarks/rxFormUtils/rxFormUtils.meta.json
- src/quarks/rxFormUtils/scripts/rxFormUtils.js
- src/quarks/rxFormUtils/scripts/rxFormUtils.spec.js
JIRA: https://jira.rax.io/browse/FRMW-396
---
Refactor `rxForm.rxFormUtils` to Quark Service.
> refactor(rxFormUtils): FRMW-396-convert to Quark Service.

- src/components/rxFeedback/rxFeedback.module.js
- src/quarks/rxScreenshotSvc/docs/rxScreenshotSvc.docs.html
- src/quarks/rxScreenshotSvc/rxScreenshotSvc.meta.json
- src/quarks/rxScreenshotSvc/scripts/rxScreenshotSvc.js
- src/quarks/rxScreenshotSvc/scripts/rxScreenshotSvc.spec.js
JIRA: https://jira.rax.io/browse/FRMW-395
---
Refactor `rxFeedback.rxScreenshotSvc` to Quark Service.
> refactor(rxScreenshotSvc): FRMW-395-convert to Quark Service.

- src/components/rxFeedback/rxFeedback.module.js
- src/quarks/rxFeedbackSvc/docs/rxFeedbackSvc.docs.html
- src/quarks/rxFeedbackSvc/rxFeedbackSvc.meta.json
- src/quarks/rxFeedbackSvc/scripts/rxFeedbackSvc.js
- src/quarks/rxFeedbackSvc/scripts/rxFeedbackSvc.spec.js
JIRA: https://jira.rax.io/browse/FRMW-394
---
Refactor `rxFeedback.rxFeedbackSvc` to Quark Service.
> refactor(rxFeedbackSvc): FRMW-394-covert to Quark Service.

- src/components/rxApp/common.less
- src/components/rxApp/rxApp.less
- src/components/rxBulkSelect/rxBulkSelect.less
- src/components/rxButton/rxButton.less
- src/components/rxForm/rxForm.less
- src/components/rxMultiSelect/rxMultiSelect.less
- src/components/rxPaginate/rxPaginate.less
- src/components/tooltips/tooltips.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-546
I have added variables that I believe will help consolidate and unify some of the duplicated properties and styling that i have seen through out components. However, this is only based on my brief history with the framework, and the items that I have had related tasks to. I would highly appreciate any feedback from any DEVS that have way more history with the framework, in case I can add additional items that i may have missed.
> style(vars): FRMW-546 Setup Global Vars

- src/components/tooltips/docs/tooltips.html
- src/components/tooltips/tooltips.less
- src/styles/vars.less
https://jira.rax.io/browse/FRMW-551
> style(tooltips): Add border to tooltips

- src/components/configs/scripts/feedbackApi.js
- src/quarks/feedbackApi/docs/feedbackApi.docs.html
- src/quarks/feedbackApi/feedbackApi.meta.json
- src/quarks/feedbackApi/scripts/feedbackApi.js
- src/quarks/rxFeedbackSvc/scripts/rxFeedbackSvc.spec.js
JIRA: https://jira.rax.io/browse/FRMW-379
---
Refactor `configs.feedbackApi` to Quark.
> refactor(feedbackApi): FRMW-379-convert to Quark.

- src/components/rxStatusColumn/rxStatusColumn.module.js
- src/quarks/rxStatusColumnIcons/docs/rxStatusColumnIcons.docs.html
- src/quarks/rxStatusColumnIcons/rxStatusColumnIcons.meta.json
- src/quarks/rxStatusColumnIcons/scripts/rxStatusColumnIcons.js
JIRA: https://jira.rax.io/browse/FRMW-417
---
Refactor `rxStatusColumn.rxStatusColumnIcons` to Quark object.
> refactor(rxStatusColumnIcons): FRMW-417-convert to Quark object.

- src/components/rxMisc/README.md
- src/components/rxMisc/docs/rxMisc.midway.js
- src/components/rxMisc/rxMisc.meta.json
- src/components/rxMisc/rxMisc.module.js
- src/quarks/quarks.module.js
- src/quarks/rxAutoSave/docs/examples/rxAutoSave.simple.html
- src/quarks/rxAutoSave/docs/examples/rxAutoSave.simple.js
- src/quarks/rxAutoSave/docs/rxAutoSave.docs.html
- src/quarks/rxAutoSave/docs/rxAutoSave.midway.js
- src/quarks/rxAutoSave/rxAutoSave.meta.json
- src/quarks/rxAutoSave/scripts/rxAutoSave.js
- src/quarks/rxAutoSave/scripts/rxAutoSave.spec.js
JIRA: https://jira.rax.io/browse/FRMW-398
---
Refactor `rxMisc.rxAutoSave` to Quark Service.
> refactor(rxAutoSave): FRMW-398-convert to Quark Service.

- src/components/rxBulkSelect/rxBulkSelect.module.js
- src/quarks/NotifyProperties/NotifyProperties.meta.json
- src/quarks/NotifyProperties/docs/NotifyProperties.docs.html
- src/quarks/NotifyProperties/scripts/NotifyProperties.js
JIRA: https://jira.rax.io/browse/FRMW-389
---
Refactor `rxBulkSelect.NotifyProperties` to Quark Service.
> refactor(NotifyProperties): FRMW-389-convert to Quark Service.

- src/components/rxBulkSelect/rxBulkSelect.module.js
- src/quarks/rxBulkSelectUtils/docs/rxBulkSelectUtils.docs.html
- src/quarks/rxBulkSelectUtils/rxBulkSelectUtils.meta.json
- src/quarks/rxBulkSelectUtils/scripts/rxBulkSelectUtils.js
JIRA: https://jira.rax.io/browse/FRMW-390
---
Refactor `rxBulkSelect.rxBulkSelectUtils` to Quark Service.
> refactor(rxBulkSelectUtils): FRMW-390-convert to Quark Service.

- src/quarks/quarks.module.js
**Sprint Docs 10 Quarks Maintenance.**
---
Review and capture all quarks added in `Docs 10` to  `src/quarks/quarks.module.js`.
> refactor(quarks): Sprint Docs 10 Quark maintenance.

- src/atoms/rxCheckbox/rxCheckbox.less
- src/components/rxForm/rxForm.less
- src/components/rxRadio/rxRadio.less
- src/components/rxStatusColumn/rxStatusColumn.less
- src/components/rxToggleSwitch/rxToggleSwitch.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-593
> style(vars): FRMW-593 Update Disabled Global Vars

- src/components/rxApp/common.less
- src/components/rxBulkSelect/rxBulkSelect.less
- src/components/rxButton/rxButton.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-594
> style(vars): FRMW-594 Update Link Global Vars

- src/components/rxButton/rxButton.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-606
> style(vars): FRMW-606 Correct rxButton Component Vars

- CONTRIBUTING.md
- demo/templates/overview.html
JIRA: https://jira.rax.io/browse/FRMW-639
---
Update the process to submit bugs and issues to the `EncoreUI` team.
> docs(contributing): FRMW-639-update bug and issue steps.

- src/components/rxApp/rxApp.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-603
> style(vars): FRMW-603 Update Preprod Warning Var Values

- src/components/rxApp/rxApp.module.js
- src/quarks/rxHideIfUkAccount/docs/rxHideIfUkAccount.docs.html
- src/quarks/rxHideIfUkAccount/rxHideIfUkAccount.meta.json
- src/quarks/rxHideIfUkAccount/scripts/rxHideIfUkAccount.js
- src/quarks/rxHideIfUkAccount/scripts/rxHideIfUkAccount.spec.js
JIRA: https://jira.rax.io/browse/FRMW-382
---
Refactor `rxApp.rxHideIfUkAccount` to Quark Service.
> refactor(rxHideIfUkAccount): FRMW-382-convert to Quark Service.

- src/components/rxApp/rxApp.module.js
- src/quarks/rxVisibility/docs/rxVisibility.docs.html
- src/quarks/rxVisibility/rxVisibility.meta.json
- src/quarks/rxVisibility/scripts/rxVisibility.js
- src/quarks/rxVisibility/scripts/rxVisibility.spec.js
JIRA: https://jira.rax.io/browse/FRMW-383
---
Refactor `rxApp.rxVisibility` to Quark Service.
> refactor(rxVisibility): FRMW-383-convert to Quark Service.

- src/molecules/rxDatePicker/docs/examples/rxDatePicker.simple.js
- src/molecules/rxDatePicker/docs/rxDatePicker.midway.js
- src/molecules/rxDatePicker/scripts/rxDatePicker.page.js
> test(rxDatePicker): Reduce surface of page object API

- src/quarks/quarks.module.js
---
Update `quarks.module.js` with new quarks added during Sprint Docs 11.
- https://github.com/rackerlabs/encore-ui/pull/1513 (Session)
- https://github.com/rackerlabs/encore-ui/pull/1522 (rxHideIfUkAccount)
- https://github.com/rackerlabs/encore-ui/pull/1523 (rxVisibility)
> refactor(quarks): Sprint Docs 11 Quarks maintenance.

- src/components/rxButton/docs/rxButton.html
- src/components/rxButton/docs/rxButton.midway.js
- src/components/rxPaginate/docs/rxPaginate.html
- src/components/rxPaginate/docs/rxPaginate.midway.js
- src/components/rxSearchBox/scripts/rxSearchBox.page.js
JIRA: https://jira.rax.io/browse/FRMW-638
---
**Tech Debt:** Eliminate warnings in midways tests.
> fix(midways): FRMW-638-eliminate midway test warnings.

- src/components/rxApp/rxApp.module.js
- src/quarks/rxStatusTags/docs/rxStatusTags.docs.html
- src/quarks/rxStatusTags/rxStatusTags.meta.json
- src/quarks/rxStatusTags/scripts/rxStatusTags.js
- src/quarks/rxStatusTags/scripts/rxStatusTags.spec.js
JIRA: https://jira.rax.io/browse/FRMW-385
---
Refactor `rxApp.rxStatusTags` to Quark Service.
> refactor(rxStatusTags): FRMW-385-convert to Quark Service.

- src/components/rxApp/rxApp.module.js
- src/quarks/encoreRoutes/docs/encoreRoutes.docs.html
- src/quarks/encoreRoutes/encoreRoutes.meta.json
- src/quarks/encoreRoutes/scripts/encoreRoutes.js
JIRA: https://jira.rax.io/browse/FRMW-381
---
Refactor `rxApp.encoreRoutes` to Quark Service.
> refactor(encoreRoutes): FRMW-381-convert to Quark Service.

- src/components/rxPaginate/rxPaginate.module.js
- src/quarks/PageTracking/PageTracking.meta.json
- src/quarks/PageTracking/docs/PageTracking.docs.html
- src/quarks/PageTracking/scripts/PageTracking.js
- src/quarks/PageTracking/scripts/PageTracking.spec.js
- src/quarks/rxPaginateUtils/docs/rxPaginateUtils.docs.html
- src/quarks/rxPaginateUtils/rxPaginateUtils.meta.json
- src/quarks/rxPaginateUtils/scripts/rxPaginateUtils.js
- src/quarks/rxPaginateUtils/scripts/rxPaginateUtils.spec.js
JIRA: https://jira.rax.io/browse/FRMW-407 (`rxPaginate.PageTracking`)
JIRA: https://jira.rax.io/browse/FRMW-408 (`rxPaginate.rxPaginateUtils`) 
---
Refactor `rxPaginate.PageTracking` and `rxPaginate.rxPaginateUtils` to Quark Services.
> refactor(quarks): FRMW-407 rxPageTracking FRMW-408 rxPaginateUtils.

- src/components/rxPermission/rxPermission.module.js
- src/quarks/Permission/Permission.meta.json
- src/quarks/Permission/docs/Permission.docs.html
- src/quarks/Permission/scripts/Permission.js
- src/quarks/Permission/scripts/Permission.spec.js
JIRA: https://jira.rax.io/browse/FRMW-409
---
Refactor `rxPermission.Permission` to Quark Service.
> refactor(Permission): FRMW-409-convert to Quark Service

- src/components/rxPaginate/rxPaginate.module.js
- src/quarks/Page/Page.meta.json
- src/quarks/Page/docs/Page.docs.html
- src/quarks/Page/scripts/Page.js
- src/quarks/Page/scripts/Page.spec.js
- src/quarks/Paginate/Paginate.meta.json
- src/quarks/Paginate/docs/Paginate.docs.html
- src/quarks/Paginate/scripts/Paginate.js
- src/quarks/Paginate/scripts/Paginate.spec.js
JIRA: https://jira.rax.io/browse/FRMW-405 (`rxPaginate.Page`)
JIRA: https://jira.rax.io/browse/FRMW-406 (`rxPaginate.Paginate`)
---
Refactor `rxPaginate.Page` and `rxPaginate.Paginate` to Quark Filters.
> refactor(quarks): FRMW-405 Page and FRMW-406 Paginate filters

- .gitignore
- grunt-tasks/options/jsdoc.js
- grunt-tasks/options/watch.js
- src/atoms/rxCheckbox/scripts/rxCheckbox.exercise.js
- src/atoms/rxCheckbox/scripts/rxCheckbox.page.js
- src/components/rxAccountInfo/scripts/rxAccountInfo.page.js
- src/components/rxActionMenu/scripts/rxActionMenu.page.js
- src/components/rxBreadcrumbs/scripts/rxBreadcrumbs.page.js
- src/components/rxBulkSelect/scripts/rxBulkSelect.exercise.js
- src/components/rxBulkSelect/scripts/rxBulkSelect.page.js
- src/components/rxCharacterCount/scripts/rxCharacterCount.exercise.js
- src/components/rxCharacterCount/scripts/rxCharacterCount.page.js
- src/components/rxCollapse/scripts/rxCollapse.exercise.js
- src/components/rxCollapse/scripts/rxCollapse.page.js
- src/components/rxEnvironment/scripts/rxEnvironment.page.js
- src/components/rxFeedback/scripts/rxFeedback.page.js
- src/quarks/rxAge/scripts/rxAge.page.js
- src/quarks/rxDiskSize/scripts/rxDiskSize.page.js
- utils/rx-page-objects/doc/README.md
- utils/rx-page-objects/jsdoc.conf.json
This helps make the new jsdoc3-style documentation site much more readable.
I will be continuing this, but wanted to check in the first 30% of the updates early, before this gets too big.
I will annotate this PR, highlighting any changes that aren't 100% straight up documentation changes. I had to supplement a few things here and there as I went.
> E2e jsdoc3 part one

- src/quarks/feedbackTypes/docs/feedbackTypes.docs.html
- src/quarks/feedbackTypes/feedbackTypes.meta.json
- src/quarks/feedbackTypes/scripts/feedbackTypes.js
JIRA: https://jira.rax.io/browse/FRMW-697
---
Refactor `rxFeedback.feedbackTypes` to Quark Value.
> refactor(feedbackTypes): FRMW-697-convert to Quark Value

- src/components/rxModalAction/rxModalAction.module.js
- src/components/rxModalAction/scripts/rxModalForm.spec.js
- src/quarks/rxModalFooterTemplates/docs/rxModalFooterTemplates.docs.html
- src/quarks/rxModalFooterTemplates/rxModalFooterTemplates.meta.json
- src/quarks/rxModalFooterTemplates/scripts/rxModalFooterTemplates.js
- src/quarks/rxModalFooterTemplates/scripts/rxModalFooterTemplates.spec.js
JIRA: https://jira.rax.io/browse/FRMW-695
---
Refactor `rxModalAction.rxModalFooterTemplates` to Quark Service.
> refactor(rxModalFooterTemplates): FRMW-695-convert to Quark Service

- src/components/tabs/scripts/tabs.page.js
> docs(tabs): Page objects to jsdoc3

- src/components/rxToggleSwitch/scripts/rxToggleSwitch.exercise.js
- src/components/rxToggleSwitch/scripts/rxToggleSwitch.page.js
> docs(rxToggleSwitch): Page objects to jsdoc3

- src/components/rxTags/scripts/rxTags.exercise.js
- src/components/rxTags/scripts/rxTags.page.js
> docs(rxTags): Page objects to jsdoc3

- src/components/rxSelect/scripts/rxSelect.exercise.js
- src/components/rxSelect/scripts/rxSelect.page.js
> docs(rxSelect): Page objects to jsdoc3

- src/components/rxSearchBox/scripts/rxSearchBox.exercise.js
- src/components/rxSearchBox/scripts/rxSearchBox.page.js
> docs(rxSearchBox): Page objects to jsdoc3

- src/components/rxRadio/scripts/rxRadio.exercise.js
- src/components/rxRadio/scripts/rxRadio.page.js
> docs(rxRadio): Page objects to jsdoc3

- src/components/rxPaginate/scripts/rxPaginate.exercise.js
- src/components/rxPaginate/scripts/rxPaginate.page.js
> docs(rxPaginate): Page objects to jsdoc3

- src/components/rxOptionTable/scripts/rxOptionTable.exercise.js
- src/components/rxOptionTable/scripts/rxOptionTable.page.js
> docs(rxOptionTable): Page objects to jsdoc3

- src/components/rxModalAction/scripts/rxModalAction.page.js
> docs(rxModalAction): Page objects to jsdoc3

- src/components/rxMultiSelect/scripts/rxMultiSelect.exercise.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.page.js
> docs(rxMultiSelect): Page objects to jsdoc3

- src/components/rxMisc/scripts/rxMisc.page.js
> docs(rxMisc): Page objects to jsdoc3

- src/components/rxInfoPanel/scripts/rxInfoPanel.page.js
> docs(rxInfoPanel): Page objects to jsdoc3

- src/components/rxForm/scripts/rxFieldName.exercise.js
> docs(rxFieldName): Page objects to jsdoc3

- src/components/rxApp/scripts/rxPage.page.js
> docs(rxPage): Page objects to jsdoc3

- src/components/rxCharacterCount/rxCharacterCount.less
- src/components/rxForm/rxForm.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-607
> style(vars): FRMW-607 Replace rxFieldName Component Vars

- src/components/rxApp/common.less
- src/components/rxBulkSelect/rxBulkSelect.less
- src/components/rxButton/rxButton.less
- src/components/rxOptionTable/rxOptionTable.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-605
> style(vars): FRMW-605 Update Table Vars to Global Vars

- src/components/rxForm/scripts/rxForm.page.js
> docs(rxForm): Page objects to jsdoc3

- src/quarks/rxAge/scripts/rxAge.page.js
> docs(rxAge): Update return type

- src/components/rxApp/scripts/rxApp.page.js
> docs(rxApp): Page objects to jsdoc3

- src/components/rxMetadata/scripts/rxMetadata.exercise.js
- src/components/rxMetadata/scripts/rxMetadata.page.js
> docs(rxMetadata): Page objects to jsdoc3

- src/quarks/rxNotify/scripts/rxNotify.page.js
> docs(rxNotify): Page objects to jsdoc3

- src/quarks/rxFeedbackController/docs/rxFeedbackController.docs.html
- src/quarks/rxFeedbackController/rxFeedbackController.meta.json
- src/quarks/rxFeedbackController/scripts/rxFeedbackController.js
- src/quarks/rxFeedbackController/scripts/rxFeedbackController.spec.js
JIRA: https://jira.rax.io/browse/FRMW-698
---
Refactor `rxFeedback.rxFeedbackController` to Quark Controller.
> refactor(rxFeedbackController): FRMW-698-convert to Quark Controller

- src/components/rxModalAction/scripts/rxModalAction.spec.js
- src/quarks/rxModalCtrl/docs/rxModalCtrl.docs.html
- src/quarks/rxModalCtrl/rxModalCtrl.meta.json
- src/quarks/rxModalCtrl/scripts/rxModalCtrl.js
JIRA: https://jira.rax.io/browse/FRMW-699
---
Refactor `rxModalAction.rxModalCtrl` to Quark Controller.
> refactor(rxModalCtrl): FRMW-699-convert to Quark Controller

- utils/visual-regression/styleguide/forms.midway.js
Correct selector for form manual save visual regression screenshot.
> fix(visualRegression): correct forms manual save screenshot

- src/quarks/PaginatedItemsSummary/PaginatedItemsSummary.meta.json
- src/quarks/PaginatedItemsSummary/docs/PaginatedItemsSummary.docs.html
- src/quarks/PaginatedItemsSummary/scripts/PaginatedItemsSummary.js
- src/quarks/PaginatedItemsSummary/scripts/PaginatedItemsSummary.spec.js
JIRA: https://jira.rax.io/browse/FRMW-696
---
Refactor `rxPaginate.PaginatedItemsSummary` to Quark Filter.
> refactor(PaginatedItemsSummary): FRWM-696-convert to Quark Filter

- src/components/rxEnvironment/rxEnvironment.module.js
- src/quarks/quarks.module.js
---
Update `src/quarks/quarks.module.js` with remaining new quarks added during Sprint Docs 12.
> docs(quarks): Sprint 12 update Quarks API Docs links

- src/components/rxSortableColumn/scripts/rxSortableColumn.page.js
> docs(rxSortableColumn): Page objects to jsdoc3

- src/components/rxSelectFilter/scripts/rxSelectFilter.page.js
> docs(rxSelectFilter): Page objects to jsdoc3

- src/quarks/rxLocalStorage/docs/rxLocalStorage.midway.js
- src/quarks/rxLocalStorage/scripts/rxLocalStorage.page.js
> docs(rxLocalStorage): Page objects to jsdoc3

- src/components/rxStatusColumn/scripts/rxStatusColumn.page.js
> docs(rxStatusColumn): Page objects to jsdoc3

- src/quarks/quarks.module.js
- src/quarks/rxBulkSelectController/docs/rxBulkSelectController.docs.html
- src/quarks/rxBulkSelectController/rxBulkSelectController.meta.json
- src/quarks/rxBulkSelectController/scripts/rxBulkSelectController.js
- src/quarks/rxBulkSelectController/scripts/rxBulkSelectController.spec.js
JIRA: https://jira.rax.io/browse/FRMW-703
---
Refactor `rxBulkSelect.rxBulkSelectController` to Quark Controller.
> refactor(rxBulkSelectController): FRMW-703-conver to Quark Controller

- .github/PULL_REQUEST_TEMPLATE.md
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
> chore(github): Automatically add LGTMs to PRs

- src/components/rxAccountInfo/templates/rxAccountInfoBanner.html
Applying null data pattern to rxAccountInfoBanner output.
> fix(rxAccountInfoBanner): apply null data pattern

- .lesshint
- demo/less/_code.less
- demo/less/_palette.less
- demo/less/demoApp.less
- src/components/layout/responsiveLayout.less
- src/components/rxApp/rxApp.less
- src/components/rxBreadcrumbs/rxBreadcrumbs.less
- src/components/rxBulkSelect/docs/rxBulkSelect.demo.less
- src/components/rxButton/rxButton.less
- src/components/rxForm/rxForm.less
- src/components/rxPaginate/rxPaginate.less
- src/components/rxRadio/rxRadio.less
- src/components/rxSearchBox/docs/rxSearchBox.demo.less
- src/components/rxSelect/docs/rxSelect.demo.less
- src/components/rxSelect/rxSelect.less
- src/components/rxToggleSwitch/rxToggleSwitch.less
- src/components/tooltips/tooltips.less
- src/molecules/rxDatePicker/rxDatePicker.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-248
Updated to latest lesshint `v1.3.1` to check `src/` and `demo/less/`.
```sh
npm install -g lesshint@1.3.1
lesshint --config=.lesshint src
lesshint --config=.lesshint demo/less
```
* adds `.lesshint` configuration for @glynnis, @ssalinas24, or others to utilize
* corrects errors reported by latest version
> fix(less): apply lesshinting

- demo/scripts/demoApp.js
- demo/templates/atoms/lists.html
- demo/templates/styles/typography.html
https://jira.rax.io/browse/FRMW-277
> refactor(lists): Put Lists into Atoms

- demo/scripts/demoApp.js
- demo/templates/atoms/tables.html
- demo/templates/molecules/tables.html
https://jira.rax.io/browse/FRMW-273
> refactor(tables): Put Tables into Atoms

- src/components/rxSearchBox/scripts/rxSearchBox.js
- src/components/rxSearchBox/scripts/rxSearchBox.spec.js
JIRA: https://jira.rax.io/browse/FRMW-714
> fix(rxSearchbox): FRMW-714 support undefined and null value

- .mention-bot
This will prevent @rnreekez, @klamping and @chriscantu from trolling us on PRs that touch core parts of our codebase.
> fix(mentionBot): Only mention rackerlabs contributors

- .lesshint
- src/components/rxApp/common.less
- src/components/rxForm/rxForm.less
- src/components/rxMultiSelect/rxMultiSelect.less
- src/components/rxSelect/rxSelect.less
- src/molecules/rxDatePicker/rxDatePicker.less
- src/molecules/rxTimePicker/rxTimePicker.less
JIRA: https://jira.rax.io/browse/FRMW-716
> style(less): Less Hint Exceptions

- .eslintignore
- .eslintignore-spec
- .eslintrc.json
- .eslintrc.spec.json
- package.json
JIRA: https://jira.rax.io/browse/FRMW-705
> chore(npm): Add and configure eslint

- src/components/rxAccountInfo/docs/rxAccountInfo.js
- src/components/rxApp/scripts/rxAppNavItem.spec.js
- src/components/rxBulkSelect/scripts/rxBulkSelect.page.js
- src/components/rxModalAction/scripts/rxModalFooter.js
- src/components/rxMultiSelect/docs/rxMultiSelect.js
- src/components/rxSortableColumn/scripts/rxSortableColumn.page.js
- src/quarks/Permission/scripts/Permission.spec.js
- src/quarks/Session/scripts/Session.spec.js
JIRA: https://jira.rax.io/browse/FRMW-726
> fix(eslint): Addresses 'indent' violations

- src/components/rxAccountInfo/scripts/rxAccountInfo.page.js
- src/components/rxApp/docs/rxApp.midway.js
- src/components/rxApp/scripts/rxPage.page.js
- src/components/rxBreadcrumbs/docs/rxBreadcrumbs.midway.js
- src/components/rxBreadcrumbs/scripts/rxBreadcrumbs.page.js
- src/components/rxBulkSelect/scripts/rxBulkSelect.exercise.js
- src/components/rxBulkSelect/scripts/rxBulkSelect.page.js
- src/components/rxCharacterCount/scripts/rxCharacterCount.exercise.js
- src/components/rxCharacterCount/scripts/rxCharacterCount.page.js
- src/components/rxCollapse/scripts/rxCollapse.page.js
- src/components/rxMetadata/docs/rxMetadata.midway.js
- src/components/rxMetadata/scripts/rxMetadata.page.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.page.js
- src/components/rxOptionTable/scripts/rxOptionTable.page.js
- src/components/rxPaginate/docs/rxPaginate.midway.js
- src/components/rxPaginate/scripts/rxPaginate.exercise.js
- src/components/rxPaginate/scripts/rxPaginate.page.js
- src/components/rxSearchBox/scripts/rxSearchBox.page.js
- src/components/rxSelectFilter/docs/rxSelectFilter.midway.js
- src/components/rxSelectFilter/scripts/rxSelectFilter.page.js
- src/components/rxTags/scripts/rxTags.page.js
- src/components/rxToggleSwitch/scripts/rxToggleSwitch.exercise.js
- src/components/rxToggleSwitch/scripts/rxToggleSwitch.page.js
- src/components/tabs/docs/tabs.midway.js
- src/components/tabs/scripts/tabs.page.js
- src/quarks/rxNotify/scripts/rxNotify.page.js
JIRA: https://jira.rax.io/browse/FRMW-431
> test(main): Remove all instances of main

- guides/testing.md
> docs(testing): Drop usage of main in docs

- src/components/rxMultiSelect/docs/rxMultiSelect.demo.less
- src/components/rxMultiSelect/docs/rxMultiSelect.html
- src/components/rxMultiSelect/docs/rxMultiSelect.js
- src/components/rxMultiSelect/docs/rxMultiSelect.midway.js
- src/components/rxMultiSelect/rxMultiSelect.less
- src/components/rxMultiSelect/rxMultiSelect.module.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.exercise.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.page.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.spec.js
- src/components/rxMultiSelect/scripts/rxSelectOption.js
- src/components/rxMultiSelect/templates/rxMultiSelect.html
- src/components/rxMultiSelect/templates/rxSelectOption.html
- src/components/rxSelect/rxSelect.less
- src/molecules/molecules.module.js
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-641
---
- Refactor `rxMultiSelect` component to remove `rxSelect` dependency.
- Fix `z-index` context stacking bug.
> fix(rxMultiSelect): FRMW-641 remove rxSelect dependency

- CONTRIBUTING.md
> docs(CONTRIBUTING): fix typo (precendents → precedents)

- src/components/rxForm/rxForm.less
JIRA: https://jira.rax.io/browse/FRMW-793
- ~~[x] QE LGTM~~ No change to tests
> fix(css): rxMultiSelect support

- guides/css-styleguide.md
JIRA: https://jira.rax.io/browse/FRMW-429
"Before" just doesn't include the bullet point about kebab case. Probably don't actually need a screenshot for this PR, but uh... :cake:
> docs(cssStyleguide): Add kebab case rule for classes

- src/components/rxFloatingHeader/docs/rxFloatingHeader.html
- src/components/rxFloatingHeader/docs/rxFloatingHeader.js
- src/components/rxFloatingHeader/docs/rxFloatingHeader.midway.js
- src/components/rxMisc/scripts/rxMisc.page.js
JIRA: https://jira.rax.io/browse/FRMW-723
This needs to run on the current version of encore using the current version of protractor.
However, this will enable us to move to 3.x rather easily.
> test(rxMisc): Improved scrollToElement functionality

- demo/templates/styles/color.html
JIRA: https://jira.rax.io/browse/FRMW-542
> refactor(color): Change hex codes to lowercase

- src/components/rxApp/docs/rxApp.demo.less
- src/components/rxApp/docs/rxApp.html
- src/components/rxApp/docs/rxApp.js
- src/components/rxApp/rxApp.less
- src/components/rxApp/scripts/rxApp.js
- src/components/rxApp/templates/rxApp.html
JIRA: https://jira.rax.io/browse/FRMW-796
* Hide nav when app detects it is in iframe
* correct styling for global notifications without nav
* correct external "Source" link when embedded
* add embedded rxApp example
> feat(rxApp): hide navigation if embedded

- src/components/rxPaginate/scripts/rxLoadingOverlay.js
- src/components/rxPaginate/scripts/rxPaginate.spec.js
Issue: #1622 
* remove isolate scope
* renamed key scope variable to denote "private" use
> fix(rxLoadingOverlay): remove isolate scope

- src/components/rxSelect/scripts/rxSelect.page.js
- src/molecules/rxDatePicker/docs/rxDatePicker.html
- src/molecules/rxDatePicker/docs/rxDatePicker.midway.js
- src/molecules/rxDatePicker/rxDatePicker.less
- src/molecules/rxDatePicker/scripts/rxDatePicker.js
- src/molecules/rxDatePicker/scripts/rxDatePicker.page.js
- src/molecules/rxDatePicker/templates/rxDatePicker.html
JIRA: https://jira.rax.io/browse/FRMW-681
---
Refactor `rxDatePicker` to provide a 10-year date range before and after current date.
> FRMW-681: Add 10-year range to rxDatePicker

- demo/less/_rxPermalink.less
- demo/scripts/rxPermalink.js
- demo/templates/rx-permalink.html
JIRA: https://jira.rax.io/browse/FRMW-797
---
Updated `rxPermalink` link location and behavior.
> feat(rxPermalink): FRMW-810 redesign rxPermlink behavior

- src/components/rxPaginate/scripts/rxPaginate.js
- src/utilities/PageTracking/scripts/PageTracking.js
JIRA: https://jira.rax.io/browse/FRMW-707
> docs(PageTracking): Add docs for createInstance

- src/atoms/rxCheckbox/rxCheckbox.less
- src/components/rxAccountInfo/rxAccountInfo.less
- src/components/rxCharacterCount/rxCharacterCount.less
- src/components/rxForm/rxForm.less
- src/components/rxRadio/rxRadio.less
- src/components/rxSearchBox/rxSearchBox.less
- src/components/rxSelect/rxSelect.less
- src/components/rxTags/rxTags.less
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-608
> style(vars): FRMW-608 Cleanup rxForm Component Vars

- src/molecules/rxDatePicker/docs/examples/rxDatePicker.simple.js
- src/molecules/rxDatePicker/docs/rxDatePicker.midway.js
- src/molecules/rxDatePicker/scripts/rxDatePicker.page.js
JIRA: https://jira.rax.io/browse/FRMW-812
---
Updated the demo and midway tests to use local time zone versus the current default UTC.
> fix(demo): FRMW-812 rxDatePicker use local time zone

- .github/PULL_REQUEST_TEMPLATE.md
> fix(prTemplate): Require a dev video review

- src/molecules/rxDatePicker/docs/rxDatePicker.midway.js
- src/molecules/rxDatePicker/scripts/rxDatePicker.page.js
JIRA: https://jira.rax.io/browse/FRMW-825
--- 
Refactor midway test to use `picker.date`.
> fix(rxDatePicker): FRMW-825 fix rxDatePicker midway test

- .github/PULL_REQUEST_TEMPLATE.md
> fix(pullRequestTemplate): Add Design and QE back in

- src/components/rxPaginate/docs/rxPaginate.html
- src/components/rxPaginate/rxPaginate.less
- src/components/rxPaginate/scripts/rxPaginate.page.js
- src/components/rxPaginate/scripts/rxPaginate.spec.js
- src/components/rxPaginate/templates/rxPaginate.html
JIRA: https://jira.rax.io/browse/FRMW-724
As far as I can tell by using throttling in the inspector, the loading overlay is still working as expected, but I'd love for someone to check that carefully in their review.
[Outdated screenshot](https://cloud.githubusercontent.com/assets/1529366/14961165/e26b2f5a-105d-11e6-98b9-995598fc05dd.png)
[Outdated screenshot](https://cloud.githubusercontent.com/assets/1529366/14961189/0792f0f6-105e-11e6-94a5-480ef648f523.png)
[Outdated screenshot](https://cloud.githubusercontent.com/assets/1529366/14961211/24755196-105e-11e6-9fdf-2f001cfaa8b0.png)
[Outdated screenshot](https://cloud.githubusercontent.com/assets/1529366/14961260/5f942d6a-105e-11e6-9bf5-0536c4ab00ee.png)
[Outdated screenshot](https://cloud.githubusercontent.com/assets/1529366/14961248/4ff0d …
> feat(rxPaginate): Use flex grid for responsiveness

- grunt-tasks/component-template/root/component.page.js
I was getting started removing all references of jshint and saw this file...decided it was worth the extra ten minutes to update it to our newer style of page object generation.
JIRA: N/A
> chore(template): Update to newer page object principles

- src/utilities/rxBytesConvert/docs/examples/rxBytesConvert.demo.html
- src/utilities/rxBytesConvert/docs/examples/rxBytesConvert.demo.js
- src/utilities/rxBytesConvert/docs/rxBytesConvert.docs.html
- src/utilities/rxBytesConvert/docs/rxBytesConvert.midway.js
- src/utilities/rxBytesConvert/rxBytesConvert.meta.json
- src/utilities/rxBytesConvert/scripts/rxBytesConvert.js
- src/utilities/rxBytesConvert/scripts/rxBytesConvert.spec.js
- src/utilities/rxDiskSize/scripts/rxDiskSize.spec.js
JIRA: https://jira.rax.io/browse/FRMW-432
> feat(rxBytesConvert): convert from bytes

- demo/less/demoApp.less
- demo/templates/styles/formatting.html
- src/elements/Buttons/docs/examples/button.group.html
- src/elements/Buttons/docs/examples/button.group.less
- src/utilities/rxBytesConvert/scripts/rxBytesConvert.js
Noticed this bug and made a PR since the change is pretty easy and this is one for the 🐜 🐜
> fix(example): Stop collisions, eliminate 'example' as class name

- package.json
JIRA: N/A
I did not find a single use of this library in our project.
> fix(npm): Drop unused semver library

- src/components/rxSortableColumn/docs/rxSortableColumn.js
> docs(rxSortableColumn): Remove unnecessary import.

- src/components/rxApp/scripts/rxAppNavItem.js
- src/components/rxApp/scripts/rxAppNavItem.spec.js
- src/components/rxApp/templates/rxAppNavItem.html
- src/utilities/Environment/scripts/Environment.js
- src/utilities/urlUtils/scripts/urlUtils.js
- src/utilities/urlUtils/scripts/urlUtils.spec.js
JIRA: https://jira.rax.io/browse/FRMW-804
This PR allows for applications to define a set of injectables (constant, value, factory, service, provider) that will allow for further customization of the nav. 
* HREF prefixes for nav items
* target prefixes for nav items
In the future we could also add `target` as nav item definitions (not developed in this PR, just worth noting).
> feat(rxAppNavItem): FRMW-804 Target & Href prefix for nav items

- demo/templates/modules/listCategoryModules.html
- demo/templates/modules/listModules.html
- src/components/rxApp/common.less
- src/components/rxFloatingHeader/docs/rxFloatingHeader.html
- src/components/rxFloatingHeader/rxFloatingHeader.less
- src/components/rxFloatingHeader/scripts/rxFloatingHeader.js
- src/components/rxFloatingHeader/scripts/rxFloatingHeader.spec.js
- src/elements/Tables/docs/examples/table.filtering.html
JIRA: https://jira.rax.io/browse/FRMW-219
> refactor(common): Remove filter-box class

- src/components/rxModalAction/docs/rxModalAction.html
After some back and forth with folks in RED, other developer designers and members of the billing team, there was a consensus that more explicit documentation was needed covering design patters in multi-state modal windows. This attempts to address this in http://rackerlabs.github.io/encore-ui/#/components/rxModalAction.
> More explicit design pattern documentation for multi-state modals

- src/components/rxApp/common.less
JIRA: https://jira.rax.io/browse/FRMW-426
> refactor(title): remove .title CSS classes

- package.json
- src/components/rxBulkSelect/docs/rxBulkSelect.midway.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.exercise.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.page.js
- src/components/rxPaginate/scripts/rxPaginate.exercise.js
- src/components/rxSelectFilter/scripts/rxSelectFilter.page.js
- src/components/typeahead/docs/typeahead.midway.js
- src/elements/Forms/scripts/rxCheckbox.page.js
- src/elements/Forms/scripts/rxDatePicker.page.js
> Protractor 3

- package.json
- src/components/rxBulkSelect/docs/rxBulkSelect.midway.js
- src/components/rxModalAction/docs/rxModalAction.html
- src/components/rxModalAction/docs/rxModalAction.midway.js
- src/components/rxModalAction/scripts/rxModalAction.page.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.exercise.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.page.js
- src/components/rxPaginate/scripts/rxPaginate.exercise.js
- src/components/rxSelectFilter/scripts/rxSelectFilter.page.js
- src/components/typeahead/docs/typeahead.midway.js
- src/elements/Forms/scripts/rxCheckbox.page.js
- src/elements/Forms/scripts/rxDatePicker.page.js
Bring in #1677 and #1668 changes to 2.x
> 2.x sync with 1.x changes (round 1)

- .travis.yml
- utils/quitIfFork.js
> Split CI among Travis and Codeship

- utils/rx-page-objects/src/rxOptionTable.page.js
- utils/rx-page-objects/test/rxOptionTable.midway.js
JIRA: https://jira.rax.io/browse/FRMW-911
---
Deprecated `rxOptionTable.unselectAll()`.  Aliased with `rxOptionTable.deselectAll()`.
> refactor(rxOptionTable_page): FRMW-911 deprecated unselectAll()

- src/components/rxApp/templates/rxPage.html
- src/components/rxCollapse/templates/rxCollapse.html
Remove remaining `.title` class usage in templates
> refactor(cleanup): remove remains of .title class

- utils/visual-regression/components/rxApp.midway.js
see if selector tweak will fix visual regression for custom rxApp
> fix(visreg): tweak rxApp selector

- utils/rx-page-objects/src/tabs.page.js
- utils/rx-page-objects/test/tabs.midway.js
JIRA: https://jira.rax.io/browse/FRMW-909
> refactor(tabs): remove tabs.tab#visit function

- utils/rx-page-objects/index.js
- utils/rx-page-objects/src/rxActionMenu.page.js
- utils/rx-page-objects/src/rxApp.page.js
- utils/rx-page-objects/src/rxCheckbox.exercise.js
- utils/rx-page-objects/src/rxCheckbox.page.js
- utils/rx-page-objects/src/rxCollapse.exercise.js
- utils/rx-page-objects/src/rxCollapse.page.js
- utils/rx-page-objects/src/rxDatePicker.page.js
- utils/rx-page-objects/src/rxFieldName.exercise.js
- utils/rx-page-objects/src/rxForm.page.js
- utils/rx-page-objects/src/rxModalAction.page.js
- utils/rx-page-objects/src/rxRadio.exercise.js
- utils/rx-page-objects/src/rxRadio.page.js
- utils/rx-page-objects/src/rxSearchBox.exercise.js
- utils/rx-page-objects/src/rxSearchBox.page.js
- utils/rx-page-objects/src/rxSelect.exercise.js
- utils/rx-page-objects/src/rxSelect.page.js
- utils/rx-page-objects/src/rxTags.exercise.js
- utils/rx-page-objects/src/rxTags.page.js
- utils/rx-page-objects/src/rxTimePicker.page.js
- utils/rx-page-objects/src/rxToggleSwitch.page.js
- utils/rx-page-objects/test/rxApp.midway.js
- utils/rx-page-objects/test/rxDatePicker.midway.js
JIRA: https://jira.rax.io/browse/FRMW-915
> Deprecate negative predicates

- utils/rx-page-objects/src/rxOptionTable.page.js
JIRA: https://jira.rax.io/browse/FRMW-912
> refactor(rxOptionTable): remove rxOptionTable.unselectAll

- utils/rx-page-objects/src/rxActionMenu.page.js
- utils/rx-page-objects/src/rxApp.page.js
- utils/rx-page-objects/src/rxCheckbox.page.js
- utils/rx-page-objects/src/rxCollapse.page.js
- utils/rx-page-objects/src/rxDatePicker.page.js
- utils/rx-page-objects/src/rxForm.page.js
- utils/rx-page-objects/src/rxRadio.page.js
- utils/rx-page-objects/src/rxSearchBox.page.js
- utils/rx-page-objects/src/rxSelect.page.js
- utils/rx-page-objects/src/rxTags.page.js
- utils/rx-page-objects/src/rxTimePicker.page.js
- utils/rx-page-objects/test/rxForm.midway.js
JIRA: https://jira.rax.io/browse/FRMW-851
> chore(rxPageObjects): remove deprecated api functions

- src/elements/ActionMenu/styles/rxActionMenu.less
- utils/rx-page-objects/src/rxActionMenu.page.js
- utils/rx-page-objects/src/rxDatePicker.page.js
- utils/rx-page-objects/src/rxNotify.page.js
- utils/rx-page-objects/src/rxStatusColumn.page.js
- utils/rx-page-objects/src/rxTimePicker.page.js
- utils/rx-page-objects/test/rxMisc.midway.js
- utils/rx-page-objects/test/rxNotify.midway.js
- utils/rx-page-objects/test/rxSelect.midway.js
JIRA: https://jira.rax.io/browse/FRMW-910
> Chrome e2e tests in 1.x

- src/elements/ActionMenu/styles/rxActionMenu.less
- utils/rx-page-objects/src/rxActionMenu.page.js
- utils/rx-page-objects/src/rxDatePicker.page.js
- utils/rx-page-objects/src/rxNotify.page.js
- utils/rx-page-objects/src/rxStatusColumn.page.js
- utils/rx-page-objects/src/rxTimePicker.page.js
- utils/rx-page-objects/test/rxMisc.midway.js
- utils/rx-page-objects/test/rxNotify.midway.js
- utils/rx-page-objects/test/rxSelect.midway.js
JIRA: https://jira.rax.io/browse/FRMW-910
I've included a Design LGTM because I had to modify the action menu's less file to get chrome to stop complaining about an overlapping element. I already showed @ssalinas24 he said it looked ok.
> Chrome e2e tests

- grunt-tasks/modules.js
- grunt-tasks/options/karma.js
- src/domainOverride.js
- src/utilities/SessionStorage/scripts/SessionStorage.js
- src/utilities/rxLocalStorage/scripts/rxLocalStorage.js
JIRA: https://jira.rax.io/browse/FRMW-895
By modifying the `rxLocalStorage` and `SessionStorage` services (which need a good rename) we are able to allow apps inside of an iframe to communicate with Origin.
> FRMW-895 Share LocalStorage for iFrame Apps Auth

- demo/scripts/demoApp.js
- demo/templates/styles/formatting.html
JIRA: https://jira.rax.io/browse/FRMW-817
> Documentation to support FRMW-817

- utils/rx-page-objects/README.md
- utils/rx-page-objects/src/rxAccountInfo.page.js
- utils/rx-page-objects/src/rxActionMenu.page.js
- utils/rx-page-objects/src/rxDatePicker.page.js
- utils/rx-page-objects/src/rxFeedback.page.js
- utils/rx-page-objects/src/rxLocalStorage.page.js
- utils/rx-page-objects/src/rxMisc.page.js
- utils/rx-page-objects/src/rxMultiSelect.page.js
- utils/rx-page-objects/src/rxNotify.page.js
- utils/rx-page-objects/src/rxSelect.exercise.js
- utils/rx-page-objects/src/rxSelect.page.js
- utils/rx-page-objects/src/rxStatusColumn.page.js
- utils/rx-page-objects/src/rxTags.exercise.js
- utils/rx-page-objects/src/rxTags.page.js
- utils/rx-page-objects/src/rxToggleSwitch.exercise.js
- utils/rx-page-objects/src/rxToggleSwitch.page.js
- utils/rx-page-objects/test/rxAccountInfo.midway.js
- utils/rx-page-objects/test/rxActionMenu.midway.js
- utils/rx-page-objects/test/rxAutoSave.midway.js
- utils/rx-page-objects/test/rxForm.midway.js
- utils/rx-page-objects/test/rxLocalStorage.midway.js
- utils/rx-page-objects/test/rxMisc.midway.js
- utils/rx-page-objects/test/rxModalAction.midway.js
- utils/rx-page-objects/test/rxNotify.midway.js
- utils/rx-page-objects/test/rxSelect.midway.js
- utils/rx-page-objects/test/rxStatusColumn.midway.js
> Deprecate Page Object Functions/Properties

- utils/rx-page-objects/src/rxModalAction.page.js
> test(rxModalAction): Allow redefinitions for built-in modal functions

- utils/rx-page-objects/src/rxAccountInfo.page.js
- utils/rx-page-objects/src/rxActionMenu.page.js
- utils/rx-page-objects/src/rxLocalStorage.page.js
- utils/rx-page-objects/src/rxMultiSelect.page.js
- utils/rx-page-objects/src/rxNotify.page.js
- utils/rx-page-objects/src/rxSelect.page.js
- utils/rx-page-objects/src/rxStatusColumn.page.js
- utils/rx-page-objects/src/rxTags.page.js
- utils/rx-page-objects/src/rxToggleSwitch.page.js
JIRA: n/a
Remove items deprecated in 1.x
> chore(deprecations): remove deprecated functions

- src/elements/Forms/templates/rxDatePicker.html
- utils/rx-page-objects/src/rxDatePicker.page.js
- utils/rx-page-objects/test/rxDatePicker.midway.js
JIRA: https://jira.rax.io/browse/FRMW-850
* no modification to UI display
> refactor(rxDatePicker): page object no longer uses Date params

- .eslintignore-dev
- demo/index.html
- demo/scripts/loadExamples.js
- demo/scripts/rxExample.js
- demo/templates/rx-example.html
- grunt-tasks/build.js
- grunt-tasks/examples.js
- grunt-tasks/util/config.js
JIRA: https://jira.rax.io/browse/FRMW-942
> fix(rxExample): fix performance lag/delay

- utils/rx-page-objects/src/rxMisc.page.js
Relates to https://github.com/rackerlabs/encore-ui/pull/1730
> docs(rxMisc): Deprecate performance metrics function

- src/elements/Links/docs/examples/link.icons.reserved.html
- utils/visual-regression/components/buttons.midway.js
- utils/visual-regression/components/rxAccountInfo.midway.js
- utils/visual-regression/components/rxActionMenu.midway.js
- utils/visual-regression/components/rxFeedback.midway.js
- utils/visual-regression/components/rxForm.midway.js
- utils/visual-regression/components/rxTags.midway.js
> test(visreg): Expand to elements

- .gitignore
- .travis.yml
- guides/testing.md
- package.json
- utils/rx-page-objects/.gitignore
- utils/rx-page-objects/package.json
- utils/rx-page-objects/protractor.chrome.conf.js
- utils/rx-page-objects/protractor.conf.js
- utils/rx-page-objects/protractor.visual.regression.conf.js
- utils/rx-page-objects/src/rxAge.page.js
> chore(testing): Move all testing deps into utils/rx-page-objects

- src/components/rxApp/scripts/rxApp.js
- src/components/rxApp/scripts/rxAppNav.js
- src/components/rxApp/scripts/rxAppSearch.js
- src/components/rxApp/scripts/rxPage.js
- src/components/rxAttributes/scripts/rxAttributes.js
- src/components/rxForm/scripts/rxFormSection.js
- src/components/rxModalAction/docs/rxModalAction.html
- src/components/rxModalAction/scripts/rxModalAction.js
- src/components/rxModalAction/scripts/rxModalFooter.js
- src/components/rxModalAction/scripts/rxModalForm.js
- src/components/rxPaginate/scripts/rxPaginate.js
- src/components/rxStatusColumn/scripts/rxStatusColumn.js
- src/components/rxToggleSwitch/docs/rxToggleSwitch.html
- src/components/rxToggleSwitch/scripts/rxToggleSwitch.js
- src/components/rxToggleSwitch/templates/rxToggleSwitch.html
- src/elements/AccountInfo/scripts/rxAccountInfo.js
- src/elements/Buttons/docs/examples/rxButton.disable.html
- src/elements/Buttons/scripts/rxButton.js
- src/elements/Buttons/scripts/rxButton.spec.js
- src/elements/Buttons/templates/rxButton.html
- src/elements/Forms/scripts/rxDatePicker.js
- src/elements/Forms/scripts/rxTimePicker.js
- src/utilities/PageTracking/scripts/PageTracking.js
- src/utilities/Permission/scripts/Permission.js
- src/utilities/rxAutoSave/scripts/rxAutoSave.js
JIRA: https://jira.rax.io/browse/FRMW-717
> Ng disabled

- src/components/rxMultiSelect/rxMultiSelect.less
- src/components/rxMultiSelect/scripts/rxMultiSelect.js
- src/components/rxMultiSelect/scripts/rxMultiSelect.spec.js
- src/components/rxMultiSelect/templates/rxMultiSelect.html
- src/elements/Forms/scripts/rxDatePicker.js
- src/elements/Forms/scripts/rxTimePicker.js
- src/elements/Forms/styles/rxDatePicker.less
- src/elements/Forms/templates/rxDatePicker.html
- utils/rx-page-objects/src/rxDatePicker.page.js
- utils/rx-page-objects/src/rxMultiSelect.exercise.js
- utils/rx-page-objects/test/rxDatePicker.midway.js
- utils/rx-page-objects/test/rxTimePicker.midway.js
JIRA: https://jira.rax.io/browse/FRMW-914
> Update rxModalAction compatibility with rxDatePicker, rxTimePicker, and rxMultiSelect

- utils/rx-page-objects/test/rxNotify.midway.js
This is blocking all open PRs.
*Note*: I'm going to drop the review on this PR since it only affects our testing setup, and is holding up a large number of other PRs.
> test(alerts): Skip alert tests for chrome 52

- src/elements/Collapse/rxCollapse.meta.json
JIRA: n/a
Correct `displayName` skipped over in [this comment](https://github.com/rackerlabs/encore-ui/pull/1740/files#r71021636)
> fix(Collapse): correct displayName

- demo/templates/styles/color.html
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-978
[Outdated screenshot.](https://cloud.githubusercontent.com/assets/1529366/17146683/e21d173e-5324-11e6-8396-4672a9106efd.png)
@Droogans Guessing this doesn't need a QE LGTM but feel free to add back a checkbox if you think it's called for.
> docs(color): update hex code for red accent

- src/utilities/rxDate/docs/examples/rxDate.demo.html
- src/utilities/rxDate/docs/examples/rxDate.demo.js
- src/utilities/rxDate/docs/rxDate.docs.html
- src/utilities/rxDate/rxDate.meta.json
- src/utilities/rxDate/scripts/rxDate.js
- src/utilities/rxDate/scripts/rxDate.spec.js
- src/utilities/rxDateTime/docs/examples/rxDateTime.demo.html
- src/utilities/rxDateTime/docs/examples/rxDateTime.demo.js
- src/utilities/rxDateTime/docs/rxDateTime.docs.html
- src/utilities/rxDateTime/rxDateTime.meta.json
- src/utilities/rxDateTime/scripts/rxDateTime.js
- src/utilities/rxDateTime/scripts/rxDateTime.spec.js
- src/utilities/rxMomentFormats/rxMomentFormats.meta.json
- src/utilities/rxMomentFormats/scripts/rxMomentFormats.js
- src/utilities/rxMonth/docs/examples/rxMonth.demo.html
- src/utilities/rxMonth/docs/examples/rxMonth.demo.js
- src/utilities/rxMonth/docs/rxMonth.docs.html
- src/utilities/rxMonth/rxMonth.meta.json
- src/utilities/rxMonth/scripts/rxMonth.js
- src/utilities/rxMonth/scripts/rxMonth.spec.js
- src/utilities/rxTime/docs/examples/rxTime.demo.html
- src/utilities/rxTime/docs/examples/rxTime.demo.js
- src/utilities/rxTime/docs/rxTime.docs.html
- src/utilities/rxTime/rxTime.meta.json
- src/utilities/rxTime/scripts/rxTime.js
- src/utilities/rxTime/scripts/rxTime.spec.js
JIRA: https://jira.rax.io/browse/FRMW-817
> feat(DateTimeFilters): create formatting filters for Date and Time

- src/components/rxApp/scripts/rxApp.js
- src/components/rxApp/scripts/rxApp.spec.js
> feat(rxApp): FRMW-953 Allow routes to be updated via an event

- src/elements/Forms/Forms.meta.json
- src/elements/Forms/docs/forms.docs.html
JIRA: https://jira.rax.io/browse/EO-1094
Before
------------
After
-----------
> refactor(textarea): EO-1094 Form Text Area Refactor

- demo/index.html
- grunt-tasks/modules.js
- grunt-tasks/options/concat.js
- grunt-tasks/options/karma.js
- grunt-tasks/options/ngAnnotate.js
- grunt-tasks/options/uglify.js
- grunt-tasks/templates/encore-ui.ejs.js
- grunt-tasks/util/config.js
- src/elements/AccountInfo/scripts/rxAccountInfo.js
- src/utilities/PaginatedItemsSummary/scripts/PaginatedItemsSummary.js
- src/utilities/rxFavicon/scripts/rxFavicon.spec.js
- utils/rx-page-objects/package.json
JIRA: https://jira.rax.io/browse/FRMW-969
The work in this PR came about after noticing that the generated javascript was duplicating DI dependencies. This lead to tweaking the grunt configs, which lead to the discovery that we're generating distributable files that aren't being used. Additionally, several other little things were discovered and corrected.
> Grunt pipeline refactor

- utils/rx-page-objects/src/rxCopy.exercise.js
- utils/rx-page-objects/src/rxCopy.page.js
- utils/rx-page-objects/test/rxCopy.midway.js
JIRA: https://jira.rax.io/browse/FRMW-455
This can be closed and cherry picked if you want. Or merged.
> Frmw 455 rx copy exercises

- .eslintrc.test.json
- .travis.yml
- src/elements/Copy/Copy.meta.json
- src/elements/Copy/docs/Copy.demo.less
- src/elements/Copy/docs/Copy.docs.html
- src/elements/Copy/docs/examples/copy.advanced.html
- src/elements/Copy/docs/examples/copy.advanced.js
- src/elements/Copy/docs/examples/copy.simple.html
- src/elements/Copy/docs/examples/copy.simple.js
- src/elements/Copy/docs/examples/copy.tables.html
- src/elements/Copy/docs/examples/copy.tables.js
- src/elements/Copy/scripts/rxCopy.js
- src/elements/Copy/scripts/rxCopy.spec.js
- src/elements/Copy/styles/rxCopy.less
- src/elements/Copy/templates/rxCopy.html
- src/elements/Metadata/styles/rxMetadata.less
- src/utilities/rxCopyUtil/docs/rxCopyUtil.demo.html
- src/utilities/rxCopyUtil/rxCopyUtil.meta.json
- src/utilities/rxCopyUtil/scripts/rxCopyUtil.js
- src/utilities/rxCopyUtil/scripts/rxCopyUtil.spec.js
- utils/rx-page-objects/src/rxCopy.exercise.js
- utils/rx-page-objects/src/rxCopy.page.js
- utils/rx-page-objects/src/rxStatusColumn.page.js
- utils/rx-page-objects/src/tooltip.page.js
- utils/rx-page-objects/test/rxCopy.midway.js
- utils/visual-regression/components/rxCopy.midway.js
JIRA: https://jira.rax.io/browse/FRMW-455
> FRMW-455: Add Copy Element (rxCopy)

- src/components/rxApp/scripts/rxAppNavItem.js
- src/components/rxApp/scripts/rxAppNavItem.spec.js
- src/components/rxApp/templates/rxAppNavItem.html
JIRA: https://jira.rax.io/browse/FRMW-952
Checks to see if the iframe has url that has been clicked
If it does, do nothing, if it doesn't load into iframe
Defaults to regular link behavior if not in origin
> feat(navItem): Checks url before passing to origin

- .eslintignore-test
- .travis.yml
JIRA: N/A
There was a mistake in my typescript PR that wasn't caught since we don't run linting in pull request builders. This fixes that.
> Lint in pr builders

- src/utilities/rxNotify/docs/rxNotify.docs.html
> fix(demo): correct broken rxNotify link

- src/components/rxPaginate/docs/rxPaginate.html
- utils/rx-page-objects/src/rxPaginate.exercise.js
- utils/rx-page-objects/src/rxPaginate.page.js
- utils/rx-page-objects/test/rxPaginate.midway.js
> E2e rx paginate is displayed

- src/components/rxApp/scripts/rxAppNavItem.js
- src/components/rxApp/scripts/rxAppNavItem.spec.js
> chore(navItemTarget): Use null instead of _self as default target

- src/elements/Forms/styles/rxCheckbox.less
- src/elements/Forms/styles/rxForm.less
- src/elements/Forms/styles/rxRadio.less
- src/elements/Forms/styles/rxSelect.less
- src/elements/Forms/templates/rxTimePicker.html
- src/styles/vars.less
JIRA: https://jira.rax.io/browse/FRMW-566
- ~~[ ] QE LGTM (no change to javascript)~~
Adds form focused styles for directives that have a native counterpart
> style(rxInput): Adds Form focus

- src/components/rxApp/scripts/rxAccountSearch.js
- src/components/rxApp/scripts/rxAtlasSearch.js
- src/components/rxApp/scripts/rxBillingSearch.js
JIRA: https://jira.rax.io/browse/FRMW-1035
> feat(rxNav): check for oriLocationService and use it in search

- src/elements/Buttons/docs/examples/button.animated.html
- src/elements/Buttons/scripts/rxButton.js
- src/elements/Forms/docs/examples/forms.disabled.html
- src/elements/Forms/docs/examples/forms.inputgroups.html
- src/elements/Forms/docs/examples/forms.manualSave.html
- src/elements/Forms/scripts/rxToggleSwitch.js
- src/elements/Forms/scripts/rxToggleSwitch.spec.js
- src/elements/Forms/templates/rxTimePicker.html
- src/elements/Modals/scripts/rxModalAction.js
- src/utilities/rxAutoSave/docs/examples/rxAutoSave.simple.html
JIRA: https://jira.rax.io/browse/FRMW-1045
Part of [3.0.0 Road Map](https://github.com/rackerlabs/encore-ui/wiki/Road-Map#300)
> 3.x remove deprecated attributes

- bower.json
- grunt-tasks/build.js
- grunt-tasks/modules.js
- grunt-tasks/options/concat.js
- grunt-tasks/options/ngAnnotate.js
- grunt-tasks/util/config.js
Part of [3.0.0 Road Map](https://github.com/rackerlabs/encore-ui/wiki/Road-Map#300-september-28-2016)
> chore(bower): stop distributing unnecessary *tpls.js file

- src/components/rxApp/scripts/rxApp.js
- src/utilities/SessionStorage/scripts/SessionStorage.js
- src/utilities/rxLocalStorage/scripts/rxLocalStorage.js
> chore(iframe): try/catch access to the top frame (1.x)

- src/components/rxApp/scripts/rxApp.js
- src/utilities/SessionStorage/scripts/SessionStorage.js
- src/utilities/rxLocalStorage/scripts/rxLocalStorage.js
> chore(iframe): try/catch access to the top frame (2.x)

- src/components/rxApp/scripts/rxApp.js
- src/utilities/SessionStorage/scripts/SessionStorage.js
- src/utilities/rxLocalStorage/scripts/rxLocalStorage.js
> chore(iframe): try/catch access to the top frame (3.X)

- demo/scripts/demoApp.js
Fix broken documentation links and remove unused routes.
> chore(docs): remove dead links and routes

- .eslintignore-test
- src/components/rxEnvironment/scripts/rxEnvironment.spec.js
- src/utilities/Environment/scripts/Environment.js
> chore(Environment): Match origin as prod

- package.json
- utils/rx-page-objects/package.json
> chore(rxPageObjects): Move typings to framework package.json

- package.json
Fix `sh: typings: command not found`
> chore(npm): fix typings path

- src/utilities/SessionStorage/scripts/SessionStorage.js
- src/utilities/rxLocalStorage/scripts/rxLocalStorage.js
> chore(storage): 1.x use current storage

- src/elements/Forms/docs/examples/forms.autoSave.html
JIRA: https://jira.rax.io/browse/FRMW-1011
> fix(Forms): Styling Issue with "Saving Form Data" example

- src/components/rxApp/scripts/rxApp.js
- src/utilities/SessionStorage/scripts/SessionStorage.js
- src/utilities/rxLocalStorage/scripts/rxLocalStorage.js
> fix(windowTop): Remove usage of window.top and use window.parent

- src/utilities/rxAutoSave/scripts/rxAutoSave.js
- src/utilities/rxAutoSave/scripts/rxAutoSave.spec.js
- utils/rx-page-objects/test/rxLocalStorage.midway.js
JIRA: https://jira.rax.io/browse/FRMW-819
> fix(rxAutoSave): Update rxAutoSave to use $location.path()

- package.json
- src/utilities/rxAutoSave/scripts/rxAutoSave.js
- src/utilities/rxAutoSave/scripts/rxAutoSave.spec.js
- src/utilities/urlUtils/scripts/urlUtils.spec.js
- utils/rx-page-objects/package.json
- utils/rx-page-objects/test/rxLocalStorage.midway.js
1.x port of #1852 and #1846, with protractor fix for Codeship
> [1.x] fix(phantomjs): upgrade to PhantomJS 2.x

- package.json
- src/utilities/urlUtils/scripts/urlUtils.spec.js
> [2.x] fix(phantomjs): upgrade to PhantomJS 2.x

- package.json
- src/elements/elements.module.js
- src/index.ngdoc.js
- src/utilities/utilities.module.js
JIRA: https://jira.rax.io/browse/FRMW-222
*index*
*elements*
*utilities*
*index*
*elements*
*utilities*
> chore(ngdocs): Add content to index

- src/elements/Breadcrumbs/docs/examples/Breadcrumbs.simple.html
JIRA: https://jira.rax.io/browse/FRMW-512
> fix(demo): frmw512-rxbreadcrumbs background color fix

- demo/less/_rxPermalink.less
JIRA: https://jira.rax.io/browse/FRMW-856
> refactor(rxPermalink): icon on left

- README.md
> docs(README): fix broken guide links

- bower.json
- demo/index.html
- grunt-tasks/options/karma.js
- grunt-tasks/templates/encore-ui.ejs.js
- src/elements/Forms/docs/examples/forms.intermediatecontrols.html
- src/elements/Forms/docs/examples/forms.intermediatecontrols.js
JIRA: https://jira.rax.io/browse/FRMW-993
(^Noticed after fix during giphy capture that production does not properly validates e-mails with parsers usage/overwritten with checking for "foo")
> refactor(forms): forms updated from parser to validators

- grunt-tasks/shipit.js
> chore(grunt): remove unused task from shipit

- src/components/rxOptionTable/docs/rxOptionTable.meta.json
- src/components/rxOptionTable/scripts/rxOptionTable.js
JIRA: https://jira.rax.io/browse/FRMW-971
> refactor(rxOptionTable): updated option table deprecated message

- demo/scripts/demoApp.js
- demo/templates/modules/showModule.html
- grunt-tasks/util/config.js
- src/elements/Breadcrumbs/docs/examples/Breadcrumbs.simple.js
- src/elements/Buttons/scripts/rxButton.js
- src/elements/Forms/scripts/rxSearchBox.js
- src/elements/Forms/scripts/rxToggleSwitch.js
- src/elements/Modals/scripts/rxModalFooter.js
- src/elements/Tables/scripts/rxStatusColumn.js
- src/elements/Tables/scripts/rxStatusHeader.js
- src/elements/Typeahead/scripts/typeahead.js
- src/utilities/rxNotify/scripts/rxNotify.js
JIRA: https://jira.rax.io/browse/FRMW-1219
* Correct links to ensure they are relative to the documentation root
* Ensure that "View Source" links lead to the proper repo branch on GitHub
> chore(ghPages): Fix links for 3.x versioned docs

- src/utilities/encoreRoutes/scripts/encoreRoutes.js
- src/utilities/rxAppRoutes/scripts/rxAppRoutes.js
- src/utilities/rxVisibility/scripts/rxVisibility.js
- src/utilities/rxVisibilityPathParams/scripts/rxVisibilityPathParams.js
> chore(multiple): Deprecates multiple modules

- src/components/rxApp/scripts/rxAppNav.js
- src/components/rxOptionTable/scripts/rxOptionTable.js
- src/elements/Tables/scripts/rxPaginate.js
- src/utilities/Paginate/scripts/Paginate.js
- src/utilities/PaginatedItemsSummary/scripts/PaginatedItemsSummary.js
- src/utilities/encoreRoutes/docs/encoreRoutes.meta.json
- src/utilities/encoreRoutes/scripts/encoreRoutes.js
- src/utilities/rxAppRoutes/docs/rxAppRoutes.meta.json
- src/utilities/rxAppRoutes/scripts/rxAppRoutes.js
- src/utilities/rxApply/docs/rxApply.meta.json
- src/utilities/rxEnvironment/scripts/rxEnvironment.js
- src/utilities/rxPager/scripts/rxPager.js
- src/utilities/rxStatus/scripts/rxStatus.js
- src/utilities/rxUrlUtils/docs/rxUrlUtils.meta.json
- src/utilities/rxVisibility/docs/rxVisibility.meta.json
- src/utilities/rxVisibilityPathParams/docs/rxVisibilityPathParams.meta.json
* ensure demo pages show deprecated items as deprecated
* ensure we reference replacements for deprecated items in docs
> fix(docs): correct documentation

- .gitignore
> chore(git): Add VS Code directory to .gitignore

- src/utilities/Identity/scripts/Identity.js
- src/utilities/Identity/scripts/Identity.spec.js
- src/utilities/rxAuth/scripts/rxAuth.js
- src/utilities/rxAuth/scripts/rxAuth.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1150
> refactor(Identity): refactor Identity into rxAuth

- utils/rx-page-objects/src/rxFieldName.page.js
- utils/rx-page-objects/src/rxForm.page.js
- utils/rx-page-objects/test/rxForm.midway.js
JIRA: https://jira.rax.io/browse/FRMW-442
> refactor(rxFieldName): split rxFieldName into page object its own file

- src/components/rxApp/styles/rxApp.less
- src/elements/Forms/styles/rxToggleSwitch.less
- src/elements/Modals/styles/modals.less
- src/elements/Notifications/styles/notifications.less
- src/elements/Progressbar/styles/progressbar.less
- src/styles/mixins.less
> chore(mixins): deprecate transition mixins

- src/utilities/StatusUtil/scripts/StatusUtil.js
JIRA: https://jira.rax.io/browse/FRMW-1239
> chore(wip): deprecate StatusUtil

- src/components/rxApp/scripts/rxAppNavItem.js
- src/components/rxApp/scripts/rxAppNavItem.spec.js
- src/utilities/Permission/scripts/Permission.js
- src/utilities/Permission/scripts/Permission.spec.js
- src/utilities/Session/scripts/Session.js
- src/utilities/Session/scripts/Session.spec.js
- src/utilities/rxAuth/scripts/rxAuth.js
JIRA: https://jira.rax.io/browse/FRMW-1158 & https://jira.rax.io/browse/FRMW-1156
(Originally started to add Session into rxAuth -- Session and Permission were to not be added into rxAuth at the same time, due to failing tests, adding them at the same time was better solution)
> refactor(SessionPermission): refactor into rxAuth

- src/utilities/routesCdnPath/scripts/routesCdnPath.js
JIRA: https://jira.rax.io/browse/FRMW-1250
Simple deprecation
> refactor(routesCdnPath): Deprecates routesCdnPath

- src/components/rxApp/scripts/rxAppNavItem.js
- src/components/rxOptionTable/scripts/rxOptionTable.js
- src/elements/AccountInfo/scripts/rxAccountInfo.js
- src/elements/ActionMenu/scripts/rxActionMenu.js
- src/elements/Forms/scripts/rxFieldName.js
- src/elements/InfoPanel/scripts/rxInfoPanel.js
- src/elements/Notifications/scripts/rxNotifications.js
- src/elements/Spinner/scripts/rxSpinner.js
- src/elements/Tables/scripts/rxSelectFilter.js
- src/elements/Tables/scripts/rxSortableColumn.js
- src/elements/Tags/scripts/rxTags.js
- src/utilities/rxAppRoutes/scripts/rxAppRoutes.js
- src/utilities/rxAutoSave/scripts/rxAutoSave.js
- src/utilities/rxEnvironment/scripts/rxEnvironment.js
- src/utilities/rxFormUtils/scripts/rxFormUtils.js
- src/utilities/rxModalFooterTemplates/scripts/rxModalFooterTemplates.js
- src/utilities/rxNestedElement/scripts/rxNestedElement.js
- src/utilities/rxPageTracker/scripts/rxPageTracker.js
- src/utilities/rxPermission/scripts/rxPermission.js
- src/utilities/rxPromiseNotifications/scripts/rxPromiseNotifications.js
- src/utilities/rxTitleize/scripts/rxTitleize.js
JIRA: https://jira.rax.io/browse/FRMW-1263
> refactor(ngdocs): Refactor ng docs with updated changes

- utils/rx-page-objects/src/rxApp.page.js
- utils/rx-page-objects/src/rxButton.page.js
- utils/rx-page-objects/src/rxEnvironment.page.js
- utils/rx-page-objects/src/rxFieldName.page.js
- utils/rx-page-objects/src/rxInfoPanel.page.js
- utils/rx-page-objects/src/rxLocalStorage.page.js
- utils/rx-page-objects/src/rxMisc.page.js
- utils/rx-page-objects/src/rxOptionTable.exercise.js
- utils/rx-page-objects/src/rxOptionTable.page.js
- utils/rx-page-objects/src/rxPage.page.js
- utils/rx-page-objects/src/rxSpinner.page.js
JIRA: https://jira.rax.io/browse/FRMW-1264
- ~~Design LGTM~~ Not Needed
> chore(rxPageObjects): FRMW-1264 - Deprecate Several rx-page-objects

- src/components/rxApp/docs/rxApp.js
- src/components/rxApp/scripts/rxApp.js
- src/components/rxApp/scripts/rxApp.spec.js
- src/elements/Feedback/scripts/rxFeedback.js
- src/elements/Feedback/scripts/rxFeedback.spec.js
- src/elements/Tables/templates/rxPaginate.html
- src/utilities/rxAuth/scripts/rxAuth.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1245
***When deprecating in the 4.x branch for Jira: https://jira.rax.io/browse/FRMW-1245, found areas in the code that required updating on the 3.x branch. Made a new branch called frmw1245-deprecatedbugfixes and made necessary changes so that 3.x branch is up to date.***
> refactor(scripttestupdates): refactoring code from deprecations

- src/elements/Forms/scripts/rxDatePicker.js
- src/elements/Forms/scripts/rxDatePicker.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1274
> fix(rxDatePicker): correct empty string validity

- src/elements/Forms/scripts/rxDatePicker.js
- src/elements/Forms/scripts/rxDatePicker.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1274
> fix(2xrxDatePicker): correct empty string validity (2x branch)

- src/elements/Forms/scripts/rxDatePicker.js
- src/elements/Forms/scripts/rxDatePicker.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1274
> Frmw1274 1xrxdatepickerbug

- src/components/rxApp/scripts/rxAccountSearch.js
- src/components/rxApp/scripts/rxAccountUsers.js
- src/components/rxApp/scripts/rxApp.js
- src/components/rxApp/scripts/rxAppNav.js
- src/components/rxApp/scripts/rxAppNavItem.js
- src/components/rxApp/scripts/rxAppSearch.js
- src/components/rxApp/scripts/rxAtlasSearch.js
- src/components/rxApp/scripts/rxBillingSearch.js
- src/components/rxApp/scripts/rxPage.js
- src/components/rxApp/scripts/rxStatusTag.js
- src/components/rxApp/scripts/rxTicketSearch.js
- src/elements/AccountInfo/scripts/rxAccountInfo.js
- src/elements/Breadcrumbs/scripts/rxBreadcrumbs.js
- src/utilities/encoreRoutes/scripts/encoreRoutes.js
- src/utilities/routesCdnPath/scripts/routesCdnPath.js
- src/utilities/rxBreadcrumbsSvc/scripts/rxBreadcrumbsSvc.js
- src/utilities/rxStatusTags/scripts/rxStatusTags.js
- src/utilities/rxVisibility/scripts/rxVisibility.js
- src/utilities/rxVisibilityPathParams/scripts/rxVisibilityPathParams.js
JIRA: https://jira.rax.io/browse/FRMW-1241
> refactor(rxApp): rxApp and dependencies deprecations for 3.x

- src/utilities/rxTokenInterceptor/scripts/rxTokenInterceptor.js
- src/utilities/rxTokenInterceptor/scripts/rxTokenInterceptor.spec.js
- src/utilities/rxUnauthorizedInterceptor/scripts/rxUnauthorizedInterceptor.js
- src/utilities/rxUnauthorizedInterceptor/scripts/rxUnauthorizedInterceptor.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1302
> fix(interceptors): correct circular dependency

- src/utilities/rxEnvironmentUrl/scripts/rxEnvironmentUrl.js
- src/utilities/rxEnvironmentUrl/scripts/rxEnvironmentUrl.spec.js
- src/utilities/rxFavicon/scripts/rxFavicon.js
- src/utilities/rxFavicon/scripts/rxFavicon.spec.js
- src/utilities/rxUrlUtils/scripts/rxUrlUtils.js
JIRA: https://jira.rax.io/browse/FRMW-1253
> refactor(rxEnvironment): stop using rxEnvironment.get()

- .npmrc
- src/components/rxApp/rxApp.less
JIRA: https://jira.rax.io/browse/FRMW-1310
> style(rxapp): 1.x FRMW-1310 rxApp Background Color

- src/components/rxApp/rxApp.less
JIRA: https://jira.rax.io/browse/FRMW-1310
> style(rxapp): 2.x FRMW-1310 rxApp Background Color

- src/components/rxApp/styles/rxApp.less
JIRA: https://jira.rax.io/browse/FRMW-1310
> style(rxapp): 3.x FRMW-1310 rxApp Background Color

- src/components/rxApp/docs/rxApp.meta.json
- src/elements/AccountInfo/docs/AccountInfo.meta.json
- src/elements/Breadcrumbs/docs/Breadcrumbs.meta.json
- src/utilities/Identity/docs/Identity.meta.json
- src/utilities/Permission/docs/Permission.meta.json
- src/utilities/Session/docs/Session.meta.json
- src/utilities/StatusUtil/docs/StatusUtil.meta.json
- src/utilities/hotkeys/docs/hotkeys.meta.json
- src/utilities/routesCdnPath/docs/routesCdnPath.meta.json
- src/utilities/rxBreadcrumbsSvc/docs/rxBreadcrumbsSvc.meta.json
- src/utilities/rxEnvironmentUrl/docs/rxEnvironmentUrl.meta.json
- src/utilities/rxFormUtils/docs/rxFormUtils.meta.json
- src/utilities/rxStatusTags/docs/rxStatusTags.meta.json
JIRA: https://jira.rax.io/browse/FRMW-1307
> refactor(stabilitypills): updated to correct stability

- demo/scripts/demoApp.directive.js
JIRA: https://jira.rax.io/browse/FRMW-1238
> fix(navHighlighting): correct multi-highlight [4.x]

- grunt-tasks/util/config.js
Update configuration settings.
> chore(config): update build config

- demo/templates/overview.html
> refactor(migrationguide): update migration guide link and text

- src/elements/Modals/scripts/rxModalAction.js
JIRA: https://jira.rax.io/browse/FRMW-1054
> refactor(modaljsdocs): missing rxmodalaction documentation

- src/elements/Forms/docs/examples/forms.manualSave.html
- src/elements/Forms/docs/forms.docs.html
- src/elements/Modals/docs/examples/modals.delete.html
- src/elements/Notifications/scripts/rxNotification.js
- src/elements/Notifications/scripts/rxNotification.spec.js
- src/elements/Notifications/styles/notifications.less
- src/elements/Notifications/templates/rxNotification.html
- src/elements/Notifications/templates/rxNotifications.html
- utils/rx-page-objects/src/rxNotify.page.ts
JIRA: https://jira.rax.io/browse/FRMW-1343
> fix(Notifications): correct notification styling

- src/elements/Tabs/docs/Tabs.meta.json
- src/elements/Tabs/docs/examples/tabs.simple.html
- src/elements/Tabs/docs/tabs.docs.html
- src/elements/Tabs/scripts/rxTab.js
- src/elements/Tabs/scripts/rxTabContentTransclude.js
- src/elements/Tabs/scripts/rxTabHeadingTransclude.js
- src/elements/Tabs/scripts/rxTabs.spec.js
- src/elements/Tabs/scripts/rxTabset.js
- src/elements/Tabs/templates/rxTab.html
- src/elements/Tabs/templates/rxTabset.html
- src/utilities/rxTabsetController/docs/rxTabsetController.docs.html
- src/utilities/rxTabsetController/docs/rxTabsetController.meta.json
- src/utilities/rxTabsetController/scripts/rxTabsetController.js
- utils/rx-page-objects/index.d.ts
- utils/rx-page-objects/src/rxTabs.page.ts
- utils/rx-page-objects/test/rxTabs.midway.ts
- utils/visual-regression/styleguide/layouts.midway.js
JIRA: https://jira.rax.io/browse/FRMW-821
> frmw821-replacesbstabs

- demo/scripts/demoApp.js
JIRA: https://jira.rax.io/browse/FRMW-1356
> FRMW-1356 - fix(demoApp): fix broken routing

- src/components/rxOptionTable/scripts/rxOptionTable.js
- src/components/rxOptionTable/scripts/rxOptionTable.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1349
> FRMW-1349 - fix(rxOptionTable): fix broken call when disableFn is not a function

- src/elements/AccountInfo/scripts/rxAccountInfo.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1350
> FRMW-1350 - fix(rxAccountInfo): fix failing unit tests

- src/elements/Notifications/scripts/rxNotification.js
- src/elements/Notifications/scripts/rxNotification.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1352
> Frmw-1352 - notification

- src/elements/Modals/scripts/rxModalAction.js
- src/elements/Modals/scripts/rxModalAction.spec.js
- src/elements/Modals/scripts/rxModalBackdrop.js
- src/elements/Modals/scripts/rxModalWindow.js
- src/elements/Modals/templates/rxModalBackdrop.html
- src/elements/Modals/templates/rxModalWindow.html
- src/utilities/rxModal/docs/rxModal.docs.html
- src/utilities/rxModal/docs/rxModal.meta.json
- src/utilities/rxModal/scripts/rxModal.js
- src/utilities/rxModal/scripts/rxModalAnimationClass.js
- src/utilities/rxModal/scripts/rxModalStack.js
- src/utilities/rxModal/scripts/rxModalTransclude.js
- src/utilities/rxModal/scripts/rxMultiMap.js
- src/utilities/rxModal/scripts/rxMultiMap.spec.js
- src/utilities/rxModal/scripts/rxStackedMap.js
- src/utilities/rxModal/scripts/rxStackedMap.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1362
> FRMW-1362 - modals

- src/elements/Forms/scripts/rxMultiSelect.js
- src/elements/Forms/scripts/rxMultiSelect.spec.js
- src/elements/Forms/scripts/rxSelectOption.js
JIRA: https://jira.rax.io/browse/FRMW-1351
> FRMW-1351 - multiselect

- src/elements/Tables/scripts/rxPaginate.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1353
> FRMW-1353 - pagination

- src/elements/AccountInfo/docs/AccountInfo.docs.js
- src/elements/AccountInfo/scripts/rxAccountInfo.js
- src/elements/AccountInfo/scripts/rxAccountInfo.spec.js
- src/elements/AccountInfo/templates/rxAccountInfoBanner.html
- utils/rx-page-objects/src/rxAccountInfo.page.js
- utils/rx-page-objects/test/rxAccountInfo.midway.js
JIRA: https://jira.rax.io/browse/FRMW-1323
Adds the collection status of an account to the info banner
Screens pending
> feat(rxAccountInfo): Adds collection status

- src/elements/Modals/scripts/rxModalAction.js
> backport(docs): rxModalAction 'controller' param

- demo/scripts/layout/page/layoutDataTableController.js
- demo/templates/styles/layouts/data-table-page.html
- utils/visual-regression/components/rxForm.midway.js
> refactor(demo): stop using deprecated items

- src/utilities/rxSortEmptyTop/scripts/rxSortEmptyTop.js
- src/utilities/rxSortEmptyTop/scripts/rxSortEmptyTop.spec.js
JIRA: https://jira.rax.io/browse/FRMW-1354
> frmw1354-sortemptytopissues

- src/elements/Forms/docs/forms.docs.html
- src/elements/Forms/docs/radio.docs.js
> fix(radio): fix failing midways

- src/elements/Forms/docs/forms.docs.html
> test(rxSelect): fix failing midways

- demo/less/_palette.less
- demo/less/_rxExample.less
- demo/less/_rxPermalink.less
- demo/less/_rxStability.less
- demo/less/demoApp.less
- demo/templates/styles/color.html
JIRA: https://jira.rax.io/browse/FRMW-1367
> frmw1367-docscssvars

- src/elements/Forms/docs/examples/forms.intermediatecontrols.html
- src/elements/Forms/docs/forms.docs.html
- src/elements/Forms/scripts/rxInlineError.js
- src/elements/Forms/styles/rxForm.less
JIRA: https://jira.rax.io/browse/FRMW-1372
> refactor(inlineerrors): update rxinlineerror

- src/elements/Forms/docs/forms.docs.html
- src/elements/Forms/scripts/rxCharacterCount.js
- src/elements/Forms/scripts/rxCharacterCount.spec.js
- utils/rx-page-objects/src/rxCharacterCount.exercise.js
- utils/rx-page-objects/test/rxCharacterCount.midway.js
JIRA: https://jira.rax.io/browse/FRMW-434 & https://jira.rax.io/browse/FRMW-1377
(removed)
> frmw434 -rxcharactercount

- .travis.yml
- grunt-tasks/util/config.js
- utils/rx-page-objects/package.json
Preparing `4.x` branch for archival purposes.
> chore(config): update github.branch for legacy branch

- bower.json
- grunt-tasks/util/config.js
- package.json
- utils/rx-page-objects/package.json
Update config to publish docs to 5.x
> chore(config): dir.docs = 'build/5.x' [skip ci]
